void AddSC_boss_exarch_maladaar();
void AddSC_boss_shirrak_the_dead_watcher();
void AddSC_boss_nexusprince_shaffar();
void AddSC_boss_pandemonius();
void AddSC_boss_anzu();
void AddSC_boss_darkweaver_syth();
void AddSC_boss_talon_king_ikiss();
void AddSC_instance_sethekk_halls();
void AddSC_sethekk_halls();
void AddSC_boss_ambassador_hellmaw();
void AddSC_boss_blackheart_the_inciter();
void AddSC_boss_grandmaster_vorpil();
void AddSC_boss_murmur();
void AddSC_instance_shadow_labyrinth();
void AddSC_azuremyst_isle();
void AddSC_black_temple();
void AddSC_boss_gurtogg_bloodboil();
void AddSC_boss_illidan();
void AddSC_boss_mother_shahraz();
void AddSC_boss_reliquary_of_souls();
void AddSC_boss_shade_of_akama();
void AddSC_boss_supremus();
void AddSC_boss_teron_gorefiend();
void AddSC_boss_najentus();
void AddSC_boss_illidari_council();
void AddSC_instance_black_temple();
void AddSC_blades_edge_mountains();
void AddSC_bloodmyst_isle();
void AddSC_boss_fathomlord_karathress();
void AddSC_boss_hydross_the_unstable();
void AddSC_boss_lady_vashj();
void AddSC_boss_leotheras_the_blind();
void AddSC_boss_the_lurker_below();
void AddSC_boss_morogrim_tidewalker();
void AddSC_instance_serpentshrine_cavern();
void AddSC_boss_ahune();
void AddSC_instance_slave_pens();
void AddSC_slave_pens();
void AddSC_boss_hydromancer_thespia();
void AddSC_boss_mekgineer_steamrigger();
void AddSC_boss_warlord_kalithresh();
void AddSC_instance_steam_vault();
void AddSC_boss_hungarfen();
void AddSC_boss_the_black_stalker();
void AddSC_eversong_woods();
void AddSC_ghostlands();
void AddSC_boss_gruul();
void AddSC_boss_high_king_maulgar();
void AddSC_instance_gruuls_lair();
void AddSC_boss_broggok();
void AddSC_boss_kelidan_the_breaker();
void AddSC_boss_the_maker();
void AddSC_instance_blood_furnace();
void AddSC_boss_omor_the_unscarred();
void AddSC_boss_vazruden_the_herald();
void AddSC_boss_watchkeeper_gargolmar();
void AddSC_boss_magtheridon();
void AddSC_instance_magtheridons_lair();
void AddSC_boss_grand_warlock_nethekurse();
void AddSC_boss_warbringer_omrogg();
void AddSC_boss_warchief_kargath_bladefist();
void AddSC_instance_shattered_halls();
void AddSC_shattered_halls();
void AddSC_instance_ramparts();
void AddSC_hellfire_peninsula();
void AddSC_isle_of_queldanas();
void AddSC_boss_felblood_kaelthas();
void AddSC_boss_priestess_delrissa();
void AddSC_boss_selin_fireheart();
void AddSC_boss_vexallus();
void AddSC_instance_magisters_terrace();
void AddSC_nagrand();
void AddSC_netherstorm();
void AddSC_shadowmoon_valley();
void AddSC_shartuul_event();
void AddSC_shattrath_city();
void AddSC_silvermoon_city();
void AddSC_boss_brutallus();
void AddSC_boss_eredar_twins();
void AddSC_boss_felmyst();
void AddSC_boss_kalecgos();
void AddSC_boss_kiljaeden_new();
void AddSC_boss_muru();
void AddSC_instance_sunwell_plateau();
void AddSC_sunwell_plateau();
void AddSC_arcatraz();
void AddSC_boss_harbinger_skyriss();
void AddSC_instance_arcatraz();
void AddSC_boss_high_botanist_freywinn();
void AddSC_boss_laj();
void AddSC_boss_warp_splinter();
void AddSC_boss_alar();
void AddSC_boss_high_astromancer_solarian();
void AddSC_boss_kaelthas();
void AddSC_boss_void_reaver();
void AddSC_instance_the_eye();
void AddSC_the_eye();
void AddSC_boss_gatewatcher_iron_hand();
void AddSC_boss_mechanolord_capacitus();
void AddSC_boss_nethermancer_sepethrea();
void AddSC_boss_pathaleon_the_calculator();
void AddSC_instance_mechanar();
void AddSC_mechanar();
void AddSC_terokkar_forest();
void AddSC_zangarmarsh();
void AddSC_boss_akilzon();
void AddSC_boss_halazzi();
void AddSC_boss_hex_lord_malacrass();
void AddSC_boss_janalai();
void AddSC_boss_nalorakk();
void AddSC_boss_zuljin();
void AddSC_instance_zulaman();
void AddSC_zulaman();

void AddOutlandScripts()
{
    AddSC_boss_exarch_maladaar();
    AddSC_boss_shirrak_the_dead_watcher();
    AddSC_boss_nexusprince_shaffar();
    AddSC_boss_pandemonius();
    AddSC_boss_anzu();
    AddSC_boss_darkweaver_syth();
    AddSC_boss_talon_king_ikiss();
    AddSC_instance_sethekk_halls();
    AddSC_sethekk_halls();
    AddSC_boss_ambassador_hellmaw();
    AddSC_boss_blackheart_the_inciter();
    AddSC_boss_grandmaster_vorpil();
    AddSC_boss_murmur();
    AddSC_instance_shadow_labyrinth();
    AddSC_azuremyst_isle();
    AddSC_black_temple();
    AddSC_boss_gurtogg_bloodboil();
    AddSC_boss_illidan();
    AddSC_boss_mother_shahraz();
    AddSC_boss_reliquary_of_souls();
    AddSC_boss_shade_of_akama();
    AddSC_boss_supremus();
    AddSC_boss_teron_gorefiend();
    AddSC_boss_najentus();
    AddSC_boss_illidari_council();
    AddSC_instance_black_temple();
    AddSC_blades_edge_mountains();
    AddSC_bloodmyst_isle();
    AddSC_boss_fathomlord_karathress();
    AddSC_boss_hydross_the_unstable();
    AddSC_boss_lady_vashj();
    AddSC_boss_leotheras_the_blind();
    AddSC_boss_the_lurker_below();
    AddSC_boss_morogrim_tidewalker();
    AddSC_instance_serpentshrine_cavern();
    AddSC_boss_ahune();
    AddSC_instance_slave_pens();
    AddSC_slave_pens();
    AddSC_boss_hydromancer_thespia();
    AddSC_boss_mekgineer_steamrigger();
    AddSC_boss_warlord_kalithresh();
    AddSC_instance_steam_vault();
    AddSC_boss_hungarfen();
    AddSC_boss_the_black_stalker();
    AddSC_eversong_woods();
    AddSC_ghostlands();
    AddSC_boss_gruul();
    AddSC_boss_high_king_maulgar();
    AddSC_instance_gruuls_lair();
    AddSC_boss_broggok();
    AddSC_boss_kelidan_the_breaker();
    AddSC_boss_the_maker();
    AddSC_instance_blood_furnace();
    AddSC_boss_omor_the_unscarred();
    AddSC_boss_vazruden_the_herald();
    AddSC_boss_watchkeeper_gargolmar();
    AddSC_boss_magtheridon();
    AddSC_instance_magtheridons_lair();
    AddSC_boss_grand_warlock_nethekurse();
    AddSC_boss_warbringer_omrogg();
    AddSC_boss_warchief_kargath_bladefist();
    AddSC_instance_shattered_halls();
    AddSC_shattered_halls();
    AddSC_instance_ramparts();
    AddSC_hellfire_peninsula();
    AddSC_isle_of_queldanas();
    AddSC_boss_felblood_kaelthas();
    AddSC_boss_priestess_delrissa();
    AddSC_boss_selin_fireheart();
    AddSC_boss_vexallus();
    AddSC_instance_magisters_terrace();
    AddSC_nagrand();
    AddSC_netherstorm();
    AddSC_shadowmoon_valley();
    AddSC_shartuul_event();
    AddSC_shattrath_city();
    AddSC_silvermoon_city();
    AddSC_boss_brutallus();
    AddSC_boss_eredar_twins();
    AddSC_boss_felmyst();
    AddSC_boss_kalecgos();
    AddSC_boss_kiljaeden_new();
    AddSC_boss_muru();
    AddSC_instance_sunwell_plateau();
    AddSC_sunwell_plateau();
    AddSC_arcatraz();
    AddSC_boss_harbinger_skyriss();
    AddSC_instance_arcatraz();
    AddSC_boss_high_botanist_freywinn();
    AddSC_boss_laj();
    AddSC_boss_warp_splinter();
    AddSC_boss_alar();
    AddSC_boss_high_astromancer_solarian();
    AddSC_boss_kaelthas();
    AddSC_boss_void_reaver();
    AddSC_instance_the_eye();
    AddSC_the_eye();
    AddSC_boss_gatewatcher_iron_hand();
    AddSC_boss_mechanolord_capacitus();
    AddSC_boss_nethermancer_sepethrea();
    AddSC_boss_pathaleon_the_calculator();
    AddSC_instance_mechanar();
    AddSC_mechanar();
    AddSC_terokkar_forest();
    AddSC_zangarmarsh();
    AddSC_boss_akilzon();
    AddSC_boss_halazzi();
    AddSC_boss_hex_lord_malacrass();
    AddSC_boss_janalai();
    AddSC_boss_nalorakk();
    AddSC_boss_zuljin();
    AddSC_instance_zulaman();
    AddSC_zulaman();
}
