ALTER TABLE `creature_template`   
  ADD COLUMN IF NOT EXISTS `spell_school_immune_mask` INT(3) UNSIGNED DEFAULT 0  NOT NULL AFTER `mechanic_immune_mask`;

UPDATE creature_template_addon SET auras = NULL WHERE entry IN (575, 22311, 17167, 691, 11256, 17917, 510, 22311, 17156, 17157, 17158, 17159, 22313, 329, 92, 17153, 17155, 17167, 691, 11256, 17917, 510, 22310);
DELETE FROM creature_template_addon WHERE path_id = 0 AND mount = 0 AND bytes0 = 0 AND bytes1 = 0 AND bytes2 = 0 AND emote = 0 AND moveflags = 0 AND (auras = 0 OR auras IS NULL);

-- fire
UPDATE creature_template SET spell_school_immune_mask = spell_school_immune_mask | 4 WHERE entry IN (575, 22311);
-- nature
UPDATE creature_template SET spell_school_immune_mask = spell_school_immune_mask | 8 WHERE entry IN (22310, 17167, 691, 11256, 17917, 510, 22311, 17160, 17156, 17157, 17158, 17159, 22313, 329, 92);
-- frost
UPDATE creature_template SET spell_school_immune_mask = spell_school_immune_mask | 16 WHERE entry IN (17153, 17155, 17167, 691, 11256, 17917, 510);
-- shadow
-- arcane
UPDATE creature_template SET spell_school_immune_mask = spell_school_immune_mask | 64 WHERE entry IN (22310);

DELETE FROM spell_template_override WHERE entry IN (53101, 53102, 53103, 53104, 53105);


-- some more immunities from TC
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 92;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 691;
UPDATE creature_template SET spell_school_immune_mask = 32 WHERE entry = 703;
UPDATE creature_template SET spell_school_immune_mask = 32 WHERE entry = 1043;
UPDATE creature_template SET spell_school_immune_mask = 32 WHERE entry = 1364;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 2091;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 2108;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 2258;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 2447;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 2592;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 2726;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 2735;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 2736;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 2752;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 2760;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 2761;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 2762;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 2791;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 3917;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 4036;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 4037;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 4038;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 4499;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 4676;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 5461;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 5462;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 5850;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 5852;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 7079;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 7132;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 7137;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 7428;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 7429;
UPDATE creature_template SET spell_school_immune_mask = 52 WHERE entry = 7664;
UPDATE creature_template SET spell_school_immune_mask = 84 WHERE entry = 7734;
UPDATE creature_template SET spell_school_immune_mask = 84 WHERE entry = 7735;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 9016;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 9017;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 9026;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 9453;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 9816;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 9878;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 9879;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 10198;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 10202;
UPDATE creature_template SET spell_school_immune_mask = 124 WHERE entry = 10485;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 10642;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 10662;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 10663;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 10664;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 10756;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 10757;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 11321;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 11480;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 11483;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 11502;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 11666;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 11667;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 11668;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 11744;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 11777;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 11778;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 11779;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 11783;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 11784;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 12056;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 12143;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 12201;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 12237;
UPDATE creature_template SET spell_school_immune_mask = 126 WHERE entry = 12457;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 13280;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 14435;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 14455;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 16488;
UPDATE creature_template SET spell_school_immune_mask = 126 WHERE entry = 16491;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 16530;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 16570;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 16854;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 17085;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 17153;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 17154;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 17155;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 17156;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 17157;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 17158;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 17159;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 17160;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 17167;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 17207;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 17358;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 18062;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 18181;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 18864;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 18865;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 18866;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 18867;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 19203;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 19204;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 19205;
UPDATE creature_template SET spell_school_immune_mask = 32 WHERE entry = 19206;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 19973;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 20516;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 20702;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 20703;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 20704;
UPDATE creature_template SET spell_school_immune_mask = 32 WHERE entry = 20705;
UPDATE creature_template SET spell_school_immune_mask = 96 WHERE entry = 21032;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 21428;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 21706;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 21707;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 21728;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 22009;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 22035;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 22036;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 22309;
UPDATE creature_template SET spell_school_immune_mask = 64 WHERE entry = 22310;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 22323;
UPDATE creature_template SET spell_school_immune_mask = 8 WHERE entry = 23029;
UPDATE creature_template SET spell_school_immune_mask = 4 WHERE entry = 25001;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 25740;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 25755;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 25756;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 25757;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 25865;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26116;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26178;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26204;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26214;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26215;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26216;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26338;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26339;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26340;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26341;
UPDATE creature_template SET spell_school_immune_mask = 16 WHERE entry = 26342;