
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','0','0','Energy. Power. My people are addicted to it... a dependence made manifest after the Sunwell was destroyed. Welcome... to the future. A pity you are too late to stop it. No one can stop me now! Selama ashal\'anore!','14','0','100','0','0','11256','0','kaelthas SAY_INTRO');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','1','0','Capernian will see to it that your stay here is a short one.','14','0','100','0','0','11257','0','kaelthas SAY_INTRO_CAPERNIAN');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','2','0','Well done, you have proven worthy to test your skills against my master engineer, Telonicus.','14','0','100','0','0','11258','0','kaelthas SAY_INTRO_TELONICUS');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','3','0','Let us see how your nerves hold up against the Darkener, Thaladred.','14','0','100','0','0','11259','0','kaelthas SAY_INTRO_THALADRED');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','4','0','You have persevered against some of my best advisors... but none can withstand the might of the Blood Hammer. Behold, Lord Sanguinar!','14','0','100','0','0','11260','0','kaelthas SAY_INTRO_SANGUINAR');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','5','0','As you see, I have many weapons in my arsenal...','14','0','100','0','0','11261','0','kaelthas SAY_PHASE2_WEAPON');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','6','0','Perhaps I underestimated you. It would be unfair to make you fight all four advisors at once, but... fair treatment was never shown to my people. I\'m just returning the favor.','14','0','100','0','0','11262','0','kaelthas SAY_PHASE3_ADVANCE');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','7','0','Alas, sometimes one must take matters into one\'s own hands. Balamore shanal!','14','0','100','0','0','11263','0','kaelthas SAY_PHASE4_INTRO2');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','8','0','I have not come this far to be stopped! The future I have planned will not be jeopardized! Now you will taste true power!','14','0','100','0','0','11273','0','kaelthas SAY_PHASE5_NUTS');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','9','0','You will not prevail.','14','0','100','0','0','11270','0','kaelthas SAY_SLAY1');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','9','1','You gambled...and lost.','14','0','100','0','0','11271','0','kaelthas SAY_SLAY2');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','9','2','This was Child\'s play.','14','0','100','0','0','11272','0','kaelthas SAY_SLAY3');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','10','0','Obey me.','14','0','100','0','0','11268','0','kaelthas SAY_MINDCONTROL1');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','10','1','Bow to my will.','14','0','100','0','0','11269','0','kaelthas SAY_MINDCONTROL2');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','11','0','Let us see how you fare when your world is turned upside down.','14','0','100','0','0','11264','0','kaelthas SAY_GRAVITYLAPSE1');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','11','1','Having trouble staying grounded?','14','0','100','0','0','11265','0','kaelthas SAY_GRAVITYLAPSE2');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','12','0','Anara\'nel belore!','14','0','100','0','0','11267','0','kaelthas SAY_SUMMON_PHOENIX1');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','12','1','By the power of the sun!','14','0','100','0','0','11266','0','kaelthas SAY_SUMMON_PHOENIX2');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','13','0','For...Quel...thalas!','14','0','100','0','0','11274','0','kaelthas SAY_DEATH');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','14','0','%s begins to cast Pyroblast!','41','0','100','0','0','0','0','kaelthas SAY_PYROBLAST');

replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','0','0','Tal anu\'men no Sin\'dorei!','14','0','100','0','0','11134','0','solarian SAY_AGGRO');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','1','0','Ha ha ha! You are hopelessly outmatched!','14','0','100','0','0','11139','0','solarian SAY_SUMMON1');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','2','0','I will crush your delusions of grandeur!','14','0','100','0','0','11140','0','solarian SAY_SUMMON2');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','3','0','Your soul belongs to the Abyss!','14','0','100','0','0','11136','0','solarian SAY_KILL1');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','3','1','By the blood of the Highborne!','14','0','100','0','0','11137','0','solarian SAY_KILL2');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','3','2','For the Sunwell!','14','0','100','0','0','11138','0','solarian SAY_KILL3');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','4','0','The warmth of the sun... awaits.','14','0','100','0','0','11135','0','solarian SAY_DEATH');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','5','0','Enough of this! Now I call upon the fury of the cosmos itself.','14','0','100','0','0','0','0','solarian SAY_VOIDA');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('18805','6','0','I become ONE... with the VOID!','14','0','100','0','0','0','0','solarian SAY_VOIDB');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20060','0','0','Blood for blood!','14','0','100','0','0','11152','0','sanguinar SAY_SANGUINAR_AGGRO');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20060','1','0','NO! I ...will... not...','14','0','100','0','0','11153','0','sanguinar SAY_SANGUINAR_DEATH');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20062','0','0','The sin\'dore reign supreme!','14','0','100','0','0','11117','0','capernian SAY_CAPERNIAN_AGGRO');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20062','1','0','This is not over!','14','0','100','0','0','11118','0','capernian SAY_CAPERNIAN_DEATH');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20063','0','0','Anar\'alah belore!','14','0','100','0','0','11157','0','telonicus SAY_TELONICUS_AGGRO');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20063','1','0','More perils... await','14','0','100','0','0','11158','0','telonicus SAY_TELONICUS_DEATH');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20064','0','0','Prepare yourselves!','14','0','100','0','0','11203','0','thaladred SAY_THALADRED_AGGRO');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20064','1','0','Forgive me, my prince! I have... failed.','14','0','100','0','0','11204','0','thaladred SAY_THALADRED_DEATH');
replace into `creature_text` (`CreatureID`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20064','2','0','%s sets his gaze on $N!','16','0','100','0','0','0','0','thaladred EMOTE_THALADRED_GAZE');

REPLACE INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`) 
VALUES('81499','184596','550','1','744.045','-44.6345','46.661','3.14159','0','0','1','0.00000126759','7200','255','1','');
REPLACE INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`,`position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`) 
VALUES('81500','184597','550','1','744.045','42.3536','46.661','3.14159','0','0','1','0.00000126759','7200','255','1','');


replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20060','0','0','0','0','0','100','0','0','0','15000','15000','11','44863','0','0','0','0','0','1','0','0','0','0','0','0','0','Lord Sanguinar - In Combat - Cast Bellowing Roar');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20060','0','1','2','6','0','100','0','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Lord Sanguinar - On Death - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20060','0','2','0','61','0','100','0','0','0','0','0','11','36709','0','0','0','0','0','1','0','0','0','0','0','0','0','Lord Sanguinar - On Death - Cast Spell');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','0','0','0','0','100','0','0','0','2500','2500','11','36971','64','0','0','0','0','2','0','0','0','0','0','0','0','Grand Astromancer Capernian - In Combat - Cast Fireball');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','1','0','0','0','100','0','7000','10000','18500','20500','11','37018','0','0','0','0','0','5','30','0','0','0','0','0','0','Grand Astromancer Capernian - In Combat - Cast Conflagration');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','2','0','0','0','100','0','3000','3000','6000','6000','11','36970','0','0','0','0','0','5','8','0','0','0','0','0','0','Grand Astromancer Capernian - In Combat - Cast Arcane Burst');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','3','4','6','0','100','0','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Grand Astromancer Capernian - On Death - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','4','0','61','0','100','0','0','0','0','0','11','36709','0','0','0','0','0','1','0','0','0','0','0','0','0','Grand Astromancer Capernian - On Death - Cast Spell');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20063','0','0','0','0','0','100','0','0','0','2000','2000','11','37036','64','0','0','0','0','2','0','0','0','0','0','0','0','Master Engineer Telonicus - In Combat - Cast Bomb');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20063','0','1','0','0','0','100','0','5000','10000','20000','20000','11','37027','0','0','0','0','0','5','100','0','0','0','0','0','0','Master Engineer Telonicus - In Combat - Cast Remote Toy');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20063','0','2','3','6','0','100','0','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Master Engineer Telonicus - On Death - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20063','0','3','0','61','0','100','0','0','0','0','0','11','36709','0','0','0','0','0','1','0','0','0','0','0','0','0','Master Engineer Telonicus - On Death - Cast Spell');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','0','1','0','0','100','0','100','100','10000','10000','64','1','0','0','0','0','0','18','100','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Store Target');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','1','2','61','0','100','0','0','0','0','0','14','0','100','0','0','0','0','1','0','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Modify Threat PCT All');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','2','3','61','0','100','0','0','0','0','0','49','0','0','0','0','0','0','12','1','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Attack Start');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','3','4','61','0','100','0','0','0','0','0','1','2','0','0','0','0','0','12','1','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','4','0','61','0','100','0','0','0','0','0','138','10000000','0','0','0','0','0','12','1','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Modify Threat');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','5','0','0','0','100','0','4000','6000','9000','12000','11','36966','0','0','0','0','0','2','0','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Cast Psychic Blow');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','6','0','0','0','100','0','3000','4000','8000','10000','11','36965','0','0','0','0','0','2','0','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Cast Rend');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','7','0','13','0','100','0','15000','15000','0','0','11','30225','0','0','0','0','0','2','0','0','0','0','0','0','0','Thaladred the Darkener - Victim Casting - Cast Silence');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','8','9','6','0','100','0','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Thaladred the Darkener - On Death - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','9','0','61','0','100','0','0','0','0','0','11','36709','0','0','0','0','0','1','0','0','0','0','0','0','0','Thaladred the Darkener - On Death - Cast Spell');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','10','0','25','0','100','0','0','0','0','0','59','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Thaladred the Darkener - On Reset - Set Run false');

UPDATE creature_template SET ScriptName = "", AIName = "SmartAI" WHERE entry IN (20064, 20060, 20062, 20063);

REPLACE INTO spawn_group (groupId, spawnType, spawnid) VALUES (1, 0, 12525);
REPLACE INTO spawn_group (groupId, spawnType, spawnid) VALUES (1, 0, 12524);
REPLACE INTO spawn_group (groupId, spawnType, spawnid) VALUES (1, 0, 12523);
REPLACE INTO spawn_group (groupId, spawnType, spawnid) VALUES (1, 0, 12522);

REPLACE INTO spell_script_names VALUES (35859, "spell_kaelthas_summon_nether_vapor");
REPLACE INTO spell_script_names VALUES (35941, "spell_kaelthas_gravity_lapse");
REPLACE INTO spell_script_names VALUES (35869, "spell_kaelthas_nether_beam");