
DROP TABLE IF EXISTS `spell_template_override`;
CREATE TABLE `spell_template_override` (
  `entry` int(10) unsigned NOT NULL,
  `category` int(9) unsigned,
  `dispel` int(9) unsigned,
  `mechanic` int(9) unsigned,
  `attributes` int(9) unsigned,
  `attributesEx` int(9) unsigned,
  `attributesEx2` int(9) unsigned,
  `attributesEx3` int(9) unsigned,
  `attributesEx4` int(9) unsigned,
  `attributesEx5` int(9) unsigned,
  `attributesEx6` int(9) unsigned,
  `stances` int(9) unsigned,
  `stancesNot` int(9) unsigned,
  `targets` int(9) unsigned,
  `targetCreatureType` int(9) unsigned,
  `requiresSpellFocus` int(9) unsigned,
  `facingCasterFlags` int(9) unsigned,
  `casterAuraState` int(9) unsigned,
  `targetAuraState` int(9) unsigned,
  `casterAuraStateNot` int(9) unsigned,
  `targetAuraStateNot` int(9) unsigned,
  `castingTimeIndex` int(9) unsigned,
  `recoveryTime` int(9) unsigned,
  `categoryRecoveryTime` int(9) unsigned,
  `interruptFlags` int(9) unsigned,
  `auraInterruptFlags` int(9) unsigned,
  `channelInterruptFlags` int(9) unsigned,
  `procFlags` int(9) unsigned,
  `procChance` int(9) unsigned,
  `procCharges` int(9) unsigned,
  `maxLevel` int(9) unsigned,
  `baseLevel` int(9) unsigned,
  `spellLevel` int(9) unsigned,
  `durationIndex` int(9) unsigned,
  `powerType` int(9),
  `manaCost` int(9) unsigned,
  `manaCostPerlevel` int(9) unsigned,
  `manaPerSecond` int(9) unsigned,
  `manaPerSecondPerLevel` int(9) unsigned,
  `rangeIndex` int(9) unsigned,
  `speed` float,
  `stackAmount` int(9) unsigned,
  `totem1` int(9) unsigned,
  `totem2` int(9) unsigned,
  `reagent1` int(9),
  `reagent2` int(9),
  `reagent3` int(9),
  `reagent4` int(9),
  `reagent5` int(9),
  `reagent6` int(9),
  `reagent7` int(9),
  `reagent8` int(9),
  `reagentCount1` int(9) unsigned,
  `reagentCount2` int(9) unsigned,
  `reagentCount3` int(9) unsigned,
  `reagentCount4` int(9) unsigned,
  `reagentCount5` int(9) unsigned,
  `reagentCount6` int(9) unsigned,
  `reagentCount7` int(9) unsigned,
  `reagentCount8` int(9) unsigned,
  `equippedItemClass` int(9),
  `equippedItemSubClassMask` int(9),
  `equippedItemInventoryTypeMask` int(9),
  `effect1` int(9) unsigned,
  `effect2` int(9) unsigned,
  `effect3` int(9) unsigned,
  `effectDieSides1` int(9),
  `effectDieSides2` int(9),
  `effectDieSides3` int(9),
  `effectBaseDice1` int(9),
  `effectBaseDice2` int(9),
  `effectBaseDice3` int(9),
  `effectDicePerLevel1` float,
  `effectDicePerLevel2` float,
  `effectDicePerLevel3` float,
  `effectRealPointsPerLevel1` float,
  `effectRealPointsPerLevel2` float,
  `effectRealPointsPerLevel3` float,
  `effectBasePoints1` int(9),
  `effectBasePoints2` int(9),
  `effectBasePoints3` int(9),
  `effectMechanic1` int(9) unsigned,
  `effectMechanic2` int(9) unsigned,
  `effectMechanic3` int(9) unsigned,
  `effectImplicitTargetA1` int(9) unsigned,
  `effectImplicitTargetA2` int(9) unsigned,
  `effectImplicitTargetA3` int(9) unsigned,
  `effectImplicitTargetB1` int(9) unsigned,
  `effectImplicitTargetB2` int(9) unsigned,
  `effectImplicitTargetB3` int(9) unsigned,
  `effectRadiusIndex1` int(9) unsigned,
  `effectRadiusIndex2` int(9) unsigned,
  `effectRadiusIndex3` int(9) unsigned,
  `effectApplyAuraName1` int(9) unsigned,
  `effectApplyAuraName2` int(9) unsigned,
  `effectApplyAuraName3` int(9) unsigned,
  `effectAmplitude1` int(9) unsigned,
  `effectAmplitude2` int(9) unsigned,
  `effectAmplitude3` int(9) unsigned,
  `effectMultipleValue1` float,
  `effectMultipleValue2` float,
  `effectMultipleValue3` float,
  `effectChainTarget1` int(9) unsigned,
  `effectChainTarget2` int(9) unsigned,
  `effectChainTarget3` int(9) unsigned,
  `effectItemType1` int(9) unsigned,
  `effectItemType2` int(9) unsigned,
  `effectItemType3` int(9) unsigned,
  `effectMiscValue1` int(9),
  `effectMiscValue2` int(9),
  `effectMiscValue3` int(9),
  `effectMiscValueB1` int(9),
  `effectMiscValueB2` int(9),
  `effectMiscValueB3` int(9),
  `effectTriggerSpell1` int(9) unsigned,
  `effectTriggerSpell2` int(9) unsigned,
  `effectTriggerSpell3` int(9) unsigned,
  `effectPointsPerComboPoint1` float,
  `effectPointsPerComboPoint2` float,
  `effectPointsPerComboPoint3` float,
  `spellVisual` int(9) unsigned,
  `spellIconID` int(9) unsigned,
  `activeIconID` int(9) unsigned,
  `spellName1` varchar(100),
  `spellName2` varchar(100),
  `spellName3` varchar(100),
  `spellName4` varchar(100),
  `spellName5` varchar(100),
  `spellName6` varchar(100),
  `spellName7` varchar(100),
  `spellName8` varchar(100),
  `spellName9` varchar(100),
  `spellName10` varchar(100),
  `spellName11` varchar(100),
  `spellName12` varchar(100),
  `spellName13` varchar(100),
  `spellName14` varchar(100),
  `spellName15` varchar(100),
  `spellName16` varchar(100),
  `rank1` varchar(100),
  `rank2` varchar(100),
  `rank3` varchar(100),
  `rank4` varchar(100),
  `rank5` varchar(100),
  `rank6` varchar(100),
  `rank7` varchar(100),
  `rank8` varchar(100),
  `rank9` varchar(100),
  `rank10` varchar(100),
  `rank11` varchar(100),
  `rank12` varchar(100),
  `rank13` varchar(100),
  `rank14` varchar(100),
  `rank15` varchar(100),
  `rank16` varchar(100),
  `manaCostPercentage` int(9) unsigned,
  `startRecoveryCategory` int(9) unsigned,
  `startRecoveryTime` int(9) unsigned,
  `maxTargetLevel` int(9) unsigned,
  `spellFamilyName` int(9) unsigned,
  `spellFamilyFlags` bigint(20) unsigned,
  `maxAffectedTargets` int(9) unsigned,
  `dmgClass` int(9) unsigned,
  `preventionType` int(9) unsigned,
  `dmgMultiplier1` float,
  `dmgMultiplier2` float,
  `dmgMultiplier3` float,
  `totemCategory1` int(9) unsigned,
  `totemCategory2` int(9) unsigned,
  `areaId` int(9) unsigned,
  `schoolMask` int(9) unsigned,
  `customAttributesFlags` int(11) unsigned,
  `comment` TEXT,
  PRIMARY KEY (`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Use this table to override values from spell_template table';

-- Migrate column customAttributesFlags
INSERT INTO spell_template_override (entry, customAttributesFlags) VALUES (31513,131072), (34913,524288),(37450,131072);
ALTER TABLE spell_template DROP COLUMN IF EXISTS customAttributesFlags;

-- Migrate some entries from LoadSpellCustomAttr to this new table
INSERT INTO spell_template_override (entry, effectRadiusIndex1, comment) VALUES (6495,0,"Sentry totem. Remove radius, this spell has 100.0f and we don't want to to be summoned 100 yards away");
INSERT INTO spell_template_override (entry, effectImplicitTargetA1, comment) VALUES (37540,1,"Fireball Barrage : spellInfo->EffectImplicitTargetA[0] = TARGET_UNIT_CASTER;");
INSERT INTO spell_template_override (entry, effectImplicitTargetA1, comment) VALUES (37632,1,"Toxic Barrage : spellInfo->EffectImplicitTargetA[0] = TARGET_UNIT_CASTER;");
INSERT INTO spell_template_override (entry, maxAffectedTargets, comment) VALUES (40243,5,"Crushing Shadows : spellInfo->MaxAffectedTargets = 5;");
INSERT INTO spell_template_override (entry, maxAffectedTargets, comment) VALUES (46292,8,"Cataclysm Breath : spellInfo->MaxAffectedTargets = 8;");
INSERT INTO spell_template_override (entry, maxAffectedTargets, comment) VALUES (46480,8,"Fel Lightning : spellInfo->MaxAffectedTargets = 8;");
INSERT INTO spell_template_override (entry, dispel) VALUES (27066,0);
INSERT INTO spell_template_override (entry, spellFamilyFlags) VALUES (38393,429496729601);
INSERT INTO spell_template_override (entry, spellFamilyFlags) VALUES (37384,6);
INSERT INTO spell_template_override (entry, spellFamilyFlags) VALUES (38397,1574945);
INSERT INTO spell_template_override (entry, spellFamilyFlags) VALUES (38429,2416967680);
INSERT INTO spell_template_override (entry, spellFamilyFlags) VALUES (23575,1056);
INSERT INTO spell_template_override (entry, spellFamilyFlags) VALUES (33737,1056);
INSERT INTO spell_template_override (entry, effectImplicitTargetA1, comment) VALUES (20625, 20, "spellInfo->EffectImplicitTargetA[0] = TARGET_UNIT_CASTER_AREA_PARTY");
INSERT INTO spell_template_override (entry, effectImplicitTargetA1, comment) VALUES (35460, 2, "Fureur des anciens crapuches : spellInfo->EffectImplicitTargetA[1] = TARGET_TYPE_UNIT_TARGET;");
 