-- arcatraz boss states

-- Zereketh
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20870','0','8','0','25','0','100','0','0','0','0','0','34','1','0','1','0','0','0','0','0','0','0','0','0','0','0','0','Zereketh the Unbound - On Reset - Set Instance Boss State 1 0 ');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20870','0','9','0','4','0','100','0','0','0','0','0','34','1','1','1','0','0','0','0','0','0','0','0','0','0','0','0','Zereketh the Unbound - On Aggro - Set Instance Boss State 1 1 ');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20870','0','10','0','6','0','100','0','0','0','0','0','34','1','3','1','0','0','0','0','0','0','0','0','0','0','0','0','Zereketh the Unbound - On Death - Set Instance Boss State 1 3 ');

DELETE FROM smart_scripts WHERE entryorguid IN (20886, 20885);
UPDATE creature_template SET AIName = '', ScriptName = "boss_dalliah_the_doomsayer" WHERE entry = 20885;
UPDATE creature_template SET AIName = '', ScriptName = "boss_wrath_scryer_soccothrates" WHERE entry = 20886;
UPDATE creature SET pool_id = 0 WHERE id IN (20886, 20885);

-- arcatraz warder
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20859','0','0','0','0','0','100','0','5000','10000','10000','20000','11','35963','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Arcatraz Warder - In Combat - Cast \"<a href=\"http://wowhead.com/spell=35963\">Improved Wing Clip</a>\" ');
UPDATE creature_template SET AIName = "SmartAI" WHERE entry = 20859;


-- protean nightmare
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20864','0','0','0','0','0','100','2','2500','5000','15000','20000','11','36617','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Protean Nightmare - In Combat - Cast \"<a href=\"http://wowhead.com/spell=36617\">Gaping Maw</a>\" (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20864','0','1','0','0','0','100','4','2500','5000','15000','20000','11','38810','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Protean Nightmare - In Combat - Cast \"<a href=\"http://wowhead.com/spell=38810\">Gaping Maw</a>\" (Heroic Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20864','0','3','0','0','0','100','0','12000','15000','30000','40000','11','36622','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Protean Nightmare - In Combat - Cast \"<a href=\"http://wowhead.com/spell=36622\">Incubation</a>\" ');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20864','0','4','0','0','0','100','2','6000','10000','10000','15000','11','36619','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Protean Nightmare - In Combat - Cast \"<a href=\"http://wowhead.com/spell=36619\">Infectious Poison</a>\" (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20864','0','5','0','0','0','100','4','6000','10000','10000','15000','11','38811','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Protean Nightmare - In Combat - Cast \"<a href=\"http://wowhead.com/spell=38811\">Infectious Poison</a>\" (Heroic Dungeon)');
UPDATE creature_template SET AIName = "SmartAI" WHERE entry = 20864;

-- Negaton Screamer

replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','0','0','4','0','100','512','0','0','0','0','11','36733','2','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Agro - Cast Elemental Response');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','1','0','9','0','100','0','0','8','12000','20000','11','13704','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Range  - Cast Psychic Scream');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','2','0','0','2','100','512','15000','25000','15000','25000','22','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2) - Set Phase 1');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','3','0','4','0','100','512','0','0','0','0','22','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Agro - Set Phase 1');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','4','17','8','1','100','512','0','2','0','0','11','34336','2','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Holy) (Phase 1) - Cast Damage Reduction: Holy');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','5','18','8','1','100','512','0','4','0','0','11','34333','2','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Fire) (Phase 1) - Cast Damage Reduction: Fire');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','6','19','8','1','100','512','0','8','0','0','11','34335','2','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Nature)(Phase 1) - Cast Damage Reduction: Nature');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','7','20','8','1','100','512','0','16','0','0','11','34334','2','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Frost) (Phase 1) - Cast Damage Reduction: Frost');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','8','21','8','1','100','512','0','32','0','0','11','34338','2','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Shadow) (Phase 1)  - Cast Damage Reduction: Shadow');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','9','22','8','1','100','512','0','64','0','0','11','34331','2','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Arcane) (Phase 1)  - Cast Damage Reduction: Arcane');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','10','0','61','0','100','512','0','0','0','0','22','2','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - Link - Set Phase 2');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','11','0','0','2','100','2','0','0','3000','3500','11','36742','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Fireball Volley (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','12','0','0','2','100','2','0','0','3000','3500','11','36738','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Arcane Volley (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','13','0','0','2','100','2','0','0','3000','3500','11','36741','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Frostbolt Volley (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','14','0','0','2','100','2','0','0','3000','3500','11','36743','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Holy Bolt Volley (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','15','0','0','2','100','2','0','0','3000','3500','11','36740','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Lightning Bolt Volley (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','16','0','0','2','100','2','0','0','3000','3500','11','36736','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Shadow Bolt Volley (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','17','10','61','0','100','512','0','0','0','0','1','3','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Holy) (Phase 1) - Say');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','18','10','61','0','100','512','0','0','0','0','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Fire) (Phase 1) - Say');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','19','10','61','0','100','512','0','0','0','0','1','4','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Nature)(Phase 1) - Say');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','20','10','61','0','100','512','0','0','0','0','1','2','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Frost) (Phase 1) - Say');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','21','10','61','0','100','512','0','0','0','0','1','5','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Shadow) (Phase 1)  - Say');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','22','10','61','0','100','512','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Negaton Screamer - On Spellhit (Arcane) (Phase 1)  - Say');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','23','0','0','2','100','4','0','0','3000','3500','11','38836','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Fireball Volley (Heroic Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','24','0','0','2','100','4','0','0','3000','3500','11','38835','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Arcane Volley (Heroic Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','25','0','0','2','100','4','0','0','3000','3500','11','38837','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Frostbolt Volley (Heroic Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','26','0','0','2','100','4','0','0','3000','3500','11','38838','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Holy Bolt Volley (Heroic Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','27','0','0','2','100','4','0','0','3000','3500','11','38839','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Lightning Bolt Volley (Heroic Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20875','0','28','0','0','2','100','4','0','0','3000','3500','11','38840','64','0','0','0','0','2','0','0','0','0','0','0','0','Negaton Screamer - IC (Phase 2)  - Cast Shadow Bolt Volley (Heroic Dungeon)');

replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20875','0','0','%s absorbs the fire energy of the attack.','16','0','100','0','0','0','17105','0','Negaton Screamer');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20875','1','0','%s absorbs the arcane energy of the attack.','16','0','100','0','0','0','17109','0','Negaton Screamer');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20875','2','0','%s absorbs the frost energy of the attack.','16','0','100','0','0','0','17106','0','Negaton Screamer');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20875','3','0','%s absorbs the holy energy of the attack.','16','0','100','0','0','0','17110','0','Negaton Screamer');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20875','4','0','%s absorbs the nature energy of the attack.','16','0','100','0','0','0','17107','0','Negaton Screamer');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20875','5','0','%s absorbs the shadow energy of the attack.','16','0','100','0','0','0','17108','0','Negaton Screamer');
UPDATE creature_template SET AIName = "SmartAI" WHERE entry = 20875;

--Arcatraz Sentinel
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20869','0','0','0','2','0','100','1','0','10','0','0','11','36719','1','0','0','0','0','1','0','0','0','0','0','0','0','Arcatraz Sentinel - Between 0-2% Health - Cast Spell Explode');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20869','0','1','0','6','0','100','1','0','0','0','0','11','37394','1','0','0','0','0','1','0','0','0','0','0','0','0','Arcatraz Sentinel - Death - Cast Serverside - Summon Destroyed Sentinel');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20869','0','2','3','10','0','100','1','0','15','0','0','28','31261','0','0','0','0','0','1','0','0','0','0','0','0','0','Arcatraz Sentinel - ooc los - remove aura');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20869','0','3','0','61','0','100','0','0','0','0','0','49','0','0','0','0','0','0','21','50','0','0','0','0','0','0','Arcatraz Sentinel - ooc los - Start attack');
UPDATE creature_template SET AIName = "SmartAI" WHERE entry = 20869;

-- Spiteful Temptress
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20883','0','0','0','0','0','100','0','8000','11000','20000','22000','11','36866','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Spiteful Temptress - In Combat - Cast \"<a href=\"http://wowhead.com/spell=36866\">Domination</a>\" ');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20883','0','1','0','0','0','100','2','5000','6000','7000','8000','11','36868','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Spiteful Temptress - In Combat - Cast \"<a href=\"http://wowhead.com/spell=36868\">Shadow Bolt</a>\" (Normal Dungeon)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_flags`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20883','0','2','0','0','0','100','4','5000','6000','7000','8000','11','38892','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Spiteful Temptress - In Combat - Cast \"<a href=\"http://wowhead.com/spell=38892\">Shadow Bolt</a>\" (Heroic Dungeon)');
UPDATE creature_template SET AIName = "SmartAI" WHERE entry = 20883;


replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','0','0','Don\'t worry about me; kill that worthless dullard instead!','14','0','100','1','0','11085','19979','0','Dalliah the Doomsayer - Aggro Soccothrates First');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','1','0','It is unwise to anger me!','14','0','100','0','0','11086','19978','0','Dalliah the Doomsayer - Aggro');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','2','0','Completely ineffective.  Just like someone else I know.','14','0','100','0','0','11087','19980','0','Dalliah the Doomsayer - Kill');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','2','1','You chose the wrong opponent.','14','0','100','0','0','11088','19981','0','Dalliah the Doomsayer - Kill');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','3','0','Reap the whirlwind!','14','0','100','0','0','11089','19982','0','Dalliah the Doomsayer - Cast Whirlwind');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','3','1','I\'ll cut you to pieces!','14','0','100','0','0','11090','19983','0','Dalliah the Doomsayer - Cast Whirlwind');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','4','0','That is much better.','14','0','100','0','0','11091','19984','0','Dalliah the Doomsayer - Cast Heal');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','4','1','Ahh... just what I needed.','14','0','100','0','0','11092','19985','0','Dalliah the Doomsayer - Cast Heal');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','5','0','Now I\'m really angry.','14','0','100','0','0','11093','19986','0','Dalliah the Doomsayer - Death');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','6','0','More than you can handle, scryer?','14','0','100','1','0','11094','19987','0','Dalliah the Doomsayer - Soccothrates at 25%');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','6','1','I suppose I\'ll end up fighting them all myself.','14','0','100','1','0','11095','19988','0','Dalliah the Doomsayer - Soccothrates at 25%');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','6','2','I\'ve grown used to cleaning up your messes.','14','0','100','1','0','11096','19989','0','Dalliah the Doomsayer - Soccothrates at 25%');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','7','0','Congratulations.  I\'ve wanted to do that for years.','14','0','100','66','0','11097','19990','0','Dalliah the Doomsayer - Soccothratess dies');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','8','0','Why would I call on you?','14','0','100','396','0','0','20055','0','Dalliah the Doomsayer - Conversation with Soccothrates part 1');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','9','0','When I need someone to prance around like an overstuffed peacock, I\'ll call on you.','14','0','100','396','0','0','20056','0','Dalliah the Doomsayer - Conversation with Soccothrates part 2');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20885','10','0','What would you know about commitment, sheet-sah?','14','0','100','396','0','0','20057','0','Dalliah the Doomsayer - Conversation with Soccothrates part 3');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','0','0','Have you come to kill Dalliah?  Can I watch?','14','0','100','1','0','11237','19968','0','Wrath-Scryer Soccothrates - Aggro Dalliah First');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','1','0','At last, a target for my frustrations!','14','0','100','0','0','11238','19967','0','Wrath-Scryer Soccothrates - Aggro');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','2','0','Yes, that was quite satisfying.','14','0','100','0','0','11239','19969','0','Wrath-Scryer Soccothrates - Kill');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','3','0','On guard!','14','0','100','0','0','11241','19971','0','Wrath-Scryer Soccothrates - Knock Away');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','3','1','Defend yourself, for all the good it will do....','14','0','100','0','0','11242','19972','0','Wrath-Scryer Soccothrates - Knock Away');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','4','0','Knew this was... the only way out.','14','0','100','0','0','11243','19973','0','Wrath-Scryer Soccothrates - Death');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','5','0','Having problems, Dalliah?  How nice.','14','0','100','1','0','11244','19974','0','Wrath-Scryer Soccothrates - Dalliah at 25%');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','5','1','This may be the end for you, Dalliah.  What a shame that would be.','14','0','100','1','0','11245','19975','0','Wrath-Scryer Soccothrates - Dalliah at 25%');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','5','2','I suggest a new strategy: you draw their attacks while I gather reinforcements.','14','0','100','1','0','11246','19976','0','Wrath-Scryer Soccothrates - Dalliah at 25%');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','6','0','Finally!  Well done!','14','0','100','66','0','11247','19977','0','Wrath-Scryer Soccothrates - Dalliah dies');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','7','0','Did you call on me?','14','0','100','397','0','11236','20051','0','Wrath-Scryer Soccothrates - Conversation with Dalliah part 1');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','8','0','To do your heavy lifting, most likely.','14','0','100','396','0','0','20052','0','Wrath-Scryer Soccothrates - Conversation with Dalliah part 2');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','9','0','Then I\'ll commit myself to ignoring you.','14','0','100','396','0','0','20053','0','Wrath-Scryer Soccothrates - Conversation with Dalliah part 3');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('20886','10','0','You\'re the one who should be-- Wait, we have company...','14','0','100','396','0','0','20054','0','Wrath-Scryer Soccothrates - Conversation with Dalliah part 4');

replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19979','0','','Don\'t worry about me; kill that worthless dullard instead!','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19978','0','','It is unwise to anger me!','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19980','0','','Completely ineffective.  Just like someone else I know.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19981','0','','You chose the wrong opponent.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19982','0','','Reap the whirlwind!','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19983','0','','I\'ll cut you to pieces!','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19984','0','','That is much better.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19985','0','','Ahh... just what I needed.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19986','0','','Now I\'m really angry.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19987','0','','More than you can handle, scryer?','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19988','0','','I suppose I\'ll end up fighting them all myself.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19989','0','','I\'ve grown used to cleaning up your messes.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19990','0','','Congratulations.  I\'ve wanted to do that for years.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('20055','0','','Why would I call on you?','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('20056','0','','When I need someone to prance around like an overstuffed peacock, I\'ll call on you.','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('20057','0','','What would you know about commitment, sheet-sah?','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19968','0','Have you come to kill Dalliah?  Can I watch?','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19967','0','At last, a target for my frustrations!','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19969','0','Yes, that was quite satisfying.','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19971','0','On guard!','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19972','0','Defend yourself, for all the good it will do....','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19973','0','Knew this was... the only way out.','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19974','0','Having problems, Dalliah?  How nice.','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19975','0','This may be the end for you, Dalliah.  What a shame that would be.','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19976','0','I suggest a new strategy: you draw their attacks while I gather reinforcements.','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('19977','0','Finally!  Well done!','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('20051','0','Did you call on me?','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('20052','0','To do your heavy lifting, most likely.','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('20053','0','Then I\'ll commit myself to ignoring you.','','0','0','0','0','0','0','0','0','1','18019');
replace into `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) values('20054','0','You\'re the one who should be-- Wait, we have company...','','0','0','0','0','0','0','0','0','1','18019');


replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20898','0','0','0','0','0','100','2','3000','10000','20000','20000','11','36837','0','0','0','0','0','5','20','0','0','0','0','0','0','Gargantuan Abyssal - In Combat - Cast Spell Meteor');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20898','0','1','0','0','0','100','4','3000','10000','20000','20000','11','38903','0','0','0','0','0','5','20','0','0','0','0','0','0','Gargantuan Abyssal - In Combat - Cast Spell Meteor');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20898','0','2','0','0','0','100','3','2000','5000','0','0','11','38855','0','0','0','0','0','1','0','0','0','0','0','0','0','Gargantuan Abyssal - In Combat - Cast Spell Fire Shield');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20898','0','3','0','0','0','100','5','2000','5000','0','0','11','38901','0','0','0','0','0','1','0','0','0','0','0','0','0','Gargantuan Abyssal - In Combat - Cast Spell Fire Shield');
UPDATE creature_template SET AIName = "SmartAI" WHERE entry = 20898;


replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','0','0','25','0','100','0','0','0','0','0','31','1','2','0','0','0','0','1','0','0','0','0','0','0','0','Sargeron Archer - On Reset - Set Random Event Phase Range');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','1','0','9','0','100','2','5','30','3000','3000','11','21610','64','0','0','0','0','2','0','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Shoot');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','2','0','9','0','100','4','5','30','3000','3000','11','38940','64','0','0','0','0','2','0','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Shoot');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','3','0','0','1','100','2','4000','4000','9000','9000','11','35964','0','0','0','0','0','2','0','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Frost Arrow');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','4','0','0','1','100','4','4000','4000','9000','9000','11','38942','0','0','0','0','0','2','0','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Frost Arrow');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','5','0','0','2','100','2','4000','4000','9000','9000','11','35932','0','0','0','0','0','2','0','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Immolation Arrow');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','6','0','0','2','100','4','4000','4000','9000','9000','11','38943','0','0','0','0','0','2','0','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Immolation Arrow');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','7','0','0','0','100','0','15000','15000','30000','30000','11','36828','0','0','0','0','0','1','0','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Rapid Fire');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','8','0','0','0','100','2','20000','20000','30000','30000','11','36984','0','0','0','0','0','5','40','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Serpent Sting');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','9','0','0','0','100','4','20000','20000','30000','30000','11','38914','0','0','0','0','0','5','40','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Serpent Sting');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','10','0','0','0','100','2','10000','10000','30000','30000','11','36827','0','0','0','0','0','5','30','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Hooked Net');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20901','0','11','0','0','0','100','4','10000','10000','30000','30000','11','38912','0','0','0','0','0','5','30','0','0','0','0','0','0','Sargeron Archer - In Combat - Cast Spell Hooked Net');
UPDATE creature_template SET AIName = "SmartAI" WHERE entry = 20901;
