void AddSC_alterac_mountains();
void AddSC_AV_Warmasters();
void AddSC_alterac_bowman();
void AddSC_boss_balinda();
void AddSC_boss_drekthar();
void AddSC_boss_galvangar();
void AddSC_boss_vanndar();
void AddSC_arathi_highlands();
void AddSC_blackrock_depths();
void AddSC_boss_ambassador_flamelash();
void AddSC_boss_anubshiah();
void AddSC_boss_draganthaurissan();
void AddSC_boss_general_angerforge();
void AddSC_boss_gorosh_the_dervish();
void AddSC_boss_grizzle();
void AddSC_boss_high_interrogator_gerstahn();
void AddSC_boss_magmus();
void AddSC_boss_moira_bronzebeard();
void AddSC_boss_tomb_of_seven();
void AddSC_instance_blackrock_depths();
void AddSC_boss_drakkisath();
void AddSC_boss_gyth();
void AddSC_boss_halycon();
void AddSC_boss_highlordomokk();
void AddSC_boss_mothersmolderweb();
void AddSC_boss_overlordwyrmthalak();
void AddSC_boss_pyroguard_emberseer();
void AddSC_boss_quatermasterzigris();
void AddSC_boss_rend_blackhand();
void AddSC_boss_shadowvosh();
void AddSC_boss_thebeast();
void AddSC_boss_warmastervoone();
void AddSC_instance_blackrock_spire();
void AddSC_boss_broodlord();
void AddSC_boss_chromaggus();
void AddSC_boss_ebonroc();
void AddSC_boss_firemaw();
void AddSC_boss_flamegor();
void AddSC_boss_nefarian();
void AddSC_boss_razorgore();
void AddSC_boss_vael();
void AddSC_boss_victor_nefarius();
void AddSC_blasted_lands();
void AddSC_burning_steppes();
void AddSC_instance_deadmines();
void AddSC_dun_morogh();
void AddSC_eastern_plaguelands();
void AddSC_elwynn_forest();
void AddSC_hinterlands();
void AddSC_ironforge();
void AddSC_boss_curator();
void AddSC_boss_maiden_of_virtue();
void AddSC_boss_attumen();
void AddSC_boss_moroes();
void AddSC_boss_netherspite();
void AddSC_boss_nightbane();
void AddSC_boss_malchezaar();
void AddSC_boss_shade_of_aran();
void AddSC_boss_terestian_illhoof();
void AddSC_bosses_opera();
void AddSC_chess_event();
void AddSC_instance_karazhan();
void AddSC_karazhan();
void AddSC_loch_modan();
void AddSC_boss_baron_geddon();
void AddSC_boss_garr();
void AddSC_boss_gehennas();
void AddSC_boss_golemagg();
void AddSC_boss_lucifron();
void AddSC_boss_magmadar();
void AddSC_boss_majordomo();
void AddSC_boss_ragnaros();
void AddSC_boss_shazzrah();
void AddSC_boss_sulfuron();
void AddSC_instance_molten_core();
void AddSC_molten_core();
void AddSC_boss_anubrekhan();
void AddSC_boss_faerlina();
void AddSC_boss_four_horsemen();
void AddSC_boss_gluth();
void AddSC_boss_highlord_mograine();
void AddSC_boss_kelthuzad();
void AddSC_boss_loatheb();
void AddSC_boss_maexxna();
void AddSC_boss_noth();
void AddSC_boss_patchwerk();
void AddSC_boss_razuvious();
void AddSC_boss_sapphiron();
void AddSC_redridge_mountains();
void AddSC_boss_arcanist_doan();
void AddSC_boss_azshir_the_sleepless();
void AddSC_boss_bloodmage_thalnos();
void AddSC_boss_headless_horseman();
void AddSC_boss_herod();
void AddSC_boss_high_inquisitor_fairbanks();
void AddSC_boss_houndmaster_loksey();
void AddSC_boss_interrogator_vishas();
void AddSC_boss_mograine_and_whitemane();
void AddSC_boss_scorn();
void AddSC_instance_scarlet_monastery();
void AddSC_boss_darkmaster_gandling();
void AddSC_boss_death_knight_darkreaver();
void AddSC_boss_theolenkrastinov();
void AddSC_boss_illuciabarov();
void AddSC_boss_instructormalicia();
void AddSC_boss_jandicebarov();
void AddSC_boss_kormok();
void AddSC_boss_lordalexeibarov();
void AddSC_boss_lorekeeperpolkelt();
void AddSC_boss_rasfrost();
void AddSC_boss_theravenian();
void AddSC_boss_vectus();
void AddSC_instance_scholomance();
void AddSC_scholomance();
void AddSC_searing_gorge();
void AddSC_instance_shadowfang_keep();
void AddSC_shadowfang_keep();
void AddSC_silverpine_forest();
void AddSC_stormwind_city();
void AddSC_stranglethorn_vale();
void AddSC_boss_baron_rivendare();
void AddSC_boss_baroness_anastari();
void AddSC_boss_cannon_master_willey();
void AddSC_boss_dathrohan_balnazzar();
void AddSC_boss_magistrate_barthilas();
void AddSC_boss_maleki_the_pallid();
void AddSC_boss_nerubenkan();
void AddSC_boss_order_of_silver_hand();
void AddSC_boss_postmaster_malown();
void AddSC_boss_ramstein_the_gorger();
void AddSC_boss_timmy_the_cruel();
void AddSC_instance_stratholme();
void AddSC_stratholme();
void AddSC_instance_sunken_temple();
void AddSC_sunken_temple();
void AddSC_swamp_of_sorrows();
void AddSC_the_balance_of_light_and_shadow();
void AddSC_tirisfal_glades();
void AddSC_boss_archaedas();
void AddSC_boss_ironaya();
void AddSC_instance_uldaman();
void AddSC_uldaman();
void AddSC_undercity();
void AddSC_western_plaguelands();
void AddSC_westfall();
void AddSC_wetlands();
void AddSC_boss_arlokk();
void AddSC_boss_gahzranka();
void AddSC_boss_grilek();
void AddSC_boss_hakkar();
void AddSC_boss_hazzarah();
void AddSC_boss_jeklik();
void AddSC_boss_jindo();
void AddSC_boss_mandokir();
void AddSC_boss_marli();
void AddSC_boss_renataki();
void AddSC_boss_thekal();
void AddSC_boss_venoxis();
void AddSC_boss_wushoolay();
void AddSC_instance_zulgurub();

void AddEasternKingdomsScripts()
{
    AddSC_alterac_mountains();
    AddSC_AV_Warmasters();
    AddSC_alterac_bowman();
    AddSC_boss_balinda();
    AddSC_boss_drekthar();
    AddSC_boss_galvangar();
    AddSC_boss_vanndar();
    AddSC_arathi_highlands();
    AddSC_blackrock_depths();
    AddSC_boss_ambassador_flamelash();
    AddSC_boss_anubshiah();
    AddSC_boss_draganthaurissan();
    AddSC_boss_general_angerforge();
    AddSC_boss_gorosh_the_dervish();
    AddSC_boss_grizzle();
    AddSC_boss_high_interrogator_gerstahn();
    AddSC_boss_magmus();
    AddSC_boss_moira_bronzebeard();
    AddSC_boss_tomb_of_seven();
    AddSC_instance_blackrock_depths();
    AddSC_boss_drakkisath();
    AddSC_boss_gyth();
    AddSC_boss_halycon();
    AddSC_boss_highlordomokk();
    AddSC_boss_mothersmolderweb();
    AddSC_boss_overlordwyrmthalak();
    AddSC_boss_pyroguard_emberseer();
    AddSC_boss_quatermasterzigris();
    AddSC_boss_rend_blackhand();
    AddSC_boss_shadowvosh();
    AddSC_boss_thebeast();
    AddSC_boss_warmastervoone();
    AddSC_instance_blackrock_spire();
    AddSC_boss_broodlord();
    AddSC_boss_chromaggus();
    AddSC_boss_ebonroc();
    AddSC_boss_firemaw();
    AddSC_boss_flamegor();
    AddSC_boss_nefarian();
    AddSC_boss_razorgore();
    AddSC_boss_vael();
    AddSC_boss_victor_nefarius();
    AddSC_blasted_lands();
    AddSC_burning_steppes();
    AddSC_instance_deadmines();
    AddSC_dun_morogh();
    AddSC_eastern_plaguelands();
    AddSC_elwynn_forest();
    AddSC_hinterlands();
    AddSC_ironforge();
    AddSC_boss_curator();
    AddSC_boss_maiden_of_virtue();
    AddSC_boss_attumen();
    AddSC_boss_moroes();
    AddSC_boss_netherspite();
    AddSC_boss_nightbane();
    AddSC_boss_malchezaar();
    AddSC_boss_shade_of_aran();
    AddSC_boss_terestian_illhoof();
    AddSC_bosses_opera();
    AddSC_chess_event();
    AddSC_instance_karazhan();
    AddSC_karazhan();
    AddSC_loch_modan();
    AddSC_boss_baron_geddon();
    AddSC_boss_garr();
    AddSC_boss_gehennas();
    AddSC_boss_golemagg();
    AddSC_boss_lucifron();
    AddSC_boss_magmadar();
    AddSC_boss_majordomo();
    AddSC_boss_ragnaros();
    AddSC_boss_shazzrah();
    AddSC_boss_sulfuron();
    AddSC_instance_molten_core();
    AddSC_molten_core();
    AddSC_boss_anubrekhan();
    AddSC_boss_faerlina();
    AddSC_boss_four_horsemen();
    AddSC_boss_gluth();
    AddSC_boss_highlord_mograine();
    AddSC_boss_kelthuzad();
    AddSC_boss_loatheb();
    AddSC_boss_maexxna();
    AddSC_boss_noth();
    AddSC_boss_patchwerk();
    AddSC_boss_razuvious();
    AddSC_boss_sapphiron();
    AddSC_redridge_mountains();
    AddSC_boss_arcanist_doan();
    AddSC_boss_azshir_the_sleepless();
    AddSC_boss_bloodmage_thalnos();
    AddSC_boss_headless_horseman();
    AddSC_boss_herod();
    AddSC_boss_high_inquisitor_fairbanks();
    AddSC_boss_houndmaster_loksey();
    AddSC_boss_interrogator_vishas();
    AddSC_boss_mograine_and_whitemane();
    AddSC_boss_scorn();
    AddSC_instance_scarlet_monastery();
    AddSC_boss_darkmaster_gandling();
    AddSC_boss_death_knight_darkreaver();
    AddSC_boss_theolenkrastinov();
    AddSC_boss_illuciabarov();
    AddSC_boss_instructormalicia();
    AddSC_boss_jandicebarov();
    AddSC_boss_kormok();
    AddSC_boss_lordalexeibarov();
    AddSC_boss_lorekeeperpolkelt();
    AddSC_boss_rasfrost();
    AddSC_boss_theravenian();
    AddSC_boss_vectus();
    AddSC_instance_scholomance();
    AddSC_scholomance();
    AddSC_searing_gorge();
    AddSC_instance_shadowfang_keep();
    AddSC_shadowfang_keep();
    AddSC_silverpine_forest();
    AddSC_stormwind_city();
    AddSC_stranglethorn_vale();
    AddSC_boss_baron_rivendare();
    AddSC_boss_baroness_anastari();
    AddSC_boss_cannon_master_willey();
    AddSC_boss_dathrohan_balnazzar();
    AddSC_boss_magistrate_barthilas();
    AddSC_boss_maleki_the_pallid();
    AddSC_boss_nerubenkan();
    AddSC_boss_order_of_silver_hand();
    AddSC_boss_postmaster_malown();
    AddSC_boss_ramstein_the_gorger();
    AddSC_boss_timmy_the_cruel();
    AddSC_instance_stratholme();
    AddSC_stratholme();
    AddSC_instance_sunken_temple();
    AddSC_sunken_temple();
    AddSC_swamp_of_sorrows();
    AddSC_the_balance_of_light_and_shadow();
    AddSC_tirisfal_glades();
    AddSC_boss_archaedas();
    AddSC_boss_ironaya();
    AddSC_instance_uldaman();
    AddSC_uldaman();
    AddSC_undercity();
    AddSC_western_plaguelands();
    AddSC_westfall();
    AddSC_wetlands();
    AddSC_boss_arlokk();
    AddSC_boss_gahzranka();
    AddSC_boss_grilek();
    AddSC_boss_hakkar();
    AddSC_boss_hazzarah();
    AddSC_boss_jeklik();
    AddSC_boss_jindo();
    AddSC_boss_mandokir();
    AddSC_boss_marli();
    AddSC_boss_renataki();
    AddSC_boss_thekal();
    AddSC_boss_venoxis();
    AddSC_boss_wushoolay();
    AddSC_instance_zulgurub();
}
