void AddSC_ashenvale();
void AddSC_azshara();
void AddSC_blackfathom_deeps();
void AddSC_boss_aku_mai();
void AddSC_boss_gelihast();
void AddSC_boss_kelris();
void AddSC_instance_blackfathom_deeps();
void AddSC_boss_aeonus();
void AddSC_boss_chrono_lord_deja();
void AddSC_boss_temporus();
void AddSC_dark_portal();
void AddSC_instance_dark_portal();
void AddSC_boss_anetheron();
void AddSC_boss_archimonde();
void AddSC_boss_azgalor();
void AddSC_boss_kazrogal();
void AddSC_boss_rage_winterchill();
void AddSC_hyjal();
void AddSC_hyjal_trash();
void AddSC_instance_mount_hyjal();
void AddSC_boss_captain_skarloc();
void AddSC_boss_epoch_hunter();
void AddSC_boss_lieutenant_drake();
void AddSC_instance_old_hillsbrad();
void AddSC_old_hillsbrad();
void AddSC_darkshore();
void AddSC_desolace();
void AddSC_boss_pusillin();
void AddSC_dire_maul();
void AddSC_instance_dire_maul();
void AddSC_durotar();
void AddSC_dustwallow_marsh();
void AddSC_felwood();
void AddSC_feralas();
void AddSC_boss_celebras_the_cursed();
void AddSC_boss_landslide();
void AddSC_boss_noxxion();
void AddSC_boss_ptheradras();
void AddSC_moonglade();
void AddSC_mulgore();
void AddSC_boss_onyxia();
void AddSC_orgrimmar();
void AddSC_boss_amnennar_the_coldbringer();
void AddSC_boss_glutton();
void AddSC_boss_mordresh_fire_eye();
void AddSC_boss_plaguemaw_the_rotting();
void AddSC_boss_ragglesnout();
void AddSC_boss_tuten_kash();
void AddSC_instance_razorfen_downs();
void AddSC_razorfen_downs();
void AddSC_instance_razorfen_kraul();
void AddSC_razorfen_kraul();
void AddSC_boss_ayamiss();
void AddSC_boss_buru();
void AddSC_boss_kurinnaxx();
void AddSC_boss_moam();
void AddSC_boss_ossirian();
void AddSC_boss_rajaxx();
void AddSC_instance_ruins_of_ahnqiraj();
void AddSC_silithus();
void AddSC_stonetalon_mountains();
void AddSC_tanaris();
void AddSC_teldrassil();
void AddSC_bug_trio();
void AddSC_boss_cthun();
void AddSC_boss_fankriss();
void AddSC_boss_huhuran();
void AddSC_boss_ouro();
void AddSC_boss_sartura();
void AddSC_boss_skeram();
void AddSC_boss_twinemperors();
void AddSC_instance_temple_of_ahnqiraj();
void AddSC_mob_anubisath_sentinel();
void AddSC_the_barrens();
void AddSC_thousand_needles();
void AddSC_thunder_bluff();
void AddSC_ungoro_crater();
void AddSC_instance_wailing_caverns();
void AddSC_wailing_caverns();
void AddSC_winterspring();
void AddSC_instance_zulfarrak();
void AddSC_zulfarrak();

void AddKalimdorScripts()
{
    AddSC_ashenvale();
    AddSC_azshara();
    AddSC_blackfathom_deeps();
    AddSC_boss_aku_mai();
    AddSC_boss_gelihast();
    AddSC_boss_kelris();
    AddSC_instance_blackfathom_deeps();
    AddSC_boss_aeonus();
    AddSC_boss_chrono_lord_deja();
    AddSC_boss_temporus();
    AddSC_dark_portal();
    AddSC_instance_dark_portal();
    AddSC_boss_anetheron();
    AddSC_boss_archimonde();
    AddSC_boss_azgalor();
    AddSC_boss_kazrogal();
    AddSC_boss_rage_winterchill();
    AddSC_hyjal();
    AddSC_hyjal_trash();
    AddSC_instance_mount_hyjal();
    AddSC_boss_captain_skarloc();
    AddSC_boss_epoch_hunter();
    AddSC_boss_lieutenant_drake();
    AddSC_instance_old_hillsbrad();
    AddSC_old_hillsbrad();
    AddSC_darkshore();
    AddSC_desolace();
    AddSC_boss_pusillin();
    AddSC_dire_maul();
    AddSC_instance_dire_maul();
    AddSC_durotar();
    AddSC_dustwallow_marsh();
    AddSC_felwood();
    AddSC_feralas();
    AddSC_boss_celebras_the_cursed();
    AddSC_boss_landslide();
    AddSC_boss_noxxion();
    AddSC_boss_ptheradras();
    AddSC_moonglade();
    AddSC_mulgore();
    AddSC_boss_onyxia();
    AddSC_orgrimmar();
    AddSC_boss_amnennar_the_coldbringer();
    AddSC_boss_glutton();
    AddSC_boss_mordresh_fire_eye();
    AddSC_boss_plaguemaw_the_rotting();
    AddSC_boss_ragglesnout();
    AddSC_boss_tuten_kash();
    AddSC_instance_razorfen_downs();
    AddSC_razorfen_downs();
    AddSC_instance_razorfen_kraul();
    AddSC_razorfen_kraul();
    AddSC_boss_ayamiss();
    AddSC_boss_buru();
    AddSC_boss_kurinnaxx();
    AddSC_boss_moam();
    AddSC_boss_ossirian();
    AddSC_boss_rajaxx();
    AddSC_instance_ruins_of_ahnqiraj();
    AddSC_silithus();
    AddSC_stonetalon_mountains();
    AddSC_tanaris();
    AddSC_teldrassil();
    AddSC_bug_trio();
    AddSC_boss_cthun();
    AddSC_boss_fankriss();
    AddSC_boss_huhuran();
    AddSC_boss_ouro();
    AddSC_boss_sartura();
    AddSC_boss_skeram();
    AddSC_boss_twinemperors();
    AddSC_instance_temple_of_ahnqiraj();
    AddSC_mob_anubisath_sentinel();
    AddSC_the_barrens();
    AddSC_thousand_needles();
    AddSC_thunder_bluff();
    AddSC_ungoro_crater();
    AddSC_instance_wailing_caverns();
    AddSC_wailing_caverns();
    AddSC_winterspring();
    AddSC_instance_zulfarrak();
    AddSC_zulfarrak();
}
