DELETE FROM script_texts WHERE entry BETWEEN -1000744 AND -1000729;
INSERT INTO script_texts (entry, content_default, content_loc2, sound, `type`, `language`, comment) VALUES
(-1000729, "Akama, my friend! Have you been informed? I was found out by Vashj's followers. Our secret is in peril!", "Akama... Vous êtes au courant ? J'ai été démasqué par les serviteurs de Vashj. Notre secret est en péril !", 11611, 0, 0, "The Secret Compromised - SAY_OLUM_1"),
(-1000730, "Olum... old friend. It is good to see that you are safe.", "Olum, mon vieil ami. Je suis heureux de vous voir sain et sauf.", 11600, 0, 0, "The Secret Compromised - SAY_AKAMA_1"),
(-1000731, "Illidan is looking for me. I am not safe here... none of us are.", "Illidan me recherche. Je ne suis pas en sûreté ici... Et vous non plus.", 11612, 0, 0, "The Secret Compromised - SAY_OLUM_2"),
(-1000732, "Illidan will become suspicious... that much is for certain. We will deal with it as we always do.", "Illidan va se douter de quelque chose, c'est une certitude. Nous nous en chargerons, comme d'habitude.", 11601, 0, 0, "The Secret Compromised - SAY_AKAMA_2"),
(-1000733, "Illidan will find me and when he does... he will pry the Ashtongue secret from me - such is the power of the Betrayer! No... there is only one way. My usefulness to the cause has come to an end. I must venture into the spirit world!", "Illidan me retrouvera. Et alors... Il m'arrachera le secret des Cendrelangues. Tel est le pouvoir du Traître ! Non... Il ne reste qu'une issue. J'ai cessé d'être utile à la cause. Je dois partir pour le monde des esprits.", 11613, 0, 0, "The Secret Compromised - SAY_OLUM_3"),
(-1000734, "You cannot... be serious, Olum. Your sacrifice has already been too great.", "Vous n'êtes pas... sérieux, Olum. Vous avez déjà fait un bien trop grand sacrifice.", 11602, 0, 0, "The Secret Compromised - SAY_AKAMA_3"),
(-1000735, "My decision is final. I will not be dissuaded. I have devoted my life to our plan. To jeopardize it now would betray all who have died for the cause long before me.", "Ma décision est irrévocable. Je n'en démordrai pas. J'ai voué ma vie à notre plan. Le mettre en péril aujourd'hui reviendrait à trahir tous ceux qui sont morts pour la cause bien avant moi.", 11614, 0, 0, "The Secret Compromised - SAY_OLUM_4"),
(-1000736, "It appears your mind is set then. We will guide you to the spirit world with as much kindness as we can.", "Vous semblez avoir pris votre décision. Nous vous guiderons vers le monde des esprits avec tous les égards possibles.", 11603, 0, 0, "The Secret Compromised - SAY_AKAMA_4"),
(-1000737, "I thank you, Akama. You honor me by allowing me this moment, surrounded by my brothers. Farewell, friend. Guide our people well.", "Je vous remercie, Akama. Vous me faites honneur en m'offrant ce moment, entouré par mes frères. Adieu, mon ami. Et guidez bien notre peuple.", 11615, 0, 0, "The Secret Compromised - SAY_OLUM_5"),
(-1000738, "Farewell, dear friend. We shall meet you in the next world when our duties in this one are fulfilled.", "Adieu, mon cher ami. Nous vous retrouverons dans un autre monde quand nos devoirs envers celui-ci seront remplis.", 11604, 0, 0, "The Secret Compromised - SAY_AKAMA_5"),
(-1000739, "Master! We've found the traitor who escaped Vashj! His body lies in front of me... lifeless!", "Maître ! Nous avons trouvé le traitre qui a échappé à Vashj. Son corps est étendu devant moi, sans vie !", 11605, 0, 0, "The Secret Compromised - SAY_AKAMA_6"),
(-1000740, "You disappoint me, Akama. I wanted to question the traitorous worm myself! I'm beginning to question your allegiance, Broken.", "Tu me déçois, Akama. Je voulais interroger moi-même cette vermine de traître. Je commence à avoir des doutes sur ton allégeance, Roué.", 11608, 0, 0, "The Secret Compromised - SAY_ILLIDAN_1"),
(-1000741, "But, sire! You have misjudged my actions... I do have knowledge of someone close to you who plans to betray you. It is that dog, Kael'thas! He has allied with Kil'jaeden and intends to replace you as Lord of Outland!", "Mais Sire ! Vous vous méprenez sur mes actes... J'ai appris que l'un de vos proches projette de vous trahir. C'est ce chien de Kael'thas ! Il s'est allié avec Kil'jaeden et cherche à devenir seigneur de l'Outreterre à votre place !", 11606, 0, 0, "The Secret Compromised - SAY_AKAMA_7"),
(-1000742, "I do not sense lies in your voice, Akama. That Kael'thas would betray me does not come as a big surprise - I'm not as oblivious as some would think. That one of your own was involved with him puts your loyalties into question.", "Je ne perçois aucun mensonge dans ta voix, Akama. Que Kael'thas cherche à me trahir n'est pas une grand surprise - je ne suis pas aussi inconscient que certains aimeraient le penser. Mais que l'un des tiens se soit associé à lui remet ta loyauté en question.", 11609, 0, 0, "The Secret Compromised - SAY_ILLIDAN_2"),
(-1000743, "Send your Ashtongue into Tempest Keep and slay his most prized possession, the phoenix known as Al'ar. I must know that you're not on his side. Do not think of betraying me, Broken. We both know who owns your soul!", "Envoie ton Cendrelangue au Donjon de la Tempête et tue son bien le plus cher, le phénix appelé Al'ar. Je dois m'assurer que tu n'es pas dans son camp. Ne songe pas à me trahir, Roué. Nous savons tous deux qui possède ton âme !", 11610, 0, 0, "The Secret Compromised - SAY_ILLIDAN_3"),
(-1000744, "It will be done, my lord!", "Ce sera fait, seigneur !", 11607, 0, 0, "The Secret Compromised - SAY_AKAMA_8");

UPDATE creature_template SET ScriptName = "npc_akama_prelude" WHERE entry = 21700;
UPDATE creature_template SET modelid_A = 21101, modelid_H = 21101 WHERE entry = 22820;

DELETE FROM spell_script_target WHERE entry = 39552;
INSERT INTO spell_script_target VALUES (39552, 1, 22820);
