UPDATE locales_quest SET RequestItemsText_loc2 = "Avez-vous terminé votre tâche, $C" WHERE entry = 8325;
UPDATE locales_quest SET RequestItemsText_loc2 = "Avez-vous lu la plaque au Sanctuaire maintenant, $C ?" WHERE entry = 8345;
UPDATE locales_quest SET RequestItemsText_loc2 = "C'est mieux que vous appreniez les méthodes de survie (et ce qu'il en coûte) maintenant que plus tard. Faire des choix difficiles est une chose à laquelle vous allez devoir vous habituer en tant qu'elfe de sang.$B$BPersonne n'a été là pour nous lorsque les Mort-Vivants ont déchiré notre foyer en deux. Nous nous sommes tirés seuls de ce mauvais pas." WHERE entry = 8334;
UPDATE locales_quest SET RequestItemsText_loc2 = "Ah, $N. Avez-vous terminé votre tâche ?" WHERE entry = 8346;
UPDATE locales_quest SET OfferRewardText_loc2 = "Bien le bonjour, $C ! J'ai entendu dire qu'$Gun:une; jeune $R $Gplein:pleine; de ressource et précédemment au service de la Magistrice Erona était en chemin pour aider les Estafettes. Nous apprécions toute aide, spécialement venant de quelqu'un qui a prouvé ses compétences.$B$BJ'espère que cela vous intéresse de réaliser l'une ou l'autre course pour nous." WHERE entry = 8347;
UPDATE locales_quest SET RequestItemsText_loc2 = "Salutations ! C'est un plaisir de vous rencontrer.$B$BJe vois que vous avez un bon spécial. Donnez-le moi et je vais vous offrir quelque chose en échange." WHERE entry = 8547;
UPDATE locales_quest SET OfferRewardText_loc2 = "Vous êtes en effet un héros spécial, $N. Nous vous souhaitons la bienvenue dans le monde d'Azeroth, et vous offrons l'un de ces cadeaux uniques !" WHERE entry = 8547;
UPDATE locales_quest SET OfferRewardText_loc2 = "Par le Puits de Soleil ! C'est la troisième estafette que nous avons perdue ce mois-ci.$B$BJ'apprécie le courage dont vous avez fait preuve en vous aventurant dans l'Allée du Point-du-Jour. Les gardes se doivent de garder un oeil sur ces déshérités.", RequestItemsText_loc2 = "Qu'avez-vous trouvé, $N ?" WHERE entry = 9705;
UPDATE locales_quest SET OfferRewardText_loc2 = "Ah, bien, $Gun:une; $C. Je vous ai $Gattendu:attendue;.$B$BJ'ai quelques tâches pour lesquelles vous allez parfaitement convenir." WHERE entry BETWEEN 10068 AND 10073;
