REPLACE INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
(2000000001, 'Get in the Ring of Blood, $N. The fight is about to start!', NULL, 'Entrez dans l''Arène de Sang, $N. Le combat est sur le point de commencer !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000002, 'The battle is about to begin!', NULL, 'La bataille va débuter !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000003, '$N versus the ferocious clefthoof, Brokentoe!', NULL, '$N contre le féroce Sabot-fourchu Brisorteil !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000004, 'Let''s go.', NULL, 'Allez-y.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000005, 'It is not here! hmmm....', NULL, 'Ce n''est pas ici ! Mmmh...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000006, 'It is Hollee''s tent, but where Hollee?', NULL, 'C''est la tente d''Holee, mais où est-elle ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000007, 'It is not here too. Strange... Where it is?', NULL, 'Ce n''est pas ici non plus. Etrange... Où est-ce que ça peut bien être ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000008, 'Hmm. It is not here. Maybe Hollee has it...', NULL, 'Hmm. Ce n''est pas ici. C''est peut-être Holee qui l''a en sa possession.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000009, 'What happens?', NULL, 'Qu''est-ce qu''il se passe ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000010, 'Volcor need help ?', NULL, 'Volcor a besoin d''aide ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000011, 'All right, I shall find people to help him.', NULL, 'Très bien, je vais essayer de trouver des gens qui pourront l''aider.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000012, 'All right, let''s go.', NULL, 'Très bien, allons-y.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000013, 'Oh no! They a here!', NULL, 'Oh non ! Ils sont là !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000014, 'Oh, hello Grimclaw.', NULL, 'Oh, bonjour Griffe-sinistre.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000015, 'Ok, $N. Now i can go the the Auberdine alone. Go to Terenthis. He waits for you. Thanks for the help.', NULL, 'OK, $N. Maintenant je peux finir le trajet jusqu''Auberdine tout seul. Aller voir Terenthis, il vous attend. Merci pour votre aide précieuse.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000016, 'Ok, good luck friend. Thanks for the help.', NULL, 'OK, bonne chance mon ami. Merci pour votre aide.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000017, 'Ok, let''s go!', NULL, 'OK, allons-y !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000018, 'I can make it the rest of the way. $N. THANKS!', NULL, 'Je peux finir le trajet tout seul. $N, MERCI !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000019, 'Be patient $N. The torch is almost complete.', NULL, 'Soyez patient $N. La torche est presque terminée.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000020, 'That''s interesting...', NULL, 'C''est intéressant...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000021, 'I need to consult Noram and Horatio.', NULL, 'Je dois consulter Noram et Horatio.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000022, 'Look! Minions of Terokk are approaching!', NULL, 'Regardez ! Les larbins de Terokk se rapprochent !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000023, 'Look out! More are coming!', NULL, 'Regardez ! D''autres arrivent !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000024, 'And even more!', NULL, 'Et encore d''autres !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000025, 'An Avatar of Terokk! To arms!', NULL, 'Un avatar de terokk ! Aux armes !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000026, 'Whoops!', NULL, 'Whoops !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000027, '[PH] temp text', NULL, '[PH] temp text', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000028, 'Good luck stranger, and welcome to Shattrath City', NULL, 'Bonne chance étanger, et bienvenue dans la ville de Shattrath.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000029, 'Follow, $N. I will soon begin the summoning...', NULL, 'Suivez-moi, $N. Je vais bientôt commencer le rituel d''invocation...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000030, 'This makes sense!', NULL, 'Tout s''explique !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000031, 'Your body is mine! Our fates are forever intertwined!', NULL, 'Votre corps est à moi ! Nos destins sont pour toujours entrelacés !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000032, 'Gird yourself $N, for the demon in this orb is a fel beast.', NULL, 'Attachez-vous $N, le démon de cet orbe est une bête gangrénée.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000033, 'Keep moving!', NULL, 'Continuez à vous déplacer !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000034, 'Come, $N. Lord Stormrage awaits.', NULL, 'Venez, $N. Le seigneur Hurlorage attend.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000035, 'Warriors of Dragonmaw, gather ''round! One among you has attained the rank of highlord! Bow your heads in reverence! Show your respect and allegiance to Highlord $N!', NULL, 'Guerriers Gueule-de-Dragon, approchez-vous ! L''un d''entres vous a atteint le grade de généralissime ! Inclinez-vous face à lui ! Montrez votre respect et votre allégeance au généralissime !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000036, 'Lord Illidan will be here shortly.', NULL, 'Le seigneur Illidan sera bientôt là.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000037, 'All hail Lord Illidan!', NULL, 'Gloire au Seigneur Illidan !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000038, 'Lord Illidan, this is the Dragonmaw that I, and others, have told you about. He will lead us to victory!', NULL, 'Seigneur Illidan, c''est le gueule-de-dragon donc nous vous avons parlé. Il nous mènera à la victoire !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000039, 'But... My lord, I do not understand. $N... He is the orc that has...', NULL, 'Mais... Mon Seigneur, je ne comprend pas. $N... C''est un orc qui a...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000040, 'It will be done, my lord.', NULL, 'Ce sera fait, mon Seigneur.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000041, 'So you thought to make a fool of Mor''ghor, eh? Before you are delivered to Lord Illidan, you will feel pain that you could not know to exist. I will take pleasure in exacting my own vengeance.', NULL, 'Donc vous pensiez que vous pouviez vous moquer de Mor''ghor n''est-ce pas ? Avant que vous soyez livré au Seigneur Illidan vous allez souffrir comme n''avez jamais souffert. Je vais exercer ma propre vengeance comme je l''entend.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000042, 'Until we meet again, brave one.', NULL, 'Jusqu''à ce que nous nous croisions à nouveau.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000043, 'begins a spell of summoning...', NULL, 'incante un sort d''invocation...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000044, 'It is done...', NULL, 'C''est fait...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000045, 'There''s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!', NULL, 'Il n''y a rien de tel qu''un brevage brûlant un jour frisquet à Dun Morogh pour bien démarrer la journée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000046, 'Oooooo hot hot hot! If that won''t put spring IN your step,I don''t know what will!', NULL, 'Oooooh chaud chaud chaud ! Si cela ne nous ramène pas le printemps, je ne sais pas ce qui le fera !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000047, 'Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit!', NULL, 'Ribbit! Non! Cela ne peut pas ... ribbit ... soit! Vous m''avez trompé avec ... ribbit ... votre ruse immonde! Ribbit!', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000048, 'Now let us place this rare earth in my planter...', NULL, 'Maintenant, nous allons placer cette terre rare dans ma jardinière ...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000049, 'Thank you again, $N. This rare earth will be very helpful in my experiments.', NULL, 'Merci encore, $N. Cette terre rare sera très utile pour mes expériences.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000050, 'Hello Grimclaw', NULL, 'Bonjour Griffe-sinitre.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000051, 'What happens?', NULL, 'Qu''est-ce qu''il se passe ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000052, 'Volcor was gone?', NULL, 'Volcor est parti ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000053, 'You know where he is?', NULL, 'Vous savez où il est ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000054, 'Well, ok. I am now sending people . We need find and help him.', NULL, 'Bien, d''accord. Je vais envoyer des hommes sur-le-champ. Nous devons le trouver et l''aider.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000055, 'How many more of you grunts do I need to send back to mommy and daddy in a body bag before you grow a brain and realize that runnin'' head first into a Legion kill squad is suicide? And don''t nod your thick skulls at me as if you know what I''m talkin'' about!', NULL, 'Combien de grunts devrons-nous encore ramener à papa et maman dans un sac mortuaire avant que tu ne deviennes intelligent et que tu ne réalises que foncer dans une escouade de la Légion est du suicide ? Et ne hoche pas la tête comme si tu savais de quoi je parle !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000056, 'Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N.', NULL, 'Hé là, Belm! Donne-moi une chope de bière Tonnerre, et apportes-en une autre pour mon bon ami $N.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000057, 'Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N''s pleas, and I trust his inent is noble. Please, will you aid us?', NULL, 'Esprits de l''eau, je vous implore et vous demande une faveur. Vous avez entendu le souhait de $N, et je peux vous assurer que sa cause est noble. Je vous en prie, pouvez-vous nous aider ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000058, 'Thank you great spirit. Thank you!', NULL, 'Merci grand esprit, merci !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000059, 'You are Dismissed, $N', NULL, 'Vous êtes renvoyé, $N !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000060, 'By the stars! A spirit has been summoned!', NULL, 'Par les cieux ! Un esprit a été invoqué !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000061, 'It''s a mystery of the past indeed! But a key to our future!', NULL, 'C''est un mystère du passé ! Mais une clé du futur !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000062, 'The threat be over! $N be savin'' us all!', NULL, 'La menace n''est plus! $N nous a tous sauvés !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000063, 'Follow me, good $C. I''ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout.', NULL, 'Suivez-moi, brave $C. Je vais confectionner votre objet plus vite qu''un nain. Mmmm ...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000064, 'Well, that should do it. Come now, back to the shop to finish our business!', NULL, 'Bien, ça devrait le faire. Venez maintenant, retournons au magasin et finissons notre affaire !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000065, 'We will suffer no demon''s servant in our lands!', NULL, 'Nous n''accepterons aucun serviteur de démon dans nos contrées !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000066, 'Peace and patience be with you, $N. Remain strong always.', NULL, 'Que Paix et patience soit avec vous, $N. Restez toujours $Gfort:forte;.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000067, 'What are you doing in Ysera''s realm, interloper? Leave us, I say! Your kind are not welcome here!', NULL, 'Que faites-vous dans le royaume d''Ysera, intrus ? Je vous demande de partir ! Votre espèce n''est pas la bienvenue ici !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000068, 'You -- you''re not one of them! Let''s get out of sight before they find us! Hurry!', NULL, 'Vous - vous n''êtes pas l''un d''eux! Sortons de là avant de qu''ils nous trouvent ! Dépêchez-vous!', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000069, 'They''re following me, $R! Quickly, tell me why you''re here before we''re discovered! If they catch up to me, it will mean my death and yours!', NULL, 'Ils me suivent, $R ! Vite, dites-moi pourquoi vous êtes ici avant que nous soyons découverts ! S''ils nous attrappent, cela signfie la mort pour vous et moi !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000070, 'It would''ve taken years to find the Book of the Raven without you, young sparrowhawk. Return to your home in Nagrand with our gratitude.', NULL, 'Il aurait fallu des années pour trouver le Livre du Corbeau, sans vous, jeune épervier. Retournez à votre domicile en Nagrand, avec toute notre gratitude.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000071, 'This is it! This is really it -- the Book of the Raven!', NULL, 'C''est lui ! C''est réellement ça -- Le Livre du Corbeau !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000072, 'It''s all here... how the raven''s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god''s name -- Anzu. I''d thought it was lost to history!', NULL, 'Tout est là... comment les disciples du corbeau ont capturé et soumis les esprits de leurs adversaires, les piégeant dans des statues de pierre à jamais ! La tablette mentionne même le nom du dieu corbeau - Anzu. Je croyais qu''il était perdu pour toujours !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000073, 'There''s something else here, too. After a discription of a bloody battle and the downfall of the raven, there''s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...', NULL, 'Il y a autre chose ici aussi. Après une bataille sanglante et la chute du corbeau, il y a une prophétie. Anzu va hanter les rêves de ses ennemis, jusqu''à revenir dans ce monde ...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000074, 'The tablet has the confirmation we need, just as I thought. Now, we have to use this information to draw out and defeat this Anzu before he can do any more damage to the Emerald Dream!', NULL, 'La tablette apporte la confirmation de ce que je pensais. Maintenant, nous devons utiliser cette information pour vaincre cet Anzu avant qu''il ne puisse causer plus  de dommages au Rêve d''émeraude !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000075, 'Since the sparrowhawks have proven such a success in hunting down the raven stones, Watcher Elaira has trained another one to relay my voice at a great distance. He can help us communicate as you investigate the bird spirits revealed in the tablet!', NULL, 'Etant donné que les éperviers ont prouvé leur succès en tant que chasseurs de pierres de corbeau, la gardienne Elaira en a entraîné d''autres. Ils nous aideront à communiquer pendant que vous faîtes vos recherches sur les esprits d''oiseaux mentionnés dans la tablette.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000000076, 'Hear ye, denizens of Tanaris! Let it be known $n is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $n!', NULL, 'Oyez, habitants de Tanaris ! Que l''on sache que $N est un membre exalté de l''ordre du Mithril. Un forgeron d''honneur, qui s''est dévoué avec une patience infinie. Gloire à $N !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005210, 'I''ll never stop. Never...', NULL, 'Je n''arrêterai jamais. Jamais...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005209, 'Don''t wait! Order now and receive my Ultra-Kinetic Waffle Iron at no additional charge!', NULL, 'N''attendez plus ! Commandez maintenant et recevez mon Moule à gauffre ultra-kinétique en fer sans aucun surcoût !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005208, 'Wine stains, grass stains, even pet stains are no match for the Electrostatic Maculation Blaster!', NULL, 'Les taches de vins, les taches d''herbes, et même les taches de boue ne résisteront pas au blaster nettoyant electrostatique ! ', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005207, 'Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!', NULL, 'Dérivé d''une technologie militaire de pointe appartenant à la Main Brisée, il désintègre les taches difficiles !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005206, 'Be the first on your block to own the incredible Electrostatic Maculation Blaster!', NULL, 'Soyez le premier à acquérir le fabuleux blaster nettoyant électrostatique !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005205, 'It''s coming along, Wafflefry. Haven''t you got a product demonstration to do or something?', NULL, 'Les gens semblent intéressés, Grillegauffre. Est-ce que tu n''aurais pas une démonstration à faire ou quelque chose comme ça ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005204, 'Hmm, don''t mind if I do!', NULL, 'Mmh, ne vous plaignez après !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005203, 'Yer wearin down, princess, I can sense it!', NULL, 'Vous êtes en train de vous épuiser petit à petit princesse, je peux le sentir !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005202, 'Ahh, my precious Ameenah! How wonderful to see you again.', NULL, 'Ahh, ma précieuse Ameenah ! C''est merveilleux de vous voir à nouveau.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005201, 'Charge!', NULL, 'Chargez !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005200, 'Charge!', NULL, 'Chargez !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005199, 'Best drinks in Stormwind!', NULL, 'La meilleure boisson de Hurlevent !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005198, 'Head on over to the Blue Recluse. Where everybody knows your name!', NULL, 'Dirigez-vous vers solitaire bleu. Là où tout le monde connait votre nom !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005197, 'Ask me how you can get a free drink at the Blue Recluse!', NULL, 'Demandez-moi comment vous pouvez obtenir une boisson gratuite au solitaire bleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005196, 'Best drinks in Stormwind!', NULL, 'La meilleure boisson de Hurlevent !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005195, 'Magical studies stressing your brain? Relax at the Blue Recluse!', NULL, 'Les études de la magie fatiguent votre cerveau ? Détendez-vous au solitaire bleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005194, 'Feeling blue? Come on down to the Blue Recluse for a good time!', NULL, 'Vous vous sentez déprimé ? Venez passer du bon temps au solitaire bleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005193, 'Free drinks at the Blue Recluse!', NULL, 'Boissons gratuites au solitaire bleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005192, 'Head on over to the Blue Recluse. Where everybody knows your name!', NULL, 'Dirigez-vous vers le solitaire bleu. Là où tout le monde connaît votre nom !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005191, 'Ask me how you can get a free drink at the Blue Recluse!', NULL, 'Demandez-moi comment obtenir une boisson gratuite au solitaire bleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005190, 'Magical studies stressing your brain? Relax at the Blue Recluse!', NULL, 'Les études de la magie vous donnent mal à la tête ? Relaxez-vous au solitaire bleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005189, 'Best drinks in Stormwind!', NULL, 'La meilleure boisson de Hurlevent !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005188, 'Feeling blue? Come on down to the Blue Recluse for a good time!', NULL, 'Vous vous sentez déprimé ? Venez passer du bon temps au solitaire bleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005187, 'Head on over to the Blue Recluse. Where everybody knows your name!', NULL, 'Dirigez-vous au solitaire bleu. Là où tout le monde connaît votre nom !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005186, 'Best drinks in Stormwind!', NULL, 'La meilleure boisson de Hurlevent !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005185, 'Magical studies stressing your brain? Relax at the Blue Recluse!', NULL, 'Les études de la magie vous donnent mal à la tête ? Détendez-vous au solitaire bleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005184, 'Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.', NULL, 'Flopp était un grand magicien mais il s''est fait tranformer en lapin à cause de l''un de ses sorts qui a mal tourné.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005183, 'Mommy? Can I pet Fizzles?', NULL, 'Maman ? Puis-je câliner Flopp ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005182, 'Thanks, Charys. C''mon Paige, sweetie.', NULL, 'Merci, Charys. Viens, ma chère Paige.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005181, 'Sure Paige. Just be gentle.', NULL, 'Bien sûr Paige. Sois juste gentille.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005180, 'Hello, Charys. I have my list, could you get me all of that, especially the last ingredient.', NULL, 'Bonjour, Charys. J''ai ma liste, pourrais-tu me faire parvenir tout ça, spécialement le dernier ingrédient.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005179, 'Wow, all this for a love potion. Hope he is worth it.', NULL, 'Waow, tout ça pour une potion d''amour. J''espère qu''il en vaut la peine.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005178, 'But if we stabilize it with an anchor thread at the appropriate energy crux then it should work.', NULL, 'Mais si nous le stabilisons avec une ancre et le noeud d''energie approprié, alors ça pourrait marcher.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005177, 'If we use the appropriate sequence we should be ok. Will just take some serious studying before we start.', NULL, 'Si nous utilisons la séquence appropriée, ça devrait être bon. Nous devons juste être sûrs de nous avant de commencer.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005176, 'What if we used three focuses in Tyrean pattern? That should solve it.', NULL, 'Et si nous utilisions trois concentrations dans le modèle de Tyrean ? Ca devrait résoudre le problème.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005175, 'But if we stabilize it with an anchor thread at the appropriate energy crux then it should work.', NULL, 'Mais si nous le stabilisons avec une ancre et le noeud d''energie approprié, alors ça pourrait marcher.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005174, 'Wow, all this for a love potion. Hope he is worth it.', NULL, 'Waow, tout ça pour une potion d''amour. J''espère qu''il en vaut la peine.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005173, 'The Portal will shift slightly. At this point if you cast a binding cantrip you will solidify it in place.', NULL, 'Le portail va se modifier légèrement. A ce moment, si vous lancez sorcelet, vous pourrez le solidifier sur place.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005172, 'If we use the appropriate sequence we should be ok. Will just take some serious studying before we start.', NULL, 'Si nous utilisons la séquence appropriée, ça devrait être bon. Nous devons juste être sûrs de nous avant de commencer.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005171, 'Wow, all this for a love potion. Hope he is worth it.', NULL, 'Waow, tout ça pour une potion d''amour. J''espère qu''il en vaut la peine.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005170, 'What if we used three focuses in Tyrean pattern? That should solve it.', NULL, 'Et si nous utilisions trois concentrations dans le modèle de Tyrean ? Ca devrait résoudre le problème.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005169, 'If we reverse the Essence flows perhaps we can alter the polarity.', NULL, 'Si nous altérons le flux d''essence, peut-être pourrons-nous inverser la polarité.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005168, 'Why do we have to learn this stuff anyway?', NULL, 'Pourquoi devons-nous apprendre cette matière ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005167, 'Is it true that the paladins train here?', NULL, 'Est-ce vrai que les entraîneurs des paladins se trouvent ici ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005166, 'But isn''t that what caused the initial problems with Adept Syleria''s magical formula?', NULL, 'Mais, n''est-ce pas ce qui a causé le problème initial avec les adeptes de la magie de Syleria ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005165, 'But wouldn`t that mean crossing the streams? Isn`t that really bad?', NULL, 'Mais est-ce que ça ne signifie pas dépasser les limites ? N''est-ce pas un mauvaise chose ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005164, 'Maginor says that twisting alternating flows of positive energy actually creates a much more stable flow.', NULL, 'Maginor dit que le fait de tordre les flux d''énergie positive par alternance crée en fait un flux beaucoup plus stable.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005163, 'I think not, I don''t need to be blown up again.', NULL, 'Je ne crois pas, je n''ai pas besoin de tout faire sauter encore une fois.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005162, 'But isn''t that what caused the initial problems with Adept Syleria''s magical formula?', NULL, 'Mais, n''est-ce pas ce qui a causé le problème initial avec les adeptes de la magie de Syleria ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005161, 'Why can''t we just shift the array to compensate for the variance in the flux?', NULL, 'Pourquoi ne pouvons-nous simplement pas modifier le tableau pour compenser la variance du flux ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005160, 'But wouldn`t that mean crossing the streams? Isn`t that really bad?', NULL, 'Mais est-ce que ça ne signifie pas dépasser les limites ? N''est-ce pas un mauvaise chose ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005159, 'That will unbalance the magical focus, though, and cause a reverse vibration in the ether.', NULL, 'Cela va cependant déséquilibrer le point magique, et provoquer une vibration inverse dans l''éther.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005158, 'When the positively aligned energies collide with the negatively charged energies, they don`t negate one another.', NULL, 'Lorsque les énergies alignées de façon positive entrent en collision avec les énergies chargées négativement, elle ne se détruisent pas les unes les autres.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005157, 'But what if the resulting frequency shift were to send magical feedback up the flows?', NULL, 'Mais que faire si le décalage de fréquence qui en résulte envoie des energies magiques à travers les flux ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005156, 'I suppose that could work, if we had twenty people to cast it with.', NULL, 'Je suppose que ça peut marcher, si nous avons une vingtaine de personnes pour nous aider dans l''incantation.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005155, 'But isn''t that what caused the initial problems with Adept Syleria''s magical formula?', NULL, 'Mais, n''est-ce pas ce qui a causé le problème initial avec les adeptes de la magie de Syleria ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005154, 'At least we would not be around to have to clean it up.', NULL, 'Au moins, nous ne serions pas là à devoir le nettoyer.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005153, 'Only if we did not follow the proper initialization procedures.', NULL, 'Seulement si nous ne suivons pas les procédures d''initalisation obligatoires.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005152, 'Only if we did not follow the proper initialization procedures.', NULL, 'Seulement si nous ne suivons pas les procédures d''initialisation obligatoires.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005151, 'The resultant energies could collapse though, and that could cause an energy flux that would give you a migraine for weeks.', NULL, 'Les énergies qui en résultent risquent de s''effondrer, et cela pourrait provoquer un flux d''énergie qui vous donnerait une migraine pendant des semaines.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005150, 'Only if we did not follow the proper initialization procedures.', NULL, 'Seulement si nous ne suivons pas les procédures d''initialisation obligatoires.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005149, 'At least we would not be around to have to clean it up.', NULL, 'Au moins, nous ne serions pas là à devoir le nettoyer.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005148, 'Putting in twelve centers of focus might allow the magical energies to form more solidly, adding the necessary stability.', NULL, 'Le mettre dans douze centres de concentration pourrait permettre aux énergies magiques de se former plus rapidement, en ajoutant la stabilité nécessaire.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005147, 'Don''t go close to the lake! It''s haunted!', NULL, 'N''allez pas à proximité du lac ! Il est hanté !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005146, 'Duck!', NULL, 'Canard !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005145, 'How can anyone live like this!?', NULL, 'Comment quelqu''un peut vivre comme ça ?!', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005144, 'This must be fixed!', NULL, 'Ca doit être fixé !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005143, 'This will never do..', NULL, 'Ca ne sera jamais...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005142, 'Now, take another long look before we make our way to the Holy District and the great Cathedral of Light.', NULL, 'Maintenant, regardez autour de vous une dernière fois, avant que nous nous dirigions vers le District Saint de la grande Cathédrale de la Lumière.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005141, 'Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people.', NULL, 'À couper le souffle. Les enfants, quand nous reviendrons à l''école, vous ferez chacun un rapport oral sur l''un de ces personnages légendaires.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005140, 'Isn''t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands.', NULL, 'N''est-ce pas incroyable les enfants ? Tout ceux qui entrent dans la capitale devraient venir ici pour admirer les plus grands héros que comptent nos contrées.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005139, 'Yes, well...let''s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me.', NULL, 'Oui, bien... Allons jeter une oeil sur le monument dédié aux héros des deux Grandes Guerres, la vallée des Héros. Suivez-moi.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005138, 'When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival.', NULL, 'Lorsque la Horde fut brisée, les hommes de retour ici ont commencé à reconstruire la ville. Elle est à présent un magnifique témoignage de notre survie.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005137, 'Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War.', NULL, 'Ici, nous avons le Donjon de Hurlevent. Construit sur ​​les ruines du château de Hurlevent, qui a été détruit par la Horde dans la première Grande Guerre.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005136, 'Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.', NULL, 'Les enfants, si vous voulez bien me suivre, nous allons maintenant aller voir le donjon où le Roi Anduin Wrynn lui-même est assis sur son trône.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005135, 'Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral.', NULL, 'Oui, c''est vrai. Les paladins et les prêtres s''entraînent et découvrent de grandes vérités derrière les murs de la Cathédrale.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005134, 'Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind.', NULL, 'Ici nous avons la Cathédrale de la Lumière, le centre de l''illumination spirituelle de Hurlevent.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005133, 'Having a good time?', NULL, 'Vous passez du bon temps ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005132, 'Look alive, dogs! We got an operation to run here!', NULL, 'Hey, les gars ! Nous venons de recevoir un ordre de mission urgente !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005131, 'Really?', NULL, 'Vraiment ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005130, 'Wow.', NULL, 'Waouw.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005129, 'That''s neat.', NULL, 'C''est chouette.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005128, 'Wow.', NULL, 'Waouw.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005127, 'Really?', NULL, 'Vraiment ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005126, 'My father says that''s just a story.', NULL, 'Mon père dit que c''est juste une histoire.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005125, 'Wow.', NULL, 'Waouw.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005124, 'Really?', NULL, 'Vraiment ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005123, 'Can you imagine?', NULL, 'Peux-tu imaginer ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005122, 'Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.', NULL, 'Les vers vont sur le crochet, le crochet va dans l''eau, les poissons sont dans l''eau. Nos poissons.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005121, 'I hope that was a fish!', NULL, 'J''espère que c''était un poisson !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005120, 'I think i see something.', NULL, 'Je crois que je vois quelque chose.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005119, 'Eww... that''s not a fish!', NULL, 'Erf... Ce n''est pas un poisson !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005118, 'I think i see something.', NULL, 'Je crois que je vois quelque chose.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005117, 'I got worm guts on my shoes.', NULL, 'J''ai fait tomber des vers sur mes chaussures.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005116, 'Eww... that''s not a fish!', NULL, 'Erf... Ce n''est pas un poisson !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005115, 'And that''s how Lother killed thirty six orcs with his bare hands!', NULL, 'Et c''est ainsi que Lother a tué 36 orcs à mains nues!', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005114, 'I dont think there''s any fish in these canals.', NULL, 'Je ne crois pas qu''il y ait le moindre poisson dans ces canaux.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005113, 'You know why Orcs eyes glow red? It''s because they drink blood!', NULL, 'Vous savez pourquoi les orcs ont les yeux rouges ? C''est parce qu''ils boivent du sang !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005112, 'I swear, people have actualy seen them. Pandaren really do exist!!', NULL, 'Je le jure. Des gens les ont vraiment vus. Les Pandarens existent vraiment !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005111, 'And then the rabbit just bit his head off... I swear.', NULL, 'Et après, les lapins lui ont arrachés la tête... Je le jure.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005110, 'They say he can turn into a raven sometimes.', NULL, 'Ils disent qu''il lui arrive de se transformer en corbeau.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005109, 'They say he can turn into a raven sometimes.', NULL, 'Ils disent qu''il lui arrive de se tranformer en corbeau.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005108, 'Deja vu. For a moment I thought I was back home... before the plague...', NULL, 'Déjà vu. Pendant un moment j''ai cru que j''étais de retour à la maison... Avant la peste...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005107, 'Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.', NULL, 'J’ai l’impression de faire une centaine de fois par jour ce trajet vers le puits pour aller chercher plus d’eau. Aucun respect pour leurs aînés, je vous dis.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005106, 'As if I dont have better things to do in my old age than carry buckets of water.', NULL, 'Comme si je n''avais pas autre chose à faire que porter des seaux d''eaux à mon âge.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005105, 'Of Course Im talking to myself. Only way to get a decent conversation in this city.', NULL, 'Bien sûr que je parle toute seule. C''est la seule façon d''avoir une conversation intelligente dans cette ville.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005104, 'Wheres the water Emma? Get the water Emma? Ifn it werent fer me that lot wouldnt know what water looks like.', NULL, 'Où est l''eau Emma ? Tu es allée chercher de l''eau Emma ? Comme si je ne savais pas à quoi ressemble de l''eau.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005103, 'Jack and Jill my wrinkled patoot! I do all the water luggin round here.', NULL, 'Jack et Jill, mes vieux amis ! C''est moi qui me trimballe toute l''eau ici.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005102, 'Get it while its hot', NULL, 'Prenez-le tant que c''est chaud.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005101, 'Fresh bread for sale', NULL, 'Pain frais à vendre !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005100, 'Get it while its hot', NULL, 'Prenez-le tant que c''est chaud.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005099, 'Fresh bread for sale', NULL, 'Pain frais à vendre !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005098, 'Don''t hurt Betsy, you meanie!', NULL, 'Ne fais pas de mal à Betsy, méchant !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005097, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005096, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005095, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005094, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005093, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005092, 'Don''t hurt Betsy, you meanie!', NULL, 'Ne fais pas de mal à Betsy, méchant !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005091, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005090, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005089, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005088, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005087, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005086, 'Don''t hurt Betsy, you meanie!', NULL, 'Ne fais pas de mal à Betsy, méchant !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005085, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005084, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005083, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005082, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005081, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005080, 'Don''t hurt Betsy, you meanie!', NULL, 'Ne fais pas de mal à Betsy, méchant !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005079, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005078, 'Gimmie my dolly!!', NULL, 'Donne-moi ma poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005077, 'I wonder if your dolly can swim!', NULL, 'Je me demande si ta poupée sait nager !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005076, 'Baby wants her dolly!', NULL, 'Bébé veut sa poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005075, 'Crybaby! Crybaby!', NULL, 'Pleure bébé !\r\nPleure bébé !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005074, 'I have your dolly! Nyah nyah!', NULL, 'J''ai ta poupée ! Nyah nyah !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005073, 'Baby wants her dolly!', NULL, 'Bébé veut sa poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005072, 'Ha ha! I have Betsy!', NULL, 'Ha ha ! J''ai Betsy !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005071, 'I wonder if your dolly can swim!', NULL, 'Je me demande si ta poupée peut nager !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005070, 'Baby wants her dolly!', NULL, 'Bébé veut sa poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005069, 'Crybaby! Crybaby!', NULL, 'Pleure bébé !\r\nPleure bébé !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005068, 'I have your dolly! Nyah nyah!', NULL, 'J''ai ta poupée ! Nyah nyah !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005067, 'Baby wants her dolly!', NULL, 'Bébé veut sa poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005066, 'Ha ha! I have Betsy!', NULL, 'Ha ha ! J''ai Betsy !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005065, 'I wonder if your dolly can swim!', NULL, 'Je me demande si ta poupée sait nager !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005064, 'Baby wants her dolly!', NULL, 'Bébé veut sa poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005063, 'Crybaby! Crybaby!', NULL, 'Pleure bébé !\r\nPleure bébé !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005062, 'I have your dolly! Nyah nyah!', NULL, 'J''ai ta poupée ! Nyah nyah !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005061, 'Baby wants her dolly!', NULL, 'Bébé veut sa poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005060, 'Ha ha! I have Betsy!', NULL, 'Ha ha ! J''ai Betsy !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005059, 'I wonder if your dolly can swim!', NULL, 'Je me demande si ta poupée sait nager !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005058, 'Baby wants her dolly!', NULL, 'Bébé veut sa poupée !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005057, 'Crybaby! Crybaby!', NULL, 'Pleure bébé !\r\nPleure bébé !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005056, 'Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?', NULL, 'Bien. Nou venons de nous casser le dos à transporter tout le matériel ici, et vous voulez que nous en fassions encore plus ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005055, 'Bip!', NULL, 'Bip !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005054, 'Bip!', NULL, 'Bip !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005053, 'Bip!', NULL, 'Bip !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005052, 'Hey, you there. Want some candy?', NULL, 'Hey, toi ici. Tu veux un bonbon ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005051, 'Great Gazlowe!', NULL, 'Grande Gazleu !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005050, 'Well hand it overand let''s see what you got!', NULL, 'Bien, voyons voir ce que tu as à nous montrer !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005049, 'I have another reading from the nether.', NULL, 'J''ai un autre papier venant du Néant.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005048, 'Having a good time?', NULL, 'Vous passez du bon temps ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005047, 'You want to go do the bounty off of this wanted poster after this shift is over?', NULL, 'Est-ce que vous voulez récuperer la prime de cet avis de recherche une fois que nous aurons terminé notre tour de garde ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005046, 'I''m up to looking into that bounty after this shift.', NULL, 'je suis partant pour essayer d''avoir cette récompense après mon tour de garde.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005045, 'Just don''t ask me where I got it...', NULL, 'Ne me demandez pas où j''ai pu le mettre....', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005044, 'US ALREADY ALL ANYMORE AND ANYMORE', NULL, 'NOUS SOMMES PLUS NOMBREUX A CHAQUE INSTANT !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005043, 'I WILL DESTROY ALL', NULL, 'JE VAIS TOUT DETRUIRE', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005042, 'New posting up! Adventurers and heroes, gather round the bulletin board!', NULL, 'Nouvelle affiche ! Les aventuriers et les héros, rassemblez-vous autour du panneau d''affichage!', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005041, 'I will do my best to take care of the children, Grandmother.', NULL, 'Je ferai de mon mieux pour prendre soin des enfants, Grand-mère.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005040, 'Very well. When that decision is made, I will be ready. Let us hope it won''t be too late.', NULL, 'Très bien. Lorsque cette décision sera prise, je serai prêt. Espérons qu''il ne sera pas trop tard.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005039, 'The wind speaks of our enemies'' movements, Ashyen. The Naga will attack again.', NULL, 'Le vent nous prévient des mouvements de nos ennemis, Ashyen. Les Nagas vont attaquer à nouveau.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005038, 'Tell us! Where does you leader hide?', NULL, 'Dites nous ! Où se cache votre leader ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005037, 'I might just have to go hunting for that Wretched beast now that there''s a bounty on his head.', NULL, 'Je pourrais aller à la chasse à cette pauvre bête maintenant qu''il y a une prime sur sa tête.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005036, 'Please! I must feed on something soon... A mana crystal... a shard... anything! The pain is unbearable!', NULL, 'S''il vous plaît ! Je dois me nourrir de quelque chose ... Un cristal de mana ... un fragment ... n''importe quoi ! La douleur est insupportable !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005035, 'It''s getting away!', NULL, 'Ca s''en va !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005034, 'Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don''t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate! All it takes is five or more and you''re on your way to the most wondrous prizes in all of Outland. Everybody is a winner', NULL, 'Bienvenue à tous à la foire de Sombrelune, le plus grand événement dans tous les mondes ! Nous avons tout ... de la nourriture délicieuse, des boissons fortes, des objets exotiques, les livres les plus palpitants, des prix incroyables et de l''excitation sans fin! N''oubliez pas de présenter vos billets pour la Foire à  Gelvas Crasseporte! Prenez cinq minutes pour découvrir les prix les plus merveilleux! Tout le monde est gagnant !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005033, 'Come one, come all! Welcome to the Darkmoon Faire! Do you crave adventure? Do you seek exotic and mysterious treasures? Then look no further! You, my friend, have come to the right place! Dive right in and take part in all that the Faire has to offer! We''ll be at this location all week, so be sure to tell your friends and loved ones!', NULL, 'Venez, venez tous! Bienvenue à la foire de Sombrelune ! Avez-vous envie d''aventure ? Cherchez-vous des trésors exotiques et mystérieux ? Alors ne cherchez pas plus loin! Vous, mon ami, vous êtes au bon endroit ! Profitez de tout ce que nous avons à vous offrir ! Nous serons ici toute la semaine, alors assurez-vous de le dire à vos amis et vos proches !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005032, '...And then the tauren said, "13 INCHES!"', NULL, '...Et alors le tauren s''écria, "13 POUCES !"', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005031, 'I come from the land down under... where women plague and men sunder.', NULL, 'Je viens d''une contrée souterraine ... où la peste emporte les hommes et les femmes.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005030, 'If you wait to come see me, there may be nothing left!', NULL, 'Si vous attendez pour venir me voir, nous n''avancerons pas !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005029, 'Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.', NULL, 'Nos plus anciens dragons sont encore loin de la maturité, mais avec de la patience et de l''entraînement, nous sommes persuadés qu''ils seront bientôt prêts.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005028, 'Tomorrow we will begin training of our promising dragons, so don''t forget your chew toys.', NULL, 'Demain, nous allons commencer la formation de nos dragons, il ne faut pas oublier vos jouets à mâcher.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005027, 'The Lich King''s forces are building. It is imperative that our timetable supports his plans.', NULL, 'Les forces du Roi Liche sont en train de grandir. Il est impératif que notre calendrier prenne en charge ses plans.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005026, 'Come speak with me, and what once was cloudy shall become crystal clear.', NULL, 'Venez parler avec moi, et ce qui était autrefois couvert va devenir limpide.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005025, 'Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!', NULL, 'Cadeaux ! Obtenez vos cadeaux ici! Venez ici et montrer vos billets pour la Foire de Sombrelune, ils pourront vous faire gagner des prix incroyables !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005024, 'It''s getting away!', NULL, 'Ca s''en va !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005023, 'Every item that I have for sale I acquired myself. You have my personal guarantee of authenticity.', NULL, 'Tous les objets que je vends ici, je les ai acquis moi-même. Vous avez une garantie totale sur l''authenticité des produits.', NULL, NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
(2000005022, 'Wouldn''t you like to bring those days back? I have some friends who know just the way to do that.', NULL, 'N''aimeriez-vous pas revenir parfois en arrière ? J''ai quelques amis qui connaissent la méthode pour revenir dans le passé.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005021, 'When you''re off duty, let''s go to the inn. I''ll buy a round and we can reminisce about the good old days.', NULL, 'Lorsque vous serez en congé, nous irons à la taverne. Je payerai ma tournée et nous nous rappelerons du bon vieux temps.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005020, 'It''s good to see you defending Theramore with pride, friend.', NULL, 'C''est bon de vous voir défendre Theramore avec tant d''ardeur l''ami.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005019, 'You might wanna stand back. Fish guttin'' is a dirty job.', NULL, 'Vous devriez vous reculer un peu. La pêche est un sale boulot.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005018, 'Ah, this must be him now... no?', NULL, 'Ah, ce doit être lui... Non ?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005017, 'I''m inclined to say they made ogres too big! I can see I''m not going to convince you to move now, but don''t think this is permanent!', NULL, 'Question de point de vue. Je pense que quelqu''un a construit les ogres trop grands. Bon, je ne vais pas te convaincre de bouger, mais ne t''imagine pas que c''est définitif !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005016, 'Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here!', NULL, 'Oui, on a dit que tu pouvais rester, mais ce bâtiment est notre quartier général. C''est là qu''on garde tous nos manuels et tous nos plans !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005015, 'I thought we talked about this, Brogg. You can''t stay in this building. Sure, it can house you, but there''s no room for anyone else!', NULL, 'Brogg, on en a déjà parlé. Tu ne peux pas rester dans ce bâtiment. Bien sûr, il est à ta taille, mais il n''y a plus de place pour rien d''autre !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005014, 'But this the only building that fit Brogg! Goblins make buildings too small!', NULL, 'Mais c''est le seul à la taille de Brogg ! Gobelins construire trop petit !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005013, 'I don''t think Drazzit''s going to have any luck finding anyone to kill this raptor. I mean, he''s already raised the reward twice...', NULL, 'Je ne pense pas Drazzit va avoir la chance de trouver quelqu''un capable de tuer ce rapace. Je veux dire, il a déjà augmenté la récompense à deux reprises...', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005012, 'Mysterious hoofprints, scorched shields, stray badges... how do we make sense of all this?', NULL, 'Des traces de sabots, des boucliers mystérieux brûlés, des insignes inconnues... Comment pouvons-nous donner un sens à tout cela?', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005011, 'Yes right away momma!', NULL, 'Oui, tout de suite maman !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005010, 'Zug zug! Happy to help!', NULL, 'Zug zug ! Heureux d''aider !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005009, 'Well done, soldiers! At ease!', NULL, 'Bien joué soldats ! Comme toujours !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005008, 'SQUAWK!! *cough* *cough* I need to quit smoking!', NULL, 'SQAUWK !! *tousse* *tousse* J''ai besoin d''arrêter de fumer !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005007, 'Ask Kibler about the treasure! SQUAWK!', NULL, 'Demandez à Kibler de vous parler du trésor ! SQUAWK !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005006, 'They all go to the Spire but none never come back... just like Bijou.', NULL, 'Ils sont tous aller à la Flèche, mais aucun n''est revenu... tout comme Bijou.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005005, 'Dragons controlling orcs!? SQUAWK!', NULL, 'Les dragons contrôlent les orcs ?! SQUAWK !', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005004, 'Bijou knows where treasures are hidden.', NULL, 'Bijou sait où sont cachés les trésors.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005003, 'Kibler is being investigated by G.E.T.A.', NULL, 'Kibler est espionné par le G.E.T.A.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005002, 'Bijou lost! SQUAWK! *cough', NULL, 'Bijou est perdue ! SQUAWK ! *tousse*', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005001, 'Opus wants some Cuergo''s Gold... with worm.', NULL, 'Opus voudrait bien un peu de l''Or de Cuergo... avec des vers.', NULL, NULL, NULL, NULL, NULL, NULL),
(2000005000, 'Poor Dorius. If I ever get my hands on those Dark Irons, so help me...', NULL, 'Pauvre Dorius. Si jamais je mets la main sur ces Sombrefer, alors aidez-moi ...', NULL, NULL, NULL, NULL, NULL, NULL);
