/*!40101 SET NAMES utf8 */;

replace into `creature_text` values('197','0','0','You are dismissed, $N.', '','12','0','100','113','0','0','Marshal McBride');
replace into `creature_text` values('234','0','0','The People of Westfall salute $N, a brave and valiant defender of freedom.', '','12','7','100','0','0','0','Marshal Gryan Stoutmantle');
replace into `creature_text` values('253','0','0','This shouldn\'t take long...', '','12','0','100','432','0','0','William Pestle');
replace into `creature_text` values('253','1','0','The invisibility liquer is ready for you, $N.', '','12','0','100','0','0','0','William Pestle');
replace into `creature_text` values('836','0','1','There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!', '','12','7','100','1','0','0','Durnan Furcutter after quest');
replace into `creature_text` values('836','1','1','Oooooo hot hot hot! If that won\'t put spring in your step, I don\'t know what will!', '','12','7','100','400','0','0','Durnan Furcutter after quest');
replace into `creature_text` values('1268','0','0','Hmm, I suppose it could work. But it could really use a little more umph!', '','12','0','100','0','0','0','Ozzie Togglevolt reply');
replace into `creature_text` values('1373','0','0','%s gestures to the pitcher of water sitting on the edge of the well.', '','12','0','100','1','0','0','Jarven Thunderbrew');
replace into `creature_text` values('1373','1','0','Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N.', '','12','0','100','1','0','0','Jarven Thunderbrew');
replace into `creature_text` values('1373','2','0','How goes the barrel watching...?', '','12','0','100','1','0','0','Jarven Thunderbrew');
replace into `creature_text` values('1373','3','0','Well, back to business for me. But it sure was nice taking that short break, and it\'s always nice drinking Thunder Ale!', '','12','0','100','1','0','0','Jarven Thunderbrew');
replace into `creature_text` values('1416','0','0','Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout.', '','12','0','100','1','0','0','Grimand Elmore');
replace into `creature_text` values('1416','1','0','Well, that should do it. Come now, back to the shop to finish our business!', '','12','0','100','1','0','0','Grimand Elmore');
replace into `creature_text` values('1443','0','0','I hereby destroy these instruments of evil! For the Horde!', '','14','1','100','0','0','0','Felzerul on Quest 1445 finished');
replace into `creature_text` values('1493','0','0','SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!', '','14','0','100','0','0','0','Mok\'rash Yell');
replace into `creature_text` values('1493','0','1','SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!', '','14','0','100','0','0','0','Mok\'rash Yell');
replace into `creature_text` values('1493','0','2','DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!', '','14','0','100','0','0','0','Mok\'rash Yell');
replace into `creature_text` values('1493','0','3','COME OUT TO JANEIRO\'S POINT. I\'M WAITING FOR YOU, SMOTTS...', '','14','0','100','0','0','0','Mok\'rash Yell');
replace into `creature_text` values('1493','0','4','I PROMISE I WON\'T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM!', '','14','0','100','0','0','0','Mok\'rash Yell');
replace into `creature_text` values('1493','0','5','HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?', '','14','0','100','0','0','0','Mok\'rash Yell');
replace into `creature_text` values('1493','0','6','I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?', '','14','0','100','0','0','0','Mok\'rash Yell');
replace into `creature_text` values('1494','0','0','Mmmh...I SMELL FOOD!', '','14','0','100','0','0','0','Negolash Yell on Summon');
replace into `creature_text` values('1497','0','0','Take a Candle of Beckoning from this crate, $N.', '','12','0','100','25','0','0','Gunther Arcanus');
replace into `creature_text` values('1931','0','0','I. . .I. . .don\'t. . .feel. . .right. . .', '','12','0','100','1','0','0','Scarlet Zealot');
replace into `creature_text` values('1931','1','0','My mind. . .my flesh. . .I\'m. . .rotting. . . .!', '','12','0','100','1','0','0','Scarlet Zealot');
replace into `creature_text` values('2080','0','0','Now let us place this rare earth in my planter...', '','12','0','100','1','0','0','Denalan');
replace into `creature_text` values('2080','1','0','Thank you again, $N. This rare earth will be very helpful in my experiments.', '','12','0','100','1','0','0','Denalan');
replace into `creature_text` values('2080','2','0','Denalan hurries to his planter.', '','41','0','100','1','0','0','Denalan');
replace into `creature_text` values('2080','3','0','I hope this frond takes root...', '','12','0','100','1','0','0','Denalan');
replace into `creature_text` values('2080','4','0','Denalan removes the seeds from the Glowing Fruit...', '','41','0','100','1','0','0','Denalan');
replace into `creature_text` values('2080','5','0','Let\'s see how these seeds grow in my prepared soil...', '','12','0','100','1','0','0','Denalan');
replace into `creature_text` values('2080','6','0','Denalan plants fruit seeds.', '','41','0','100','1','0','0','Denalan');
replace into `creature_text` values('2080','7','0','Bogling rises from the soil!', '','41','0','100','1','0','0','Denalan');
replace into `creature_text` values('2150','0','0','Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit!', '','12','0','100','1','0','0','Zenn Foulhoof');
replace into `creature_text` values('2211','0','0','I raise my brew and hope to be rid of the likes of you! Cheers, you no good scoundrel, $N!', '','12','0','100','7','0','0','Captured Mountaineer - Reward quest 492');
replace into `creature_text` values('2249','0','0','%s goes into a frenzy!', '','16','0','100','0','0','0','Ferocious Yeti');
replace into `creature_text` values('2276','0','0','More agents of the Syndicate I\'ll wager! You\'ll never take back Alterac... Or Southshore!', '','12','7','100','0','0','0','Magistrate Henry Maleb');
replace into `creature_text` values('2391','0','0','Whoops!', '','12','0','100','113','0','0','Serge Hinott');
replace into `creature_text` values('2396','0','0','I spent my whole life caring for these trees. Pruning and nurturing them... only fitting that they have joined me in death.', '','12','1','100','0','0','0','Hans Zandin');
replace into `creature_text` values('2396','0','1','This orchard is now as barren and lifeless as my rotting shell. Once these trees bloomed with fruit but now there is only rot.', '','12','1','100','0','0','0','Hans Zandin');
replace into `creature_text` values('2405','0','0','Intruders! Attack the intruders!', '','12','33','100','0','0','0','Tarren Mill Deathguard');
replace into `creature_text` values('2428','0','0','Never cross a Dark Iron, $C.', '','12','0','100','0','0','0','Jailor Marlgen');
replace into `creature_text` values('2428','0','1','Time to die, $C!', '','12','0','100','0','0','0','Jailor Marlgen');
replace into `creature_text` values('2428','0','2','Feel the power of the Dark Iron Dwarves!', '','12','0','100','0','0','0','Jailor Marlgen');
replace into `creature_text` values('2433','0','0','Revenge shall be mine at last!', '','14','0','100','1','0','0','Helcular\'s Remains');
replace into `creature_text` values('2433','0','1','I have risen!', '','14','0','100','1','0','0','Helcular\'s Remains');
replace into `creature_text` values('2433','0','2','Southshore shall pay in blood!', '','14','0','100','1','0','0','Helcular\'s Remains');
replace into `creature_text` values('2433','1','0','The undead shall feast on your soul, $N.', '','14','0','100','1','0','0','Helcular\'s Remains');
replace into `creature_text` values('2435','0','0','Help me! Help! Assassins in the hills! To arms! To arms!', '','14','0','100','22','0','0','Southshore Crier');
replace into `creature_text` values('2435','1','0','Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction!', '','12','0','100','1','0','0','Southshore Crier');
replace into `creature_text` values('2435','2','0','%s grabs the back of his neck and his eyes go wide.', '','16','0','100','0','0','0','Southshore Crier');
replace into `creature_text` values('2435','3','0','Assassins... save... th... Magistraaa...', '','12','0','100','65','0','0','Southshore Crier');
replace into `creature_text` values('2911','0','0','By the stars! A spirit has been summoned!', '','12','0','100','1','0','0','Archaeologist Flagongut');
replace into `creature_text` values('2911','1','0','It\'s a mystery of the past indeed! But a key to our future!', '','12','0','100','1','0','0','Archaeologist Flagongut');
replace into `creature_text` values('2986','0','0','Until we meet again, brave one.', '','12','0','100','113','0','0','Dorn Plainstalker');
replace into `creature_text` values('2991','0','0','%s gestures to the pitcher of water sitting on the edge of the well.', '','16','0','100','0','0','0','Greatmother Hawkwind');
replace into `creature_text` values('3054','0','0','Zarlman Two-Moons begins chanting as he mixes the well stones and ambercom before the Tribal Fire.', '','16','1','100','0','0','0','Zarlman Two-Moons on Quest 771 finished 1');
replace into `creature_text` values('3054','1','0','The Water of the Seers is ready for your consumption, $N.', '','12','1','100','0','0','0','Zarlman Two-Moons on Quest 771 finished 2');
replace into `creature_text` values('3142','0','0','We will suffer no demon\'s servant in our lands!', '','12','1','100','0','0','0','Orgnil Soulscar');
replace into `creature_text` values('3301','1','0','My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer.', '','12','0','100','0','0','0','Morgan Ladimore - A Daughter\'s Love');
replace into `creature_text` values('3301','2','0','I shall cling to the love of my daugter and hope that I will find forgiveness under the Light for my sins.', '','12','0','100','0','0','0','Morgan Ladimore - A Daughter\'s Love');
replace into `creature_text` values('3448','0','0','Tonga Runetotem inspects the snapjaw shells...', '','16','1','100','0','0','0','Tonga Runetotem on Quest 880 finished');
replace into `creature_text` values('3448','1','0','Hm...', '','12','1','100','0','0','0','Tonga Runetotem on Quest 880 finished');
replace into `creature_text` values('3448','2','0','Strange. Very strange...', '','12','1','100','0','0','0','Tonga Runetotem on Quest 880 finished');
replace into `creature_text` values('3448','3','0','$N. These shells tell me much, but I fear many more questions are now raised...', '','12','1','100','1','0','0','Tonga Runetotem on Quest 880 finished');
replace into `creature_text` values('3584','0','0','Ok, let\'s go!', '','12','0','100','0','0','0','Therylune');
replace into `creature_text` values('3584','1','0','I can make it the rest of the way, $N. Thanks!', '','12','0','100','0','0','0','Therylune');
replace into `creature_text` values('3616','0','0','Onu studies the parchment from the Twilight Tome...', '','16','7','100','0','0','0','Onu on Quest 950 finished');
replace into `creature_text` values('3616','1','0','Onu is struck by unleashed magic!', '','16','7','100','0','0','0','Onu on Quest 950 finished');
replace into `creature_text` values('3616','2','0','Hmm...', '','12','7','100','0','0','0','Onu on Quest 950 finished');
replace into `creature_text` values('3692','0','0','All right, let\'s go.', '','12','0','100','0','0','0','Volcor');
replace into `creature_text` values('3692','1','0','Oh no! They are here!', '','12','0','100','0','0','0','Volcor');
replace into `creature_text` values('3692','2','0','OK, $N. Now I can get to the Auberdine alone. Go to Terenthis, he\'s waiting for you. Thanks for the help!', '','12','0','100','0','0','0','Volcor');
replace into `creature_text` values('3692','3','0','OK, good luck friend. Thanks for the help.', '','12','0','100','0','0','0','Volcor');
replace into `creature_text` values('3693','0','0','What is happening?', '','12','0','0','0','0','0','Terenthis');
replace into `creature_text` values('3693','1','0','Volcor needs help?', '','12','0','0','0','0','0','Terenthis');
replace into `creature_text` values('3693','2','0','All right, I shall find people to help him.', '','12','0','0','0','0','0','Terenthis');
replace into `creature_text` values('3693','3','0','Hello Grimclaw.', '','12','0','0','0','0','0','Terenthis');
replace into `creature_text` values('3693','4','0','What is happening?', '','12','0','0','0','0','0','Terenthis');
replace into `creature_text` values('3693','5','0','Volcor needs help?', '','12','0','0','0','0','0','Terenthis');
replace into `creature_text` values('3693','6','0','You know where he is?', '','12','0','0','0','0','0','Terenthis');
replace into `creature_text` values('3693','7','0','Well, ok. I am sending people. We will need to find and help him!', '','12','0','0','0','0','0','Terenthis');
replace into `creature_text` values('3695','0','0','Grimclaw growls in your direction before taking time to sniff you.', '','16','0','0','0','0','0','Grimclaw');
replace into `creature_text` values('3817','0','0','%s charges!', '','16','0','100','0','0','0','Shadowhorn Stag');
replace into `creature_text` values('4049','0','0','The spirits of Stonetalon still rage, $N.', '','16','7','100','0','0','0','Seereth Stonebreak on Quest 1062 finished');
replace into `creature_text` values('4049','1','0','I fear we may never soothe them...', '','16','7','100','0','0','0','Seereth Stonebreak on Quest 1062 finished');
replace into `creature_text` values('4351','0','0','%s looks weak enough to capture.', '','16','0','100','0','0','0','Bloodfen Raptor');
replace into `creature_text` values('4352','0','0','%s looks weak enough to capture.', '','16','0','100','0','0','0','Bloodfen Screecher');
replace into `creature_text` values('4980','0','0','W-what do you want? Just leave me alone...', '','12','0','0','0','0','0','Paval');
replace into `creature_text` values('4980','1','0','I swear, I didn\'t steal anything from you! Here, take some of my supplies, just go away!', '','12','0','0','0','0','0','Paval');
replace into `creature_text` values('4980','2','0','I... Well, I may of taken a little thing or two from the inn... but what would an ogre care about that?', '','12','0','0','0','0','0','Paval');
replace into `creature_text` values('4980','3','0','Not one step closer, ogre!', '','12','0','0','0','0','0','Paval');
replace into `creature_text` values('4980','4','0','And I don\'t know anything about this fire of yours...', '','12','0','0','0','0','0','Paval');
replace into `creature_text` values('4980','5','0','What was that? Did you hear something?', '','12','0','0','0','0','0','Paval');
replace into `creature_text` values('4980','6','0','%s staggers back as the arrow lodges itself deeply in his chest.', '','16','0','0','0','0','0','Paval');
replace into `creature_text` values('4980','7','0','Ugh... Hallan, didn\'t think you had it in you...', '','12','0','0','16','0','0','Paval');
replace into `creature_text` values('4980','8','0','Must be your lucky day. Alright, I\'ll talk. Just leave me alone. Look, you\'re not going to believe me, but it wa... oh, Light, looks like the girl could shoot...', '','12','0','0','0','0','0','Paval');
replace into `creature_text` values('5045','0','0','Gladly, sir.', '','12','0','0','0','0','0','Hallan');
replace into `creature_text` values('5046','0','0','Paval Reethe! Found you at last. And consorting with ogres now? No fear, even deserters and traitors are afforded some mercy.', '','12','0','0','0','0','0','Caldwell');
replace into `creature_text` values('5046','1','0','Private, show Lieutenant Reethe some mercy.', '','12','0','0','0','0','0','Caldwell');
replace into `creature_text` values('5046','2','0','Now, let\'s clean up the rest of the trash, men!', '','12','0','0','0','0','0','Caldwell');
replace into `creature_text` values('5888','0','0','Peace and patience be with you, $N. Remain strong always.', '','12','1','100','0','0','0','Seer Ravenfeather');
replace into `creature_text` values('5901','0','0','Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?', '','42','0','100','1','0','0','Islen Waterseer');
replace into `creature_text` values('5901','1','0','Thank you great spirit. Thank you!', '','12','0','100','1','0','0','Islen Waterseer');
replace into `creature_text` values('6119','0','0','Horrible! Well, all right,maybe it just needs a little cleaning up?', '','12','0','100','0','0','0','Tog Rustsprocket reply');
replace into `creature_text` values('6176','0','0','Follow me, $N. I will soon begin the summoning.', '','12','0','100','0','0','0','Bath\'rah the Windwatcher');
replace into `creature_text` values('6176','1','0','%s begins a spell of summoning...', '','41','0','100','0','0','0','Bath\'rah the Windwatcher');
replace into `creature_text` values('6546','0','0','Grid yourself, $N. The demon in this orb is a fel beast.', '','12','0','100','0','0','0','Tabetha');
replace into `creature_text` values('7207','0','0','That\'s interesting...', '','12','0','100','0','0','0','Doc Mixilpixil');
replace into `creature_text` values('7207','1','0','I need to consult Noram and Horatio.', '','12','0','100','0','0','0','Doc Mixilpixil');
replace into `creature_text` values('7664','0','0','Ilifar, your master calls!', '','14','0','100','0','0','0','Razelikh the Defiler');
replace into `creature_text` values('7664','1','0','Let the flames of chaos engulf you!', '','14','0','100','0','0','0','Razelikh the Defiler');
replace into `creature_text` values('7664','2','0','Face my champion, mortals!', '','14','0','100','0','0','0','Razelikh the Defiler');
replace into `creature_text` values('7664','3','0','Prepare yourselves for an eternity of anguish and torture - vengeance shall be mine...', '','14','0','100','0','0','0','Razelikh the Defiler');
replace into `creature_text` values('7804','0','0','Hear ye, denizens of Tanaris! Let it be known $N is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $N!', '','14','0','100','0','0','0','Trenton Lighthammer');
replace into `creature_text` values('8256','0','0','Poor Dorius. If I ever get my hands on those Dark Irons, so help me...', '','12','0','100','0','0','0','Curator Thorius');
replace into `creature_text` values('8297','0','0','%s goes into a frenzy!', '','16','0','100','0','0','0','Magronos the Unyielding');
replace into `creature_text` values('8538','0','0','%s lets out a high pitched screech, calling for help!', '','16','0','100','0','0','0','Unseen Servant - Call for help Say');
replace into `creature_text` values('8539','0','0','%s lets out a high pitched screech, calling for help!', '','16','0','100','0','0','0','Eyeless Watcher - Call for help Say');
replace into `creature_text` values('9117','0','0','This makes sense!', '','12','0','100','0','0','0','J.D. Collie');
replace into `creature_text` values('9316','0','0','Ok, let\'s get started!', '','12','0','100','1','0','0','Wenikee Boltbucket');
replace into `creature_text` values('9316','1','0','... oops.', '','12','0','100','1','0','0','Wenikee Boltbucket');
replace into `creature_text` values('9546','0','0','Oh man, I thought I was dead for sure. Ugh... still dizzy...', '','12','0','100','0','0','0','Raschal the Courier');
replace into `creature_text` values('9546','1','0','I can get back to the Stronghold on my own, I think. Now that you bought me some time, I should be able to stealth out of here. Who ever you are... thank you. May Elune bless you always!', '','12','0','100','0','0','0','Raschal the Courier');
replace into `creature_text` values('10799','0','0','%s cries.', '','16','0','100','0','0','0','Warosh');
replace into `creature_text` values('10799','0','1','%s snorts.', '','16','0','100','0','0','0','Warosh');
replace into `creature_text` values('10799','0','2','%s grumbles.', '','16','0','100','0','0','0','Warosh');
replace into `creature_text` values('10940','0','0','Leave this place!', '','12','0','100','0','0','0','Ghost of the Past');
replace into `creature_text` values('11339','0','0','Killing you be easy!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11339','0','1','Troll mojo da strongest mojo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11339','0','2','Your skull gonna decorate our ritual altars!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11339','0','3','I gonna make you into mojo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11339','0','4','Feel da big bad voodoo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11339','0','5','My weapon be thirsty!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11339','0','6','You be dead soon!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11355','0','0','%s becomes enraged!', '','16','0','100','0','0','0','Gurubashi Warrior - At 30% HP - Say Line 0');
replace into `creature_text` values('11356','0','0','Killing you be easy!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11356','0','1','Troll mojo da strongest mojo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11356','0','2','Your skull gonna decorate our ritual altars!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11356','0','3','I gonna make you into mojo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11356','0','4','Feel da big bad voodoo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11356','0','5','My weapon be thirsty!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11356','0','6','You be dead soon!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11359','0','0','%s goes into a frenzy!', '','16','0','100','0','0','0','Soulflayer - At 30% HP - Say Line 0');
replace into `creature_text` values('11831','0','0','Killing you be easy!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11831','0','1','Troll mojo da strongest mojo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11831','0','2','Your skull gonna decorate our ritual altars!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11831','0','3','I gonna make you into mojo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11831','0','4','Feel da big bad voodoo!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11831','0','5','My weapon be thirsty!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('11831','0','6','You be dead soon!', '','12','0','100','0','0','0','Part of the ZulGurub on aggro lines');
replace into `creature_text` values('13602','0','0','ARRRRRRR!', '','14','0','100','0','0','0','The Abominable Greench');
replace into `creature_text` values('14368','0','0','I very much doubt that he will have anything to say, stranger...', '','12','0','100','1','0','0','Lorekeeper Lydros');
replace into `creature_text` values('14368','1','0','I personally did not mind him. It was the Prince who took exception to a high elf in his domain. Alas, I am not one to question the Prince. In his defense, he did not incinerate Master Winthalus immediately.', '','12','0','100','1','0','0','Lorekeeper Lydros');
replace into `creature_text` values('14368','2','0','We most definitely do not need anymore attention drawn to us, stranger. Return to those that sent you in search of the lost master and tell them that nothing could be found. When this is done - and I will know when it is so - return and I shall reveal the secrets of the deceased.', '','12','0','100','1','0','0','Lorekeeper Lydros');
replace into `creature_text` values('14821','0','0','%s becomes enraged!', '','16','0','100','0','0','0','Razzashi Raptor - At 30% HP - Say Line 0');
replace into `creature_text` values('14823','0','0','Everyone enjoying themselves so far?  That\'s great!  Welcome to the Darkmoon Faire, the greatest show on all of Azeroth!  Make sure that you speak with Yebb and his friends here while you\'re taking in Neblegear\'s Darkmoon Zoo Bizarre.', '','12','0','100','0','0','0','Silas Darkmoon');
replace into `creature_text` values('14823','0','1','We\'re back and better than ever!  It\'s the Darkmoon Faire friend, and it\'s your lucky day! Sparing no expense, we\'ve gathered wonders and treats from around the world for your delight.  Whether you\'re young or old, rich or poor, the Darkmoon Faire has it all!  Be sure to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate, and choose from several exotic and wondrous prizes!', '','12','0','100','0','0','0','Silas Darkmoon');
replace into `creature_text` values('14823','0','2','Come one, come all.  Welcome to the Darkmoon Faire!  Don\'t be shy.  Step right up to Lhara and buy yourself an exotic artifact from far off lands.  If you\'re one of the lucky few who have found Darkmoon Cards, have a word with Professor Paleo.  Hungry?  Thirsty?  You\'re in luck!  Refreshments are available right here from Sylannia and Stamp.  I recommend the Darkmoon Special Reserve to wash down some Red Hot Wings.  And if the future is what you seek, then run, don\'t walk, to speak with Sayge.', '','12','0','100','0','0','0','Silas Darkmoon');
replace into `creature_text` values('14823','0','3','Welcome one and all to the Darkmoon Faire, the greatest event in all the world!  We have it all... delicious food, strong drink, exotic artifacts, fortunes read, amazing prizes and excitement without end!  Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate!  All it takes is five or more and you\'re on your way to the most wondrous prizes on all of Azeroth.  Everybody is a winner!', '','12','0','100','0','0','0','Silas Darkmoon');
replace into `creature_text` values('15371','0','0','Move along, $C.', '','12','0','100','66','0','0','Sunstrider Guardian');
replace into `creature_text` values('15371','0','1','Off with you, $N.', '','12','0','100','66','0','0','Sunstrider Guardian');
replace into `creature_text` values('15371','1','0','Do not push it citizen!', '','12','0','100','1','0','0','Sunstrider Guardian');
replace into `creature_text` values('15481','0','0','I SAID GOOD BYE!', '','12','0','100','1','0','0','Spirit of Azuregos');
replace into `creature_text` values('16206','0','0','Th... thank you.  I thought I was going to die.', '','12','0','100','0','0','0','Apprentice Varnis');
replace into `creature_text` values('16208','0','0','Thanks, I should\'ve never left Silverpine Forest.', '','12','0','100','6','0','0','Apothecary Enith');
replace into `creature_text` values('16209','0','0','You have my thanks!', '','12','0','100','0','0','0','Ranger Vedoran');
replace into `creature_text` values('16227','0','0','Guards!', '','14','1','100','0','0','0','Skymistress Gloaming');
replace into `creature_text` values('16263','0','0','I don\'t see why we ally with filthy stinking trolls? The only good troll is a dead troll.', '','12','0','100','1','0','0','Paelarin');
replace into `creature_text` values('16263','0','1','Does anyone need any supplies to down the trolls? Any troll will do.', '','12','0','100','1','0','0','Paelarin');
replace into `creature_text` values('16325','0','0','%s shimmers and becomes intangible.', '','16','0','100','0','0','0','Quel\'dorei Ghost');
replace into `creature_text` values('16326','0','0','%s shimmers and becomes intangible.', '','16','0','100','0','0','0','Quel\'dorei Wraith');
replace into `creature_text` values('16550','0','0','By the seven Ata\'mal crystals!  Others have survived the crash!  Zhanaa, is that you?  It is so good to see you again!', '','12','0','100','0','0','0','Image of Technician Dyvuun');
replace into `creature_text` values('16550','1','0','And who do we have here?  No doubt th... crzzzk ...ade this communication possible?  I give you greetings fro... psshzzzk... Azure Watch.', '','12','0','100','0','0','0','Image of Technician Dyvuun');
replace into `creature_text` values('16550','2','0','Judging by your signal, we put you... ust southeast of the larger part of the island we crashed onto.  Cross the Crystalbrook River to ge... kshhhhk zzzt. Sorry, there\'s a lot of stat...', '','12','0','100','0','0','0','Image of Technician Dyvuun');
replace into `creature_text` values('16577','0','0','Brothers and sisters, I have been to the promised land. I have tasted in the sublime energy. I have felt bliss - bliss so engrossing and all encompassing that I was left wondering if I had stumbled upon the dreams of gods.', '','12','0','100','5','0','0','Martik Tor\'seldoi');
replace into `creature_text` values('16577','1','0','In paradise, you merely reach out and take from the Nether.', '','12','0','100','1','0','0','Martik Tor\'seldoi');
replace into `creature_text` values('16577','2','0','From the very air! Tendrils of arcane energy light up the obsidian sky as plumes of raw magic rise up from fissures in the land. Kneel and drink from the fissure as you do from a stream or well. Pluck a tendril from the heavens as if it were an apple hanging from a branch.', '','12','0','100','5','0','0','Martik Tor\'seldoi');
replace into `creature_text` values('17071','0','0','This is great news!  Your efforts have indeed saved us, $N!', '','12','0','100','0','0','0','Technician Zhanaa');
replace into `creature_text` values('17073','0','0','<Sobbing> I hate graveyards. So many dead. And my sweet Luhanaa.....', '','12','0','100','1','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','1','It should have been me!', '','12','0','100','1','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','2','Be at peace, my sweet, sweet, Luhanaa.', '','12','0','100','1','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','3','I\'ll never forget you, my love.', '','12','0','100','1','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','4','If I ever find the ones responsible for the crash...!', '','12','0','100','1','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','5','We should never have come along.', '','12','0','100','1','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','6','Why, Luhanaa? Why?', '','12','0','100','6','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','7','I miss you so much!', '','12','0','100','1','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','8','You\'ll always be here, with me.', '','12','0','100','1','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','9','Draenei Mourner weeps softly.', '','16','0','100','18','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','10','Draenei Mourner bows his head and sighs, clearly exhausted.', '','16','0','100','2','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','11','Draenei Mourner breaks down into huge, wracking sobs.', '','16','0','100','18','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17073','0','12','Draenei Mourner stares in silence at the graver marker before him.', '','16','0','100','0','0','0','Draenei Mourner - Random Say');
replace into `creature_text` values('17119','0','0','I think I can make it to Brackenwall on my own. They\'ve got the cargo at the top of the tower. Be careful!', '','12','0','0','0','0','0','Ithania - Escape');
replace into `creature_text` values('17226','0','0','Ok, let\'s go. I know just the perfect spot!', '','12','0','100','0','0','0','Viera Sunwhisper');
replace into `creature_text` values('17226','1','0','I can\'t wait to try this wine!', '','12','0','100','0','0','0','Viera Sunwhisper');
replace into `creature_text` values('17226','2','0','What... is happening... to me? Get this cat away from me!', '','12','0','100','0','0','0','Viera Sunwhisper');
replace into `creature_text` values('17226','3','0','%s scurries away, attempting to flee from Twinkle', '','16','0','100','0','0','0','Viera Sunwhisper');
replace into `creature_text` values('17230','0','0','%s looks at Viera Sunwhisper with very hungry eyes', '','16','0','100','0','0','0','Twinkle');
replace into `creature_text` values('17379','0','0','%s urges you to follow him.', '','16','0','100','0','0','0','Stillpine Ancestor Akida');
replace into `creature_text` values('17379','1','0','%s points to the totem of Coo.', '','16','0','100','25','0','0','Stillpine Ancestor Akida');
replace into `creature_text` values('17391','0','0','%s motions for you to follow him.', '','16','0','100','0','0','0','Stillpine Ancestor Coo');
replace into `creature_text` values('17391','1','0','[Furbolg] Ritk kin\'chikx azul azure summit...', '','12','0','100','0','0','0','Stillpine Ancestor Coo');
replace into `creature_text` values('17391','2','0','[Furbolg] Coo xip fly... Jump ilos river. Find Tikti.', '','12','0','100','0','0','0','Stillpine Ancestor Coo');
replace into `creature_text` values('17392','0','0','%s asks you to follow him.', '','16','0','100','0','0','0','Stillpine Ancestor Tikti');
replace into `creature_text` values('17392','1','0','[Furbolg] Far you mixik tak come. Gaze upon the kitch\'kal river. Follow. Ilog to Yor.', '','12','0','100','0','0','0','Stillpine Ancestor Tikti');
replace into `creature_text` values('17392','2','0','[Furbolg] Go... Search yitix\'kil bottom river. South!', '','12','0','100','0','0','0','Stillpine Ancestor Tikti');
replace into `creature_text` values('17410','0','0','[Furbolg] Bear witness to the savage acts of our adversaries, $N. They steal our young... our weak... Imprisoned here, they are left to the devices of the Bristlelimb. Set them free, Promised One!', '','12','0','100','0','0','0','Stillpine Ancestor Vark');
replace into `creature_text` values('18069','0','0','%s goes into a frenzy!', '','16','0','100','0','0','0','Mogor');
replace into `creature_text` values('18069','1','0','Dat was poop! Mogor could put up much better fight den dat!', '','14','0','100','0','0','0','Mogor');
replace into `creature_text` values('18069','2','0','Mogor not impressed! Skra\'gath wuz made of da air and shadow! Soft like da squishy orcies!', '','14','0','100','0','0','0','Mogor');
replace into `creature_text` values('18069','3','0','Now you face da true champion! I give you chance to run away little one. Run away now before Mogor decim... destyor... Run away before Mogor KILL!', '','14','0','100','0','0','0','Mogor');
replace into `creature_text` values('18069','4','0','No more chances! Now you pay da ogre!', '','14','0','100','15','0','0','Mogor');
replace into `creature_text` values('18069','5','0','No more nice ogre! You hurt Mogor!', '','14','0','100','0','0','0','Mogor');
replace into `creature_text` values('18069','6','0','WUT!? UNPOSSIBLE!! You fight Mogor now! Mogor destroy!', '','14','0','100','0','0','0','Mogor');
replace into `creature_text` values('18103','0','0','Obey the laws of Silvermoon. Failure to do so will result in termination.', '','12','1','100','0','0','0','Arcane Guardian');
replace into `creature_text` values('18103','0','1','Maintain order within these walls.', '','12','0','100','0','0','0','Arcane Guardian');
replace into `creature_text` values('18146','0','0','Champion Vranesh inclines his head slightly to the pair of guardians in greeting.', '','16','1','100','0','0','0','Champion Vranesh');
replace into `creature_text` values('18146','1','0','Champion Vranesh arches a scrulpled brow at the guards. a disapproving scowl on his face', '','16','1','100','0','0','0','Champion Vranesh');
replace into `creature_text` values('18146','2','0','Champion Vranesh glances from guard to guard.', '','16','1','100','0','0','0','Champion Vranesh');
replace into `creature_text` values('18146','3','0','Champion Vranesh surveys the small ranger practice ground with a condescending smirk.', '','16','1','100','0','0','0','Champion Vranesh');
replace into `creature_text` values('18399','0','0','Blue brothers reign supreme!', '','12','0','100','0','0','0','Murkblood Twin');
replace into `creature_text` values('18400','0','0','ROKDAR SMASH PUNY %t!', '','14','0','100','0','0','0','Rokdar the Sundered Lord');
replace into `creature_text` values('18401','0','0','Closer... Come closer... See what the void brings!', '','14','0','100','0','0','0','Skra\'gath');
replace into `creature_text` values('18402','0','0','Piece by piece I will tear this challenger apart... PIECE BY PIECE!', '','14','0','100','0','0','0','Warmaul Champion');
replace into `creature_text` values('18447','0','0','The threat be over! $N be savin\' us all!', '','12','0','100','1','0','0','Toki');
replace into `creature_text` values('18471','0','0','Get in the Ring of Blood, $N. The fight is about to start!', '','12','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','1','0','The battle is about to begin! $N versus the ferocious clefthoof, Brokentoe!', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','2','0','$N has defeated Brokentoe!', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','3','0','The battle is about to begin! The unmerciful Murkblood twins versus $N!', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','4','0','Unbelievable! $N has defeated the Murkblood Twins!', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','5','0','Hailing from the mountains of Blade\'s Edge comes Rokdar the Sundered Lord! $N is in for the fight of $g his:her; life.', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','6','0','$N is victorious once more!', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','7','0','From parts unkown: Skra\'gath! Can $N possibly survive the onslaught of void energies?', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','8','0','$N is victorious once more!', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','9','0','This is the moment we\'ve all been waiting for! The Warmaul champion is about to make $g his:her; first showing at the Ring of Blood in weeks! Will $N go down in defeat as easily as the champion\'s other opponents? We shall see...', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','10','0','$N is victorious once more!', '','14','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18471','11','0','Mogor has challenged you. You have to accept! Get in the ring if you are ready to fight.', '','12','0','100','0','0','0','Gurgthock');
replace into `creature_text` values('18929','0','0','Ooh what a dreadful job! All day, surrounded by the stench of bad feet.', '','12','0','100','1','0','0','Kyrenna');
replace into `creature_text` values('18929','0','1','Why couldn\'t mother have chosen something else to dedicate herself to? Cakes, pastries, even bread - anything but cheese!', '','12','0','100','1','0','0','Kyrenna');
replace into `creature_text` values('18929','0','2','If only I had some wine to go with my cheese...', '','12','0','100','18','0','0','Kyrenna');
replace into `creature_text` values('18999','0','0','Hey, did you read the bounty on this wanted poster?', '','12','7','100','6','0','0','Allerian Defender');
replace into `creature_text` values('18999','0','1','The Bone Wastes! I don\'t care what\'s being offered as a reward, I\'m not going into the Bone Wastes!', '','12','7','100','6','0','0','Allerian Defender');
replace into `creature_text` values('18999','0','2','This wanted poster says that they\'re offering gold to these so-called adventurers to go kill things. Isn\'t that what we do? I don\'t think I\'m being paid enough!', '','12','7','100','6','0','0','Allerian Defender');
replace into `creature_text` values('18999','0','3','You want to go do the bounty off of this wanted poster after the shift is over?', '','12','7','100','6','0','0','Allerian Defender');
replace into `creature_text` values('18999','0','4','This poster has a bounty on bonelashers. You think I should do that?', '','12','7','100','6','0','0','Allerian Defender');
replace into `creature_text` values('18999','1','0','Is that wanted poster all that you\'re going to talk about today?', '','12','7','100','1','0','0','Allerian Defender');
replace into `creature_text` values('18999','1','1','I\'m up to looking into that bounty after this shift.', '','12','7','100','1','0','0','Allerian Defender');
replace into `creature_text` values('18999','1','2','I could use the extra money.', '','12','7','100','1','0','0','Allerian Defender');
replace into `creature_text` values('18999','1','3','I don\'t know and I don\'t care.', '','12','7','100','1','0','0','Allerian Defender');
replace into `creature_text` values('18999','1','4','The bonelashers of the wastes are no laughing matter. I hear they carry diseases!', '','12','7','100','1','0','0','Allerian Defender');
replace into `creature_text` values('19035','0','0','Oh sweet, delicious, spotted eggs - you will be mine...', '','12','0','100','0','0','0','Wazat');
replace into `creature_text` values('19035','1','1','If only I could get this blasted machine working!', '','12','0','100','0','0','0','Wazat');
replace into `creature_text` values('19035','2','2','They look so delicious...', '','12','0','100','0','0','0','Wazat');
replace into `creature_text` values('19055','0','0','Emote blabla', '','16','0','100','0','0','0','Windroc Matriarch');
replace into `creature_text` values('19533','0','0','A tradesman, perhaps? You need look no further than I for supplies. My prices are quite fair, friend. These items were difficult to acquire, but what does the source matter, eh? You\'ll have what you need.', '','12','0','100','1','0','0','Dealer Aljaan');
replace into `creature_text` values('19546','0','0','I can\'t sleep without a good bedtime story. Now I\'m certain to rest well.', '','12','0','100','1','0','0','Belmara gratitude');
replace into `creature_text` values('19579','0','0','Phew! There\'s my lucky hat. I\'ve been looking for it everywhere.', '','12','0','100','1','0','0','Frostweaver gratitude');
replace into `creature_text` values('19580','0','0','I can\'t possibly go out without my cloak. I hope it\'s in here...', '','12','0','100','1','0','0','Luminrath gratitude');
replace into `creature_text` values('19580','1','0','There it is! I could\'ve sworn it wasn\'t here last time I checked...', '','12','0','100','1','0','0','Luminrath gratitude');
replace into `creature_text` values('20098','0','0','I\'m right here, daddy. You\'ve been asleep all day long. You sure must be tired!', '','12','0','100','1','0','0','Jane');
replace into `creature_text` values('20100','0','0','Was... Was it all a dream? Azuremyst, Bloodymyst, Zangarmarsh, Shadowmoon... even Zul\'Aman... Jane! Jane where are you!', '','12','0','100','1','0','0','Jessel');
replace into `creature_text` values('20100','1','0','Ah, wonderful. It was all just a dream...', '','12','0','100','1','0','0','Jessel');
replace into `creature_text` values('20242','0','0','The best selection of smuggled goods is available right here, $N.  Great for the whole family!  Avoid goblin taxation and naaru prohibition - the Consortium is here to fill your every shopping need!', '','12','0','100','1','0','0','Karaaz');
replace into `creature_text` values('20774','0','0','%s goes into a frenzy!', '','16','0','100','0','0','0','Farahlon Lasher');
replace into `creature_text` values('21291','0','0','I\'m through asking nicely, fish-man.', '','12','0','100','25','0','0','Grom\'tor, Son of Oronok');
replace into `creature_text` values('21291','1','0','Where is the Cipher of Damnation? I know a third of it is in this village.', '','12','0','100','6','0','0','Grom\'tor, Son of Oronok');
replace into `creature_text` values('21291','2','0','No... Of course not. What was I thinking? Why would you have a third of the Cipher of Damnation?', '','12','0','100','274','0','0','Grom\'tor, Son of Oronok');
replace into `creature_text` values('21291','3','0','I feel so stupid. Maybe I should unchain you and set you free?', '','12','0','100','11','0','0','Grom\'tor, Son of Oronok');
replace into `creature_text` values('21291','4','0','DO I HONESTLY LOOK THAT STUPID TO YOU, NAGA? NOW YOU FEEL PAIN!', '','12','0','100','5','0','0','Grom\'tor, Son of Oronok');
replace into `creature_text` values('21291','5','0','%s spits on the Coilskar naga.', '','16','0','100','5','0','0','Grom\'tor, Son of Oronok');
replace into `creature_text` values('21291','6','0','GET UP YOU ROTTEN PIECE OF TRASH! GET UP BEFORE I END YOU!', '','12','0','100','5','0','0','Grom\'tor, Son of Oronok');
replace into `creature_text` values('21291','7','0','I\'m listening...', '','12','0','100','273','0','0','Grom\'tor, Son of Oronok');
replace into `creature_text` values('21293','0','0','Hide! Hide before they see you! Back up!', '','15','0','100','0','0','0','Borak');
replace into `creature_text` values('21293','1','0','The time to strike is at hand. Terminate Icarius.', '','15','0','100','0','0','0','Borak');
replace into `creature_text` values('21293','2','0','You have it. Do not lose it again!', '','12','0','100','5','0','0','Borak');
replace into `creature_text` values('21295','0','0','Whhaaat... are you sssspeaking of, ssssoft-sskin?', '','12','0','100','1','0','0','Coilskar Commander');
replace into `creature_text` values('21295','1','0','The naga do nottt... have thissss... cipherrr...', '','12','0','100','1','0','0','Coilskar Commander');
replace into `creature_text` values('21295','2','0','Yesss... Yesss... Ssset me freee...', '','12','0','100','1','0','0','Coilskar Commander');
replace into `creature_text` values('21295','3','0','%s regains consciousness.', '','16','0','100','0','0','0','Coilskar Commander');
replace into `creature_text` values('21295','4','0','Do not beat the Coilsssskaarrr commander anymore, orc! I will tell you! The cipherrr... It is hidden in one of the chests at Coilssskarrr Point... The naga there hold the keysss...', '','12','0','100','1','0','0','Coilskar Commander');
replace into `creature_text` values('21295','5','0','COILSSSKARRR!', '','12','0','100','15','0','0','Coilskar Commander');
replace into `creature_text` values('21409','0','0','Halt!', '','12','0','100','1','0','0','Icarius');
replace into `creature_text` values('21409','1','0','Zarath you must return to the Black Temple at once! I... I seem to have misplaced Lord Illidan\'s orders. Quickly!', '','12','0','100','5','0','0','Icarius');
replace into `creature_text` values('21409','2','0','Zarath, I am perfectly capable of making it up this road to Eclipse Point. If we do not deliver the missive, Lord Illidan will have both of our heads! You are dismissed!', '','12','0','100','1','0','0','Icarius');
replace into `creature_text` values('21409','3','0','Ah, sweet, sweet bloodthistle... Probably left behind by one of those filthy addicts at Eclipse Point.', '','12','0','100','1','0','0','Icarius');
replace into `creature_text` values('21409','4','0','Their loss is most definitely my gain...', '','12','0','100','275','0','0','Icarius');
replace into `creature_text` values('21409','5','0','Envoy Icarius puts the bundle of bloodthistle in his robe.', '','16','0','100','0','0','0','Icarius');
replace into `creature_text` values('21409','6','0','Ah, damn it all! Clever trap. Too bad you\'ll never live to tell the tale...', '','12','0','100','1','0','0','Icarius');
replace into `creature_text` values('21410','0','0','What is it, my lord?', '','12','0','100','6','0','0','Zarath');
replace into `creature_text` values('21410','1','0','My lord, surely you do not expect me to leave you unattended. Lord Illidan would have my head if anything were to happen to you.', '','12','0','100','1','0','0','Zarath');
replace into `creature_text` values('21410','2','0','As you wish, my lord.', '','12','0','100','66','0','0','Zarath');
replace into `creature_text` values('21502','0','0','Doom Lord Kazzak will be pleased. You are to increase the pace of your attacks. Destroy the orcish and dwarven strongholds with all haste.', '','12','0','100','1','0','0','Razuun');
replace into `creature_text` values('21502','1','0','Don\'t worry about that. I\'ve increased production at the Deathforge. You\'ll have all the infernals you need to carry out your orders. Don\'t fail, Jovaan.', '','12','0','100','1','0','0','Razuun');
replace into `creature_text` values('21502','2','0','Yes?', '','12','0','100','6','0','0','Razuun');
replace into `creature_text` values('21502','3','0','Crate? I didn\'t send you a crate, Jovaan. Don\'t you have more important things to worry about? Go see to them!', '','12','0','100','274','0','0','Razuun');
replace into `creature_text` values('21797','0','0','Your body is mine! Our fates are forever intertwined!', '','14','0','100','0','0','0','Ancient Shadowmoon Spirit');
replace into `creature_text` values('22127','0','0','It\'s a good thing I was able to make duplicates of the Felsworn Gas Mask.', '','12','0','100','1','0','0','Wildlord Antelarion');
replace into `creature_text` values('22373','0','0','More Minions of Terokk are coming!', '','12','0','100','0','0','0','Defender Grashna');
replace into `creature_text` values('22373','1','0','The invaders persist! Hold them off!', '','12','0','100','0','0','0','Defender Grashna');
replace into `creature_text` values('22373','2','0','An Avatar of Terokk!! To arms!', '','12','0','100','0','0','0','Defender Grashna');
replace into `creature_text` values('22373','3','0','The Avatar of Terokk has been defeated! Death to Terokk! Death to Skettis!', '','12','0','100','0','0','0','Defender Grashna');
replace into `creature_text` values('22924','0','0','It would\'ve taken years to find the Book of the Raven without you, young sparrowhawk. Return to your home in Nagrand with our gratitude.', '','12','0','100','1','0','0','Arthorn Windsong');
replace into `creature_text` values('22924','1','0','This is it! This is really it -- the Book of the Raven!', '','12','0','100','1','0','0','Arthorn Windsong');
replace into `creature_text` values('22924','2','0','There\'s something else here, too. After a discription of a bloody battle and the downfall of the raven, there\'s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...', '','12','0','100','1','0','0','Arthorn Windsong');
replace into `creature_text` values('22924','3','0','It\'s all here... how the raven\'s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god\'s name -- Anzu. I\'d thought it was lost to history!', '','12','0','100','1','0','0','Arthorn Windsong');
replace into `creature_text` values('22924','4','0','The tablet has the confirmation we need, just as I thought. Now, we have to use this information to draw out and defeat this Anzu before he can do any more damage to the Emerald Dream!', '','12','0','100','1','0','0','Arthorn Windsong');
replace into `creature_text` values('22924','5','0','Since the sparrowhawks have proven such a success in hunting down the raven stones, Watcher Elaira has trained another one to relay my voice at a great distance. He can help us communicate as you investigate the bird spirits revealed in the tablet!', '','12','0','100','1','0','0','Arthorn Windsong');
replace into `creature_text` values('23567','0','0','Mysterious hoofprints, scorched shields, stray badges... how do we make sense of all this?', '','12','0','100','6','0','0','Inspector Tarem');
replace into `creature_text` values('23573','0','0','I don\'t think Drazzit\'s going to have any luck finding anyone to kill this raptor. I mean, he\'s already raised the reward twice...', '','12','0','100','1','0','0','Krixil Slogswitch');
replace into `creature_text` values('23685','0','0','YOU WANT DRINK? WE GOT DRINK!', '','14','0','100','0','0','0','Gordok Brew Barker');
replace into `creature_text` values('23685','0','1','HEY YOU! DRINK OGRE BREWS! MAKE YOU BIG AND STRONG!', '','14','0','100','0','0','0','Gordok Brew Barker');
replace into `creature_text` values('23685','0','2','YOU TRY DA\' BEST, NOW TRY DA\' REST! OGRE BREW!!', '','14','0','100','0','0','0','Gordok Brew Barker');
replace into `creature_text` values('23768','1','0','James? James... No, you\'re not James, but I know who you are...', '','12','0','100','0','0','0','Lynn Hyal');
replace into `creature_text` values('23768','2','0','You\'re the one who tracked down the brutes who did this to us.', '','12','0','100','0','0','0','Lynn Hyal');
replace into `creature_text` values('23768','3','0','I tried so hard to tell Jim... to tell anyone... who was behind this, but I couldn\'t find a way...', '','12','0','100','0','0','0','Lynn Hyal');
replace into `creature_text` values('23768','4','0','Thank you for helping us and for helping Jim. If you see him, tell him little Jimmy and I love him and that we\'re waiting for him.', '','12','0','100','0','0','0','Lynn Hyal');
replace into `creature_text` values('23768','5','0','I don\'t know when we\'ll see Daddy again, Jimmy, but I know he loves you and he misses you very much.', '','12','0','100','0','0','0','Lynn Hyal');
replace into `creature_text` values('23769','1','0','Mommy, when will we see Daddy again?', '','12','0','100','0','0','0','Jimmy Hyal');
replace into `creature_text` values('23905','0','0','Keep Moving!', '','14','7','100','0','0','0','Major Mills');
replace into `creature_text` values('23995','0','0','I thought we talked about this, Brogg. You can\'t stay in this building. Sure, it can house you, but there\'s no room for anyone else!', '','12','0','100','1','0','0','Axle');
replace into `creature_text` values('23995','1','0','Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here!', '','12','0','100','1','0','0','Axle');
replace into `creature_text` values('23995','2','0','I\'m inclined to say they made ogres too big! I can see I\'m not going to convince you to move now, but don\'t think this is permanent!', '','12','0','100','1','0','0','Axle');
replace into `creature_text` values('24405','0','0','Thank you!', '','12','0','100','17','0','0','Adarrah');
replace into `creature_text` values('24710','0','0','Right! Let\'s try this so-called dire brew...', '','12','0','100','0','0','0','Ipfelkofer Ironkeg');
replace into `creature_text` values('24710','1','0','Bronzebeard\'s beard! What a drink!', '','12','0','100','0','0','0','Ipfelkofer Ironkeg');
replace into `creature_text` values('24710','2','0','$N, this beer... well, it might be the best of Brewfest!', '','12','0','100','15','0','0','Ipfelkofer Ironkeg');
replace into `creature_text` values('24710','3','0','It is a shame Coren\'s Dire Brew can\'t quench more thirsting throats! It\'s blasphemy, I know, but I envy those Dark Iron dwarves!', '','12','0','100','274','0','0','Ipfelkofer Ironkeg');
replace into `creature_text` values('24710','4','0','Ho there, and welcome to Brewfest!', '','12','7','100','3','0','0','Ipfelkofer Ironkeg');
replace into `creature_text` values('24710','4','1','Hello, friend! Welcome to the Brewfest Grounds!', '','12','7','100','3','0','0','Ipfelkofer Ironkeg');
replace into `creature_text` values('24710','4','2','Hail, good $c! Welcome to Ironforge\'s annual Brewfest celebration!', '','12','7','100','3','0','0','Ipfelkofer Ironkeg');
replace into `creature_text` values('24711','0','0','Well time\'s money, and time\'s wasting! Let\'s have that drink...', '','12','0','100','1','0','0','Tapper Swindlekeg');
replace into `creature_text` values('24711','1','0','Wow! This really greases the steamplugs!', '','12','0','100','1','0','0','Tapper Swindlekeg');
replace into `creature_text` values('24711','2','0','If I were an honest goblin, I\'d say this was the best beer of the festival...', '','12','0','100','1','0','0','Tapper Swindlekeg');
replace into `creature_text` values('24711','3','0','Too bad Coren\'s dead. If I could buy that brew from him and resell it - watered down and rebottled under my own label, of course - I\'d be rich!', '','12','0','100','1','0','0','Tapper Swindlekeg');
replace into `creature_text` values('24711','4','0','Hey there, and welcome to Brewfest. Come in and have a drink or three!', '','12','1','100','3','0','0','Tapper Swindlekeg');
replace into `creature_text` values('24711','4','1','What\'s up, friend? Welcome to the Brewfest Grounds! Now go buy some drinks!', '','12','1','100','3','0','0','Tapper Swindlekeg');
replace into `creature_text` values('24711','4','2','Hey hey, it\'s another $r! Welcome to my annual Brewfest celebration... now go feast and drink some!', '','12','1','100','3','0','0','Tapper Swindlekeg');
