UPDATE creature_template SET faction_A = 14, faction_B = 14 WHERE entry = 25735;

REPLACE INTO npc_text (ID,text0_0) VALUES (25319,"Anveena's sacrifice gave us a new hope.");
REPLACE INTO locales_npc_text(entry,Text0_0_loc2) VALUES (25319,"Le sacrifice d\'Anveena nous a donné à tous un nouvel espoir pour l\'avenir.");

replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','8','0','%s begins to channel dark energy.','%s commence à canaliser des énergies noires.','3','0','100','0','0','0','KJ - EMOTE_KJ_DARKNESS');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','3','0','The expendible have perished... So be it! Now I shall succeed where Sargeras could not! I will bleed this wretched world and secure my place as the true master of the Burning Legion. The end has come! Let the unraveling of this world commence!','Les troupes sacrifiables ont péries... tant pis. Je vais réussir où Sargeras avait échoué, je vais saigner ce misérable monde et assurer ma place de véritable maître de la Légion Ardente ! La fin est venue ! Que la dissolution du monde commence !','1','0','100','0','0','12500','KJ - SAY_KJ_EMERGE');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','1','0','Another step towards destruction!','Un autre pas vers la destruction !','1','0','100','0','0','12501','KJ - SAY_KJ_SLAY1');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','1','1','Anak-ky\'ri!','Anak-ky\'ri!','1','0','100','0','0','12502','KJ - SAY_KJ_SLAY2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','2','0','Who can you trust?','En qui avoir confiance ?','1','0','100','0','0','12503','KJ - SAY_KJ_REFLECTION1');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','2','1','The enemy is among you.','L\'ennemi est parmi vous...','1','0','100','0','0','12504','KJ - SAY_KJ_REFLECTION2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','4','0','Chaos!','Chaos !','1','0','100','0','0','12505','KJ - SAY_KJ_DARKNESS1');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','4','1','Destruction!','Destruction !','1','0','100','0','0','12506','KJ - SAY_KJ_DARKNESS2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','4','2','Oblivion!','Oubli !','1','0','100','0','0','12507','KJ - SAY_KJ_DARKNESS3');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','5','0','I will not be denied! This world shall fall!','Rien ne m\'arrêtera ! Ce monde va tomber !','1','0','100','0','0','12508','KJ - SAY_KJ_PHASE3');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','6','0','Do not harbor false hope. You cannot win!','Assez de faux espoirs, vous ne pouvez pas gagner !','1','0','100','0','0','12509','KJ - SAY_KJ_PHASE4');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','7','0','Aggghh! The powers of the Sunwell... turned... against me! What have you done? WHAT HAVE YOU DONE?','Arggghh ! Les pouvoirs du Puit de Soleil se retournent contre moi... Qu\'avez-vous fait ? QU\'AVEZ-VOUS FAIT ?','1','0','100','0','0','12510','KJ - SAY_KJ_PHASE5');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25315','0','0','','','0','0','100','0','0','12527','KJ - SAY_KJ_DEATH');

replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','0','0','Strike now, heroes, while he is weakened! Vanquish the Deceiver!','Frappez héros ! Pendant qu\'il est affaibli ! Abbatez le Trompeur !','1','0','100','0','0','12449','KJ - SAY_KALECGOS_ENCOURAGE');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','1','0','I will channel my power into the orbs, be ready!','Je vais canaliser mon énergie vers les orbes, préparez-vous !','1','0','100','0','0','12440','KJ - SAY_KALECGOS_READY1');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','2','0','I have empowered another orb! Use it quickly!','J\'ai chargé un autre orbe, utilisez-le vite !','1','0','100','0','0','12441','KJ - SAY_KALECGOS_READY2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','3','0','Another orb is ready! Make haste!','Un autre orbe est prêt, hâtez-vous !','1','0','100','0','0','12442','KJ - SAY_KALECGOS_READY3');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','4','0','I have channeled all I can! The power is in your hands!','J\'ai envoyé tout ce que je pouvais, la puissance est entre vos mains.','1','0','100','0','0','12443','KJ - SAY_KALECGOS_READY4');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','5','0','Anveena, you must awaken, this world needs you!','<Texte manquant>','1','0','100','0','0','12445','KJ - SAY_KALECGOS_AWAKEN');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','6','0','You must let go! You must become what you were always meant to be! The time is now, Anveena!','<Texte manquant>','1','0','100','0','0','12446','KJ - SAY_KALECGOS_LETGO');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','7','0','Anveena, I love you! Focus on my voice, come back for me now! Only you can cleanse the Sunwell!','<Texte manquant>','1','0','100','0','0','12447','KJ - SAY_KALECGOS_FOCUS');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','8','0','Yes, Anveena! Let fate embrace you now!','<Texte manquant>','1','0','100','0','0','12448','KJ - SAY_KALECGOS_FATE');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','9','0','Goodbye, Anveena, my love. Few will remember your name, yet this day you change the course of destiny. What was once corrupt is now pure. Heroes, do not let her sacrifice be in vain.','<Texte manquant>','1','0','100','0','0','12450','KJ - SAY_KALECGOS_GOODBYE');
replace into `creature_text` (`entry`, `groupid`, `id`, `text_en`,`text_fr`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) values('25319','10','0','You are not alone. The Blue Dragonflight shall help you vanquish the Deceiver.','Vous n\'êtes pas seuls, le Vol Draconique Bleu vous aidera à vaincre le Trompeur !','1','0','100','0','0','12438','KJ - SAY_KALECGOS_JOIN');