ALTER TABLE creature_text 
	CHANGE `text_en` `text` LONGTEXT NOT NULL,
	ADD COLUMN BroadcastTextId MEDIUMINT(6) NOT NULL DEFAULT 0,
	ADD COLUMN TextRange TINYINT(3) UNSIGNED NOT NULL DEFAULT 0
	DROP COLUMN `text_fr`;