
/*!40101 SET NAMES utf8 */;

replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','0','0','Energy. Power. My people are addicted to it... a dependence made manifest after the Sunwell was destroyed. Welcome... to the future. A pity you are too late to stop it. No one can stop me now! Selama ashal\'anore!','14','0','100','0','0','11256','0','kaelthas SAY_INTRO');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','1','0','Capernian will see to it that your stay here is a short one.','14','0','100','0','0','11257','0','kaelthas SAY_INTRO_CAPERNIAN');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','2','0','Well done, you have proven worthy to test your skills against my master engineer, Telonicus.','14','0','100','0','0','11258','0','kaelthas SAY_INTRO_TELONICUS');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','3','0','Let us see how your nerves hold up against the Darkener, Thaladred.','14','0','100','0','0','11259','0','kaelthas SAY_INTRO_THALADRED');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','4','0','You have persevered against some of my best advisors... but none can withstand the might of the Blood Hammer. Behold, Lord Sanguinar!','14','0','100','0','0','11260','0','kaelthas SAY_INTRO_SANGUINAR');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','5','0','As you see, I have many weapons in my arsenal...','14','0','100','0','0','11261','0','kaelthas SAY_PHASE2_WEAPON');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','6','0','Perhaps I underestimated you. It would be unfair to make you fight all four advisors at once, but... fair treatment was never shown to my people. I\'m just returning the favor.','14','0','100','0','0','11262','0','kaelthas SAY_PHASE3_ADVANCE');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','7','0','Alas, sometimes one must take matters into one\'s own hands. Balamore shanal!','14','0','100','0','0','11263','0','kaelthas SAY_PHASE4_INTRO2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','8','0','I have not come this far to be stopped! The future I have planned will not be jeopardized! Now you will taste true power!','14','0','100','0','0','11273','0','kaelthas SAY_PHASE5_NUTS');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','9','0','You will not prevail.','14','0','100','0','0','11270','0','kaelthas SAY_SLAY1');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','9','1','You gambled...and lost.','14','0','100','0','0','11271','0','kaelthas SAY_SLAY2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','9','2','This was Child\'s play.','14','0','100','0','0','11272','0','kaelthas SAY_SLAY3');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','10','0','Obey me.','14','0','100','0','0','11268','0','kaelthas SAY_MINDCONTROL1');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','10','1','Bow to my will.','14','0','100','0','0','11269','0','kaelthas SAY_MINDCONTROL2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','11','0','Let us see how you fare when your world is turned upside down.','14','0','100','0','0','11264','0','kaelthas SAY_GRAVITYLAPSE1');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','11','1','Having trouble staying grounded?','14','0','100','0','0','11265','0','kaelthas SAY_GRAVITYLAPSE2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','12','0','Anara\'nel belore!','14','0','100','0','0','11267','0','kaelthas SAY_SUMMON_PHOENIX1');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','12','1','By the power of the sun!','14','0','100','0','0','11266','0','kaelthas SAY_SUMMON_PHOENIX2');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','13','0','For...Quel...thalas!','14','0','100','0','0','11274','0','kaelthas SAY_DEATH');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('19622','14','0','%s begins to cast Pyroblast!','41','0','100','0','0','0','0','kaelthas SAY_PYROBLAST');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20060','0','0','Blood for blood!','14','0','100','0','0','11152','0','sanguinar SAY_SANGUINAR_AGGRO');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20060','1','0','NO! I ...will... not...','14','0','100','0','0','11153','0','sanguinar SAY_SANGUINAR_DEATH');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20062','0','0','The sin\'dore reign supreme!','14','0','100','0','0','11117','0','capernian SAY_CAPERNIAN_AGGRO');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20062','1','0','This is not over!','14','0','100','0','0','11118','0','capernian SAY_CAPERNIAN_DEATH');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20063','0','0','Anar\'alah belore!','14','0','100','0','0','11157','0','telonicus SAY_TELONICUS_AGGRO');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20063','1','0','More perils... await','14','0','100','0','0','11158','0','telonicus SAY_TELONICUS_DEATH');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20064','0','0','Prepare yourselves!','14','0','100','0','0','11203','0','thaladred SAY_THALADRED_AGGRO');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20064','1','0','Forgive me, my prince! I have... failed.','14','0','100','0','0','11204','0','thaladred SAY_THALADRED_DEATH');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `TextRange`, `comment`) values('20064','2','0','%s sets his gaze on $N!','16','0','100','0','0','0','0','thaladred EMOTE_THALADRED_GAZE');


replace into `spell_script_names` (`spell_id`, `ScriptName`) values('35865','spell_kaelthas_summon_nether_vapor');
replace into `spell_script_names` (`spell_id`, `ScriptName`) values('35869','spell_kaelthas_nether_beam');
replace into `spell_script_names` (`spell_id`, `ScriptName`) values('35941','spell_kaelthas_gravity_lapse');
replace into `spell_script_names` (`spell_id`, `ScriptName`) values('36450','spell_kaelthas_resurrection');
replace into `spell_script_names` (`spell_id`, `ScriptName`) values('36797','spell_kaelthas_mind_control');
replace into `spell_script_names` (`spell_id`, `ScriptName`) values('36976','spell_kaelthas_summon_weapons');
replace into `spell_script_names` (`spell_id`, `ScriptName`) values('36709','spell_kaelthas_kael_phase_two');

replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20060','0','0','0','0','0','100','0','0','0','15000','15000','11','44863','0','0','0','0','0','1','0','0','0','0','0','0','0','Lord Sanguinar - In Combat - Cast Bellowing Roar');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20060','0','1','2','6','0','100','0','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Lord Sanguinar - On Death - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20060','0','2','0','61','0','100','0','0','0','0','0','11','36709','2','0','0','0','0','1','0','0','0','0','0','0','0','Lord Sanguinar - On Death - Cast Spell');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','0','0','0','0','100','0','0','0','2500','2500','11','36971','64','0','0','0','0','2','0','0','0','0','0','0','0','Grand Astromancer Capernian - In Combat - Cast Fireball');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','1','0','0','0','100','0','7000','10000','18500','20500','11','37018','0','0','0','0','0','5','30','0','0','0','0','0','0','Grand Astromancer Capernian - In Combat - Cast Conflagration');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','2','0','0','0','100','0','3000','3000','6000','6000','11','36970','0','0','0','0','0','5','8','0','0','0','0','0','0','Grand Astromancer Capernian - In Combat - Cast Arcane Burst');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','3','4','6','0','100','0','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Grand Astromancer Capernian - On Death - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20062','0','4','0','61','0','100','0','0','0','0','0','11','36709','2','0','0','0','0','1','0','0','0','0','0','0','0','Grand Astromancer Capernian - On Death - Cast Spell');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20063','0','0','0','0','0','100','0','0','0','2000','2000','11','37036','64','0','0','0','0','2','0','0','0','0','0','0','0','Master Engineer Telonicus - In Combat - Cast Bomb');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20063','0','1','0','0','0','100','0','5000','10000','20000','20000','11','37027','0','0','0','0','0','5','100','0','0','0','0','0','0','Master Engineer Telonicus - In Combat - Cast Remote Toy');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20063','0','2','3','6','0','100','0','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Master Engineer Telonicus - On Death - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20063','0','3','0','61','0','100','0','0','0','0','0','11','36709','2','0','0','0','0','1','0','0','0','0','0','0','0','Master Engineer Telonicus - On Death - Cast Spell');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','0','1','0','0','100','0','100','100','10000','10000','64','1','0','0','0','0','0','18','100','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Store Target');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','1','2','61','0','100','0','0','0','0','0','14','0','100','0','0','0','0','1','0','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Modify Threat PCT All');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','2','3','61','0','100','0','0','0','0','0','49','0','0','0','0','0','0','12','1','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Attack Start');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','3','4','61','0','100','0','0','0','0','0','1','2','0','0','0','0','0','12','1','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','4','0','61','0','100','0','0','0','0','0','138','10000000','0','0','0','0','0','12','1','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Modify Threat');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','5','0','0','0','100','0','4000','6000','9000','12000','11','36966','0','0','0','0','0','2','0','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Cast Psychic Blow');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','6','0','0','0','100','0','3000','4000','8000','10000','11','36965','0','0','0','0','0','2','0','0','0','0','0','0','0','Thaladred the Darkener - In Combat - Cast Rend');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','7','0','13','0','100','0','15000','15000','0','0','11','30225','0','0','0','0','0','2','0','0','0','0','0','0','0','Thaladred the Darkener - Victim Casting - Cast Silence');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','8','9','6','0','100','0','0','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Thaladred the Darkener - On Death - Talk');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','9','0','61','0','100','0','0','0','0','0','11','36709','2','0','0','0','0','1','0','0','0','0','0','0','0','Thaladred the Darkener - On Death - Cast Spell');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('20064','0','10','0','25','0','100','0','0','0','0','0','59','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Thaladred the Darkener - On Reset - Set Run false');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21362','0','1','0','37','0','100','257','0','0','0','0','80','2136200','2','0','0','0','0','1','0','0','0','0','0','0','0','Phoenix - AI Init - Script9');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21362','0','2','3','2','0','100','0','0','0','18000','18000','11','34341','0','0','0','0','0','1','0','0','0','0','0','0','0','Phoenix - Between HP 0% - Cast Ember Blast');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21362','0','3','4','61','0','100','0','0','0','0','0','12','21364','6','5000','0','0','0','1','0','0','0','0','0','0','0','Phoenix - Between HP 0% - Summon Creature');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21362','0','4','5','61','0','100','0','0','0','0','0','8','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Phoenix - Between HP 0% - Set React State');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21362','0','5','6','61','0','100','0','0','0','0','0','69','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Phoenix - Between HP 0% - Move To Point');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21362','0','6','0','61','0','100','0','0','0','0','0','18','33685510','0','0','0','0','0','1','0','0','0','0','0','0','0','Phoenix - Between HP 0% - Set Unit Flags');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21362','0','7','0','38','0','100','0','1','1','0','0','80','2136201','2','0','0','0','0','1','0','0','0','0','0','0','0','Phoenix - On Data Set - Script9');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21274','0','0','0','0','0','100','0','0','0','2200','2200','11','36990','64','0','0','0','0','5','50','0','0','0','0','0','0','Staff of Disintegration - In Combat - Cast Frost Bolt');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21274','0','1','0','0','0','100','0','5000','5000','10000','10000','11','36989','0','0','0','0','0','5','10','0','0','0','0','0','0','Staff of Disintegration - In Combat - Cast Frost Nova');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21270','0','0','0','0','0','100','0','3000','5000','7000','9000','11','36985','0','0','0','0','0','1','0','0','0','0','0','0','0','Cosmic Infuser - In Combat - Cast Holy Nova');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21270','0','1','0','14','0','100','0','30000','40','10000','10000','11','36983','0','0','0','0','0','7','0','0','0','0','0','0','0','Cosmic Infuser - Friendly Missing HP - Cast Heal');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21272','0','0','0','0','0','100','0','3000','5000','6000','8000','11','36991','0','0','0','0','0','2','0','0','0','0','0','0','0','Warp Slicer - In Combat - Cast Rend');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21269','0','0','0','0','0','100','0','4000','8000','12000','15000','11','36981','0','0','0','0','0','1','0','0','0','0','0','0','0','Devastation - In Combat - Cast Whirlwind');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21273','0','0','0','13','0','100','0','10000','10000','0','0','11','36988','0','0','0','0','0','2','0','0','0','0','0','0','0','Phaseshift Bulwark - Victim Casting - Cast Shield Bash');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21268','0','0','0','0','0','100','0','0','0','2000','2000','11','36980','64','0','0','0','0','2','0','0','0','0','0','0','0','Netherstrand Longbow - In Combat - Cast Shot');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('21268','0','1','0','0','0','100','0','4000','8000','12000','15000','11','36979','0','0','0','0','0','2','0','0','0','0','0','0','0','Netherstrand Longbow - In Combat - Cast Multi-Shot');


update creature_template SET AIName ="SmartAI", ScriptName = NULL WHERE entry IN (20064,20060,20062, 20063,21362,21274,21270,21272,21269,21273,21268);

replace into `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) values('13','1','36709','0','0','31','0','3','19871','0','0','0','0','','Target Kael\'thas');

replace into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values('23016','184597','550','1','744','43.6658','46.777','3.1415','0','0','0.997847','0.0655853','300','0','1');
replace into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values('23017','184596','550','1','744','-47.2326','46.777','3.1415','0','0','0.227545','0.973768','300','0','1');
replace into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values('23018','184597','550','1','744.045','42.3536','46.661','3.14159','0','0','1','-0.0000000437114','7200','255','1');
replace into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values('23019','184596','550','1','744.045','-44.6345','46.661','3.14159','0','0','1','-0.0000000437114','7200','255','1');


UPDATE creature_template SET faction = 1620 WHERE entry = 21272;

