UPDATE trinity_string SET content_default = "The Alliance wins!", content_loc2 = "L'Alliance l'emporte !" WHERE entry = 600;
UPDATE trinity_string SET content_default = "The Horde wins!", content_loc2 = "La Horde l'emporte !" WHERE entry = 601;
UPDATE trinity_string SET content_default = "The battle for Warsong Gulch begins in 1 minute.", content_loc2 = "La bataille pour le Goulet des Chanteguerre commence dans 1 minute." WHERE entry = 602;
UPDATE trinity_string SET content_default = "The battle for Warsong Gulch begins in 30 seconds. Prepare yourselves!", content_loc2 = "La bataille pour le Goulet des Chanteguerre commence dans 30 secondes. Préparez-vous !" WHERE entry = 603;
UPDATE trinity_string SET content_default = "Let the battle for Warsong Gulch begin!", content_loc2 = "La bataille pour le Goulet des Chanteguerre commence !" WHERE entry = 604;
UPDATE trinity_string SET content_default = "$n captured the Horde flag!", content_loc2 = "$n a pris le drapeau de la Horde !" WHERE entry = 605;
UPDATE trinity_string SET content_default = "$n captured the Alliance flag!", content_loc2 = "$n a pris le drapeau de l'Alliance !" WHERE entry = 606;
UPDATE trinity_string SET content_default = "The Horde flag was dropped by $n!", content_loc2 = "Le drapeau de la Horde a été laché par $n !" WHERE entry = 607;
UPDATE trinity_string SET content_default = "The Alliance Flag was dropped by $n!", content_loc2 = "Le drapeau de l'alliance a été laché par $n !" WHERE entry = 608;
UPDATE trinity_string SET content_default = "The Alliance Flag was returned to its base by $n!", content_loc2 = "Le drapeau de l'Alliance a été ramené à sa base par $n !" WHERE entry = 609;
UPDATE trinity_string SET content_default = "The Horde flag was returned to its base by $n!", content_loc2 = "Le drapeau de la Horde a été ramené à sa base par $n !" WHERE entry = 610;
UPDATE trinity_string SET content_default = "The Horde flag was picked up by $n!", content_loc2 = "Le drapeau de la Horde a été ramassé par $n !" WHERE entry = 611;
UPDATE trinity_string SET content_default = "The Alliance Flag was picked up by $n!", content_loc2 = "Le drapeau de l'Alliance a été ramassé par $n !" WHERE entry = 612;
UPDATE trinity_string SET content_default = "The flags are now placed at their bases.", content_loc2 = "Les drapeaux sont maintenant dans leurs bases." WHERE entry = 613;
UPDATE trinity_string SET content_default = "The Alliance flag has been respawned!", content_loc2 = "Le drapeau de l'Alliance est maintenant dans sa base." WHERE entry = 614;
UPDATE trinity_string SET content_default = "The Horde flag has been respawned!", content_loc2 = "Le drapeau de la Horde est maintenant dans sa base." WHERE entry = 615;
UPDATE trinity_string SET content_default = "The Battle for Eye of the Storm begins in 1 minute.", content_loc2 = "La bataille pour l'Oeil du Cyclone commence dans 1 minute." WHERE entry = 636;
UPDATE trinity_string SET content_default = "The Battle for Eye of the Storm begins in 30 seconds.", content_loc2 = "La bataille pour l'Oeil du Cyclone commence dans 30 secondes. Préparez-vous !" WHERE entry = 637;
UPDATE trinity_string SET content_default = "The Battle for Eye of the Storm has begun!", content_loc2 = "La bataille pour l'Oeil du Cyclone débute !" WHERE entry = 638;
UPDATE trinity_string SET content_default = "Alliance", content_loc2 = "'Alliance" WHERE entry = 650;
UPDATE trinity_string SET content_default = "Horde", content_loc2 = "a Horde" WHERE entry = 651;
UPDATE trinity_string SET content_default = "stables", content_loc2 = "l'Écurie" WHERE entry = 652;
UPDATE trinity_string SET content_default = "blacksmith", content_loc2 = "la Forge" WHERE entry = 653;
UPDATE trinity_string SET content_default = "farm", content_loc2 = "la Ferme" WHERE entry = 654;
UPDATE trinity_string SET content_default = "lumber mill", content_loc2 = "la Scierie" WHERE entry = 655;
UPDATE trinity_string SET content_default = "mine", content_loc2 = "la Mine" WHERE entry = 656;
UPDATE trinity_string SET content_default = "The %s has taken the %s", content_loc2 = "L%s s'est emparée de %s" WHERE entry = 657;
UPDATE trinity_string SET content_default = "$n has defended the %s", content_loc2 = "$n a défendu %s" WHERE entry = 658;
UPDATE trinity_string SET content_default = "$n has assaulted the %s", content_loc2 = "$n a attaqué %s" WHERE entry = 659;
UPDATE trinity_string SET content_default = "$n claims the %s! If left unchallenged, the %s will control it in 1 minute !", content_loc2 = "$n a pris %s ! Si cela reste inchangé l%s va en prendre le contrôle dans 1 minute !" WHERE entry = 660;
UPDATE trinity_string SET content_default = "The Battle for Arathi Basin begins in 1 minute.", content_loc2 = "La bataille pour le Bassin d'Arathi commence dans 1 minute." WHERE entry = 661;
UPDATE trinity_string SET content_default = "The Battle for Arathi Basin begins in 30 seconds. Prepare yourselves!", content_loc2 = "La bataille pour le Bassin d'Arathi commence dans 30 secondes. Préparez-vous !" WHERE entry = 662;
UPDATE trinity_string SET content_default = "The Battle for Arathi Basin has begun!", content_loc2 = "La bataille pour le Bassin d'Arathi débute !" WHERE entry = 663;
UPDATE trinity_string SET content_default = "The Alliance has gathered $1776W resources, and is near victory!", content_loc2 = "L'Alliance a réuni $1776W ressources, et s'approche ainsi de la victoire !" WHERE entry = 664;
UPDATE trinity_string SET content_default = "The Horde has gathered $1777W resources, and is near victory!", content_loc2 = "La Horde a réuni $1777W ressources, et s'approche ainsi de la victoire !" WHERE entry = 665;
