UPDATE locales_quest SET OfferRewardText_loc2 = "Vous êtes effectivement un héros spécial, $N. Nous vous souhaitons la bienvenue dans le monde d'Azeroth, et vous offrons un de ces cadeaux uniques !", RequestItemsText_loc2 = "Salutations ! C'est un plaisir de vous rencontrer !$B$BJe vois que vous avez un bon spécial. Donnez-le moi et je vous offrirai quelque chose en échange." WHERE entry = 9278;
UPDATE locales_quest SET OfferRewardText_loc2 = "Ceci fera l'affaire. Merci, $C !$B$BPendant que vous étiez parti, je me suis débrouillé pour collecter l'équipement nécessaire à l'analyse de ces échantillons. Cela devrait ne prendre que quelques instants.", RequestItemsText_loc2 = "Je vais avoir besoin d'échantillons en bon état si nous voulons avoir une chance de purifier le lac.$B$BNous n'avons pas beaucoup de temps, $C !" WHERE entry = 9293;
UPDATE locales_quest SET OfferRewardText_loc2 = "D'après votre description, l'agent neutralisant a fonctionné ! J'aurais juste aimé savoir combien de temps cela va durer; nous avons vraiment besoin de retirer entièrement ce cristal de puissance du lac.$B$BMerci, $N ! Je vais dire à Tedon d'essayer le produit sur une des bêtes capturées à l'occasion.", RequestItemsText_loc2 = "Le plus vite vous déverserez le produit sur le lac, le moins de créatures seront transformées après avoir bu de l'eau infectée, y compris nous !$B$BJe suis désolé que nous ne puissions rien faire pour aider les créatures déjà infectées. Si seulement mon équipement était intact." WHERE entry = 9294;
UPDATE locales_quest SET OfferRewardText_loc2 = "Laissez-moi y jeter un oeil.$B$BOui, je pense qu'ils feront l'affaire; bon travail, $N. L'émetteur est assez complexe, donc cela pourrait prendre un certain temps pour terminer les réparations. Je vous ferai savoir quand c'est prêt.$B$BEn attendant, allez voir si le Redresseur de torts Aldar peut vous employer à quelque chose.", RequestItemsText_loc2 = "Quand nous auront ces morceaux de remplacement, je sais que nous pourrons réparer l'émetteur. Avec un peu de chance, il reste encore quelqu'un à contacter." WHERE entry = 9305;
UPDATE locales_quest SET RequestItemsText_loc2 = "Alors c'est vrai... un groupe d'éclaireurs elfes de sang ici, au Val d'Ammen ! Comment nous ont-ils suivis ?$B$BJe vais envoyer immédiatement quelqu'un pour ramener Tolaan" WHERE entry = 9311;
UPDATE locales_quest SET RequestItemsText_loc2 = "Je travaille sur une solution qui pourrait être efficace avec les créatures étranges. J'ai juste besoin d'un peu de temps supplémentaire." WHERE entry = 10302;
UPDATE locales_quest SET RequestItemsText_loc2 = "Il y en a trop... Nous devons les décimer ou les survivants n'auront aucune chance contre elles." WHERE entry = 10303;
UPDATE locales_quest SET OfferRewardText_loc2 = "$N, n'est-ce pas ? J'ai entendu de bonnes choses au sujet de vous et du travail que vous avez fait en peu de temps depuis que vous êtes arrivé ici.$B$BNous allons vraiment avoir besoin de votre aide pour ramener les choses à la normale. Zhanaa, là-bas, pourra aussi requérir votre aide, j'en suis sûr." WHERE entry = 10304;

