-- MySQL dump 10.13  Distrib 5.1.62, for pc-linux-gnu (i686)
--
-- Host: localhost    Database: thum_tradwm
-- ------------------------------------------------------
-- Server version	5.1.62

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `locales_quest`
--
-- WHERE:  entry IN (1057, 1068, 1071, 1077, 1078, 1079, 1080, 1087, 1088, 1091, 1092, 6284, 6301, 6381, 6481, 6542, 6548, 6629)

DELETE FROM locales_quest WHERE entry IN (1057, 1068, 1071, 1077, 1078, 1079, 1080, 1087, 1088, 1091, 1092, 6284, 6301, 6381, 6481, 6542, 6548, 6629);
/*!40000 ALTER TABLE `locales_quest` DISABLE KEYS */;
INSERT INTO `locales_quest` VALUES (1057,'Reclaiming the Charred Vale','À la reconquête du Val calciné',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'En tant que protecteur des esprits de la forêt, vous pouvez sans aucun doute deviner pourquoi je suis alarmé.$B$BVous avez voyagé à travers ces montagnes pour atteindre ce pic, et avez sûrement vu les changements terrifiants qu\'a subi la terre. La cupidité a mené à la destruction de ces collines sacrées.$B$BLe Val calciné, au sud, a été consumée par une avide armée mécanique. Pire encore, les Rougefuries qui ont empiété sur ce territoire nous en interdisent l\'accès et nous empêchent d’y prospérer à nouveau.$B$BChassez ces affreuses harpies, $N !',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Le Gardien Albagorm du pic des Serres-Rocheuses veut que vous tuiez 7 Harpies, 7 Embusqués, 7 Tueuses et 7 Volplumes Rougefuries.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'À présent que les Rougefuries ont essuyé de telles pertes, le véritable travail pour restaurer la terre peut peut-être commencer…',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Il ya beaucoup de travail à faire avant que le Val calciné puisse redevenir la forêt luxuriante qu\'elle était autrefois.$B$BNettoyez la zone de ces menaces immondes, $N! Ce n\'est qu\'alors que nous pourrons commencer à redonner vie à la nature.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1068,'Shredding Machines','Les machines à déchiqueter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Il existe une relation entre la magie spirituelle des chamans et la magie naturelle des druides. C\'est pourquoi nous, les chamans, nous pouvons entendre la complainte des esprits des Serres-Rocheuses. Beaucoup de leurs murmures m\'échappent, mais un message – une vision – est clair...$b$bJ\'ai eu la vision de deux machines à forme humaine, dans la Combe des cisailles, au nord-ouest du val de Grandbois, coupant les arbres à une vitesse incroyable. Ces bêtes de métal doivent être stoppées !$b$bDans ma vision, il y avait d\'étranges symboles gravés sur les machines :$b$bXT4 et XT9.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Détruire les Déchiqueteurs XT4 et XT9, puis retourner voir Seereth Bris-de-pierre à la frontière entre les Serres-Rocheuses et les Tarides.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'La destruction des machines XT4 et XT9 a apaisé nombre des esprits des Serres-Rocheuses, $N. Après cette opération, espérons que la KapitalRisk se retire d’elle-même des montagnes.$B$BCar si elle ne le fait pas, alors je crains que les atrocités commises sur cette terre ne soient rien en comparaison de ce qui pourrait arriver.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Les esprits des arbres pleurent la mort de leurs frères, $N. Vous devez détruire les Déchiqueteurs XT4 et XT9 ou je crains que les Serres-Rocheuses ne puissent jamais guérir .',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1071,'A Gnome\'s Respite','Du répit pour un gnome',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Vous voyez, $N, je suis un membre de l\'Assemblée illuminée d\'arcanologie, d\'alchimie et de sciences d\'ingénierie, et c\'est mon but… non, il est de mon DEVOIR de montrer aux elfes de la nuit que l’association de magie, de mixtures et de mécanique peut aider à sauver leurs forêts.$B$BMais c\'est un combat acharné, et les gobelins semblent se reproduire comme des lapins. Je n\'ai même pas eu le temps de construire mes dernières inventions !$B$BJ\'ai besoin de temps pour planifier et organiser. Mais vous pouvez m’aider à retenir les gobelins à quai à la combe des Cisailles, à l\'est.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tuer 10 Déboiseurs de la KapitalRisk et 10 Défricheurs de la KapitalRisk, puis retourner voir Gaxim Larguerouille dans les Serres-Rocheuses.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Je vous remercie tellement pour votre aide, $N. Vous revenez juste à temps, en fait. Je crois que j\'ai un plan parfait… des explosifs. Non, ce n\'est pas le plan ! Mais ça fait partie du plan.$B$BVous voyez, j\'ai utilisé de puissants explosifs – ne vous en faites pas, ils ne sont pas aussi dangereux qu’on le dit – pour effrayer un peu les gobelins. J\'arrive à les attrouper plutôt bien avec quelques détonations placées à des endroits clés le long des crêtes, mais je n\'ai plus beaucoup de matériel depuis quelques jours...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Comment s\'est terminé la bataille, $N ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1077,'Special Delivery for Gaxim','Livraison spéciale pour Gaxim',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Voilà, $N. Ça devrait faire l\'affaire.$B$BAssurez Gaxim de ma considération la prochaine fois que vous le verrez. J\'ai hâte d\'entendre la suite de cette aventure.$B$BAdieu.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Apporter le Parchemin de contact à Gaxim Larguerouille dans les Serres-Rocheuses.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'C\'est parfait, $N! Génial.$B$BCe sort, mélangé avec le NG-5, fera un explosif à distance parfait.$B$BNous allons être en mesure de créer la distraction parfaite pour vous, afin que vous puissiez vous glisser et voler à la KapitalRisk les lettres et des plans d\'ingénierie.$B$BCa va sûrement ralentir la déforestation ainsi que leurs activités annexes.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Haha! Vous êtes de retour! L\'avez-vous ? Avez-vous le sort ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1078,'Retrieval for Mauren','Des retrouvailles pour Mauren',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Les voyageurs m\'interrogent toujours au sujet des Serres-Rocheuses. C’est une région populaire pour qui cherche l\'aventure, qu’il s’agisse de traquer des wyvernes, des élémentaires, ou du personnel de la KapitalRisk.$b$bDans le Val calciné, loin à l’intérieur des montagnes, vivait autrefois une espèce de basilic dont les écailles, une fois plantées dans la poussière, produisaient un merveilleux réactif pour certains des sorts que j\'ai créés.$b$bSi ces basilics vivent toujours, j\'aimerais avoir quelques-unes de leurs écailles.$b$bPrenez votre temps, ce n\'est pas urgent, mais je paye bien.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Apporter 8 Ecailles de cristal à Collin Mauren à Hurlevent.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'C\'est parfait, $N. Je vous remercie grandement.$B$BPeut-être qu\'un jour prochain, je serai en mesure de vous aider comme vous m\'avez aidé.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bonjour, $N.$b$bAvez-vous déjà pu récupérer les écailles dans le Val Calciné ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1079,'Covert Ops - Alpha','Opérations secrètes – Plan A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ça y est, $N. Faites très attention ! Les dispositifs sont montés et prêts à fonctionner.$B$BPrenez ces explicatifs. Ils résument tout ce qu\'il faut savoir sur les détonateurs et les explosifs, et indiquent également où vous devez les placer.$B$BRappelez-vous, le succès de votre mission ne dépend pas de la somme de destruction que vous provoquerez. Le succès du plan A dépend du fait que vous rapportiez les plans d\'ingénierie de la KapitalRisk de l\'intérieur de la scierie au sud du lac de la Combe.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Récupérer les Plans d\'ingénierie de la KapitalRisk dans la scierie de la Combe des Cisailles.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Impressionnant! C\'est un coup dur pour la KapitalRisk.$B$BNous allons être en mesure de trouver les faiblesses de leurs machines et d\'y intégrer leurs atouts dans nos propres créations. C\'est un jour merveilleux.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Avez-vous les plans, $N ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1080,'Covert Ops - Beta','Opérations secrètes – Plan B',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Le plan B est identique au plan A, $N.$B$BNous faisons diversion et nous volons leurs précieuses notes.$B$BLe plus important est d\'obtenir leurs notes… Rappelez-vous de ça.$B$BLes explicatifs que je vous ai déjà fournis indiquent où placer les explosifs. Revenez simplement ici en vie et avec ces notes...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Récupérer les Notes de la KapitalRisk dans la mine des Cisailles à l\'extrémité est de la Combe des Cisailles.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Incroyable, $n! Kaela et les Sentinelles seront tellement heureuses. Avec vos compétences et mes créations, nous allons être invincibles.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Comment ça s\'est passé, $N ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1087,'Cenarius\' Legacy','L\'héritage de Cénarius',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Vous ne pouvez pas imaginer la haine que je ressens pour cette terre misérable. Au pic, les semblables de Cénarius et les druides kaldorei emploient leurs pouvoirs minables pour étouffer le flot de magie, même jusqu\'au sud de leurs possessions pathétiques... leurs forêts bien-aimées.$b$bJe voudrais retourner à Jaedenar et exulter dans le flot de magie, mais mon maître ne le permettra pas tant que mon travail ici ne sera pas achevé.$b$bIl ne fait aucun doute que vous aimez les elfes de la nuit et leurs alliés aussi peu que je les aime. Aidez-moi, et notre but commun pourra être atteint.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tuer 4 Fils de Cénarius, 4 Filles de Cénarius et 4 Botanistes cénariens pour Braelyn Brasemain, près de la Retraite de Roche-Soleil.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Déjà je le sens… oui… un pouvoir si suave… un torrent déferlant. Les kaldorei sont idiots de refuser les présents de ce monde, de rejeter le courant de la magie tandis qu\'il coule, chantant dans vos veines.$B$BQuelle pâle caricature est la vie sans son étreinte de feu...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ici, canaliser la magie, c\'est comme tirer de l\'eau d\'un puits avec un seau plein de trous.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1088,'Ordanus','Ordanus',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ils ont cru qu\'ils pourraient arrêter le flot de magie. Ils se sont trompés. Ils ont cru pouvoir cacher Ordanus, mais j\'aurai sa tête !$b$bLa magie m\'accorde la vision véritable. Oui… il est là. Un croisement… Au sommet d\'un grand arbre dans la forêt d\'Orneval. Un nom... Raynebois. L\'un des fils aînés du dieu de la Forêt. Ils l\'ont fait disparaître du pic avant que je puisse le trouver, mais son temps est compté.$b$bApportez-le-moi et je vous offrirai un puissant cadeau.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Apporter la Tête d\'Ordanus à Braelyn Brasemain, près de la Retraite de Roche-Soleil.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'J\'ai rencontré Ordanus une fois, il y a bien longtemps. Il a eu l\'arrogance de son espèce, se tenant au-dessus des Bien-nés.$B$BSa tête ne monte pas si haut maintenant, n\'est-ce-pas, $n ?$B$BJ\'ai promis une récompense, et cela vous sera accordé. Laissez-moi un instant.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Quand mon maître m\'a dit d\'aller au pic des Serres-Rocheuses, je m\'attendais à voir les elfes de la nuit dévaster et piller notre ancien temple d\'Azshara, et dépouiller les lieux de son caractère sacré ... mais Ordanus m\'avait glissé entre les doigts.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1091,'Kaela\'s Update','Des nouvelles pour Kaela',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$N, apportez ces notes à Kaela. Il est certain qu\'elle voudra en savoir plus à ce propos. Ou du moins ce sera le cas des Sentinelles.$B$BDites-lui à quel point notre victoire a été éclatante, et à quel point nous n\'aurions pu y parvenir sans l\'aide d\'un peu de magie.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Apporter les Notes de la KapitalRisk à Kaela Ombrelance.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'C\'est très intéressant en effet.$b$bVous et Gaxim avez fait du bon travail, $n. Merci.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Oui, $N ? Qu\'est-ce que je peux faire pour vous ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1092,'Gerenzo\'s Orders','Les ordres de Gerenzo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Je pense que je ferais mieux d’envisager de ficher le camp d\'ici, aussi. Ça ne va pas prendre beaucoup de temps avant que la nouvelle de ce qui s\'est passé ici se répande au-dessus, et je suis sûr qu\'ils ne seraient pas ravis de me revoir.$B$BJe vais dégager d’ici et aller voir Ziz. J\'espère qu\'il pourra me trouver du boulot !$B$BJe vais essayer de nettoyer ce bordel, mais vous devez apporter l\'échantillon de minerai à Ziz tout de suite. Il m\'a dit qu\'il établirait un camp quelque part du côté ouest de la Combe des Cisailles. Bonne chance.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Remettre le Minerai non identifié à Ziz Fizzik dans les Serres-Rocheuses.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ahhh, je savais que j\'avais pris la bonne décision en disant à Piznik de rester derrière. Je suis sûr que les ingénieurs seront très intéréssés par ce... bien sûr.$b$bEt je vais garder un petit morceau pour moi, après tout, s\'ils n\'en savent rien, ça ne peut pas faire de mal, n\'est-ce pas ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'En quoi puis-je vous aider ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6284,'Arachnophobia','Arachnophobie',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Attention : si vous pénétrez dans le Canyon de Sishir, à l’ouest d\'ici, ce sera à vos risques et périls.$B$BBesseleth et ses enfants arachnéens de la forêt ont pris possession du territoire, et en ont fait leur repaire et leur nid.$B$BMaggran Lieur-de-terre, de la Retraite de Roche-Soleil, a mis la tête de Besseleth à prix. Tuez-la et apportez une preuve de sa mort à Maggran ; vous recevrez une récompense pour avoir fait disparaître cette menace à huit pattes.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tuer Besseleth et apporter le Croc de Besseleth à Maggran, à la Retraite de Roche-Soleil.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bonne chasse, $N! Besseleth était un prédateur ancien ... Elle ne me manquera pas. Prenez cette récompense, vous êtes le champion des forêts.$B$b$b$bPeut-être que maintenant les gens viendront plus nombreux ici, sans avoir peur de ce qui se cache dans l\'ombre.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Besseleth est un prédateur redoutable... Je crains pour la vie de ceux qui empruntent ce chemin la nuit.Ce n\'est pas rare, qu\'elle et sa descendance, prennent la vie des voyageurs innocents. Elle a même été à deux doigts de me tuer, mais par chance, j\'ai réussi à m\'extirper in-extremis de ses crochets venimeux. Je donnerai tout ce que je possède pour voir ce monstre abattu.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6301,'Cycle of Rebirth','Cycle de la renaissance',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'L\'avidité des industries et la guerre permanente ont détruit les Serres-Rocheuses. Seule la bénédiction de la Terre-mère peut soigner une pareille blessure.$B$B$N, j\'ai besoin que vous récoltiez des graines spéciales, aussi nommées graines de Gaïa. On ne les trouve que dans les Serres-Rocheuses, au nord de la Retraite de Roche-Soleil, au bord du lac Mirkfallon.$B$BUne fois que vous m\'aurez rapporté les graines, je les enchanterai grâce à mes pouvoirs chamaniques, afin d\'accélérer leur croissance.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tammra Champ-des-vents, de la Retraite de Roche-Soleil, vous demande de récolter 10 Graines de Gaïa.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ah ? $N, vous avez les graines de Gaïa. Regardez, et vous pourrez admirez le pouvoir que ces graines peuvent avoir sur ces terres. Seules ces plantes peuvent sauver la région.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'La destruction continue causée par la guerre et ceux qui cherchent le profit dans la souffrance des arbres me touche profondément. Le moins qu\'on puisse faire est de continuer le cycle de la renaissance et de semer les graines de Gaïa pour reconstituer les terres d\'une nouvelle forêt. Avez-vous des graines de Gaïa requises, $C ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6381,'New Life','Nouvelle vie',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Comme vous avez pu le constater, $c, le cycle de la vie demeure une instance puissante, même quand la terre souffre. Vous devez aller planter ces graines au cœur de la destruction, à l\'ouest, dans le Val calciné. Sur votre chemin, prenez garde aux harpies et aux élémentaires de feu enragés, fléaux vivants qui sévissent sur cette terre scarifiée.$B$B$N, prenez ces graines de Gaïa enchantées, et allez les planter dans des monticules de sol fertile. Le cycle de la vie doit se perpétuer !',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Planter 10 Graines de Gaïa sur les Monticules de Gaïa, puis parler à Tammra, à la Retraite de Roche-Soleil.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'C\'est la grande victoire de la terre. Avec le temps, d\'autres choses viendront à changer: la KapitalRisk remballera ses scies et ses haches, les esprits du feu en colère se calmeront, et les harpies seront poussées à fuir la terre.$b$bAlors, $N, seulement avec la volonté, les êtres des Serres seront vraiment en paix.$b$BVous avez bien travaillé $C, alors prenez un de ces articles en guise de remerciement pour la vie que vous avez redonné ici, aujourd\'hui.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ces graines que vous plantez sont fortes, résistantes à la corruption et sont un premier pas vers d\'autres formes de vie. Elles vont pousser et pousser, elles vont  empêcher la prolifération de la corruption, soigner ces terres blessées, et un jour, elles restaureront la luxueuse forêt qui était autrefois dans ce vallon. Avez-vous planté toutes les graines ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Graines de Gaïa plantées',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6481,'Earthen Arise','Un Terrestre se lève',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Vous avez découvert une sombre menace pour cette terre, $C. La gangue de résonite que vous avez trouvée dans cette caverne abrite un Terrestre dormant du nom de Goggeroc.$B$BGrâce à mes pouvoirs chamaniques, j\'ai modifié le mélange des cristaux de résonite que vous avez ramassés. Prenez ce cristal de résonite enchanté et servez-vous-en pour ouvrir la gangue de résonite qui abrite le Terrestre.$B$BQuand il sera réveillé, Goggeroc sera affaibli... Abattez-le, $N !',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ouvrir la Gangue de résonite avec le Cristal de résonite enchanté, puis tuer Goggeroc. Retourner voir Mor\'rogal pour l\'informer et lui rapporter le Cristal de résonite enchanté.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Vous apportez de bonnes nouvelles, $C!$b$bGoggeroc était une tâche pour un héros. Vous avez bien fait; les Serres-Rocheuses et Kalimdor vous sont redevables, noble $C.$b$bAcceptez cette récompense, je suis très honoré de vous l\'offrir.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Je crains que si nous ne mettons pas immédiatement un terme à cette menace, toutes les Serres-Rocheuses seront perdues. La puissance d\'un terrestre ne peut être égalée par aucun moyen. Une fois réveillé, Goggeroc sera faible suite à son long sommeil, et ce sera la seule et unique occasion ... allez maintenant, $N!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6542,'Report to Kadrak','Rapport à Kadrak',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Avez-vous déjà été à Orneval, au nord  ? La Horde a récemment établi un Avant-poste sur la grève de Zoram ; nous nous réjouissons toujours d’accueillir de nouvelles recrues pour nous aider à livrer bataille.$B$BSi vous avez confiance en vous et que vous voulez nous aider, allez voir Kadrak, dans le nord des Tarides, à la tour de guet. C’est lui qui dirige la campagne d’Orneval ; c’est lui également qui vous dira quoi faire.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Faire un rapport à Kadrak, dans la tour de guet, dans le nord des Tarides.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Orneval est une terre divisée, mais nos efforts les plus récents ont eu beaucoup de succès. Nous avons non seulement un avant-poste à la grève de Zoram, mais également un autre, juste au nord d\'ici, appelé Bois-brisé.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6548,'Avenge My Village','Vengez mon village !',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Le clan du Totem-sinistre a fait un raid sur mon village et y a tué presque tout le monde ; j’ai lutté autant que j’ai pu, abattant autant d’ennemis que possible, mais j’ai dû battre en retraite et ai pu m’échapper de justesse.$b$b$N, je n’aspire qu’à la vengeance et à en voir toujours plus mourir sous mon épée. Aidez-moi à les massacrer, vous les trouverez un peu plus à l’ouest.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tuez 8 Forbans du Totem-sinistre et 6 Mercenaires du Totem-sinistre, puis retournez voir Makaba Sabot-plat, près de la lisière sud-est des Serres-Rocheuses.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$N, merci... mais je n\'oublierai jamais ce que le Totem-sinistre a fait à mon village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Les avez-vous déjà tués ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6629,'Kill Grundig Darkcloud','Tuer Grundig Noir-nuage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$N, vous avez fait un travail magnifique en tuant les membres du Totem-sinistre. Grundig Noir-nuage et sa bande de brutes personnelles sont de loin les pires de tous. Il était celui qui mena l\'attaque sanglante contre mon village.$b$bVous le trouverez au Poste Totem-sinistre, un peu plus haut sur le chemin qui conduit vers l\'ouest. Tuez-le et je vous en serai reconnaissant pour toujours.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tuer Grundig Noir-nuage et 6 Brutes du Totem-sinistre, puis retourner voir Makaba Sabot-plat, à côté de la frontière sud-est des Serres Rocheuses.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Grundig Noir-nuage est mort ! $N, je vous serai éternellement reconnaissant de ce que vous avez fait aujourd\'hui.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Avez-vous tué Grundig Noir-nuage et sa troupe de brutes ?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
/*!40000 ALTER TABLE `locales_quest` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2012-09-20 22:24:04
