RENAME TABLE creature_questrelation TO creature_queststarter;
RENAME TABLE creature_involvedrelation TO creature_questender;
RENAME TABLE gameobject_questrelation TO gameobject_queststarter;
RENAME TABLE gameobject_involvedrelation TO gameobject_questender;