
/*!40101 SET NAMES utf8 */;

replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('4949','0','0','My people have survived in Outland...','12','0','100','0','0','0','Thrall - Messenger event 1 (quest 9438)','0','0');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('4949','1','0','Unnoticed for years...','12','0','100','0','0','0','Thrall - Messenger event 2 (quest 9438)','0','0');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('4949','2','0','...uncorrupted!','12','0','100','0','0','0','Thrall - Messenger event 3 (quest 9438)','0','0');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('3144','0','0','Thrall! My lord... are you all right?','12','0','100','0','0','0','Thrall - Messenger event 4 (quest 9438)','0','0');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('4949','3','0','I\'ll be fine, Eitrigg. We must begin preparations... I need to go to Outland at once!','12','0','100','0','0','0','Thrall - Messenger event 5 (quest 9438)','0','0');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('3144','1','0','With all due respect, Warchief. Our enemies would take advantage of your sudden absence if we don\'t prepare properly.','12','0','100','0','0','0','Thrall - Messenger event 6 (quest 9438)','0','0');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('4949','4','0','You are right, Eitrigg. The timing is unfavorable. Make sure our best ambassadors are sent as envoys to Hellscream.','12','0','100','0','0','0','Thrall - Messenger event 7 (quest 9438)','0','0');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('3144','2','0','At once, sir! For the Horde!','12','0','100','0','0','0','Thrall - Messenger event 8 (quest 9438)','0','0');
replace into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`, `TextRange`) values('4949','5','0','If he\'s anything like his father, allying with the Mag\'har will mark the dawn of a new age for the Horde.','12','0','100','0','0','0','Thrall - Messenger event 9 (quest 9438)','0','0');
