UPDATE game_event SET start_time = FROM_UNIXTIME(1327186860), length = 28800 WHERE entry = 7;

UPDATE locales_quest SET OfferRewardText_loc2 = "Il est doux de savoir que les peuples de cette terre rendent encore hommage aux races anciennes. Je vous souhaite bonne chance, $N, et vous offre ce gage de mon estime..." WHERE entry IN (8619, 8642, 8643, 8644, 8645, 8646, 8647, 8648, 8649, 8650, 8651, 8652, 8653, 8654, 8866);
UPDATE locales_quest SET OfferRewardText_loc2 = "Les batailles des âges anciens sont les graines des légendes du présent. Vous vivez en un temps de héros, mon enfant. Puisse votre légende s’enraciner et prospérer !" WHERE entry = 8635;
UPDATE locales_quest SET OfferRewardText_loc2 = "La substance de la vie est condamnée à mourir et à retourner à la terre, mais la substance de l’esprit est éternelle. Je vous souhaite bonne chance, $N, et vous offre ce gage de mon estime..." WHERE entry = 8636;
UPDATE locales_quest SET OfferRewardText_loc2 = "La vie brûle en vous, jeune $C. J’accepte votre hommage, et je vous offre ce gage de mon estime..." WHERE entry IN (8670, 8671, 8672, 8673, 8674, 8675, 8676, 8677, 8678, 8679, 8680, 8681, 8682, 8683, 8684, 8685, 8686);
UPDATE locales_quest SET OfferRewardText_loc2 = "Chacune des innombrables étoiles qui brillent dans les cieux renferme la réponse à un mystère terrestre, $N. Puissent les sages – et les chanceux – les contempler et découvrir la vérité." WHERE entry IN (8688, 8713, 8714, 8715, 8716, 8717, 8718, 8719, 8720, 8721, 8722, 8723, 8724, 8725, 8726, 8727);
UPDATE locales_quest SET OfferRewardText_loc2 = "Très bien - j'accepte ces pièces des ancêtres. Prenez cette chandelle d'Elune avec ma bénédiction. Oh, et acceptez également ces feux d'artifice en complément.$B$BPuisse votre Fête lunaire être joyeuse et pleine de bonheur.$B$BEt si vous décidez d'affronter Présage et ses serviteurs, la chandelle d'Elune vous sera très utile...", RequestItemsText_loc2 = "La chandelle d'Elune est un artefact d'une grande importance pour les disciples de la Fête lunaire. Dans la chandelle est conservé un vrai rayon de lune, prêt à être lâché !$B$BCette lumière ne blesse pas la majorité des créatures, mais vous vous apercevrez que Présage et ses serviteurs sont brûlés et éblouis par celle-ci." WHERE entry = 8862;
UPDATE locales_quest SET Details_loc2 = "Si vous avez faim, vous êtes au bon endroit mon ami !$B$BLes raviolis sont une nourriture traditionnelle de la Fête lunaire; ils sont servis depuis l'époque de la première Fête lunaire, et je suis heureux de pouvoir vous en offrir cette fois. En échange d'une seule pièce des ancêtres, je partagerai avec vous un échantillon du meilleur repas que vous dégusterez jamais !", OfferRewardText_loc2 = "Excellent - profitez bien de ces raviolis. Même s'ils ne sont qu'une faible récompense pour tout l'honneur dont vous avez fait preuve, je pense que vous en profiterez bien tout de même.$B$BSi vous avez d'autres pièces des ancêtres, je me tiens prêt à vous offrir pas mal d'objets en échange." WHERE entry = 8863;
UPDATE locales_quest SET OfferRewardText_loc2 = "Très bien - j'accepte ces pièces des ancêtres. Prenez votre robe avec ma bénédiction. Oh, et acceptez également ces feux d'artifice en complément.$B$BVous avez honoré vos ancêtres, vous m'honorez de votre présence. Puisse votre Fête lunaire être joyeuse et pleine de bonheur.", RequestItemsText_loc2 = "J'ai une sélection de robes qui pourraient vous intéresser. De telles robes ont été portées par le passé durant la Fête lunaire, et la sélection que j'ai aujourd'hui est probablement la plus jolie que j'aie jamais vue. Chacune est faite à la main avec les plus précieux des composants.$B$BEn échange de quelques pièces des ancêtres, je vous laisserai en choisir une. Cela vous parait-il acceptable ?" WHERE entry = 8864;
UPDATE locales_quest SET OfferRewardText_loc2 = "Très bien - j'accepte ces pièces des ancêtres. Prenez votre habit de fête avec ma bénédiction. Oh, et acceptez également ces feux d'artifice en complément.$B$BSi vous avez d'autres pièces des ancêtres à échanger, parlez moi à nouveau. Je vous offrirai divers objets tout au long de la Fête lunaire.", RequestItemsText_loc2 = "Je suis ravi de vous informer que j'ai une sélection d'habits de fête disponibles pour vous dès maintenant... mais seulement en échange de pièces des ancêtres. Si la mode est importante pour vous, j'ai ce que vous cherchez ! Je vous assure que vous ne trouverez d'habits comme cela nulle part ailleurs.$B$BEn échange de quelques pièces des ancêtres, je vous laisserai en choisir un. Cela vous parait-il acceptable ?" WHERE entry = 8865;
UPDATE locales_quest SET RequestItemsText_loc2 = "Avez-vous trouvé les lanceurs, $N ?" WHERE entry = 8867;
UPDATE locales_quest SET Details_loc2 = "Je détiens le secret de fabrication des feux d'artifice de la Fête lunaire, et je suis heureux de partager mon savoir avec ceux qui sont honorés.$B$BEn échange de quelques pièces des ancêtres, je peux vous offrir la recette pour fabriquer des petites fusées...", OfferRewardText_loc2 = "Ah, très bien. Voici vos recettes, $N, et puisse Elune vous bénir." WHERE entry = 8876;
UPDATE locales_quest SET Details_loc2 = "Bien que les feux d'artifice sont une façon merveilleuse de célébrer un événement, pour vraiment voir leur beauté... ils doivent être tirés depuis un lanceur.$B$BApportez-moi des pièces des ancêtres et je pourrai vous offrir la connaissance requise pour fabriquer des lanceurs de fusées comme ceux que vous avez pu voir à Reflet-de-lune.", OfferRewardText_loc2 = "Vous voilà, $N. Voici les schémas pour créer un lanceur de fusées. Placez les lanceurs là où vous voulez faire la fête, et invitez vos amis à vous rejoindre !" WHERE entry = 8877;
UPDATE locales_quest SET Details_loc2 = "Les robes et pantalons de fête sont des vêtements traditionnels d'il y a beaucoup d'années. Ils sont portés pour honorer les anciennes coutumes et les êtres aimés qui s'en sont allés.$B$BSi vous m'apportez des pièces des ancêtres, $N, je vous donnerai le patron pour créer ces robes et pantalons traditionnels.", OfferRewardText_loc2 = "Voici les patrons, $N. Je suis sûr que vous trouverez le produit de cette connaissance plutôt joli." WHERE entry = 8878;
UPDATE locales_quest SET Details_loc2 = "Les grandes fusées de la Fête lunaire illuminent brillamment le ciel - seul le lanceur de chapelets rivalise avec leur magnificence !$B$BApportez-moi des pièces des ancêtres, $N, et je partagerai avec vous mes connaissances sur leur création.", OfferRewardText_loc2 = "Très bien - j'accepte ces pièces des ancêtres. Voici vos recettes, $N. Puissiez-vous les utiliser pour la gloire d'Elune !" WHERE entry = 8879;
UPDATE locales_quest SET OfferRewardText_loc2 = "Merci, $N. Voici la recette pour les grands chapelets de fusées. Puissent vos produits apporter joie et chance à tous ceux qui les utilisent.", RequestItemsText_loc2 = "Le grand lanceur de chapelets requiert beaucoup de ressources et de compétences pour être créé, mais sa brillance et sa beauté valent largement l'effort ! Apportez-moi des pièces des ancêtres, et je vous apprendrai comment les fabriquer." WHERE entry = 8881;
UPDATE locales_quest SET OfferRewardText_loc2 = "Voici votre schéma. Etudiez-le en détail, et apprenez...$B$BBonne chance, $N. Puissent vos célébrations rivaliser avec celles de la Fête lunaire elle-même !", RequestItemsText_loc2 = "Les plus beaux feux d'artifice doivent inclure des chapeles, et ces chapelets doivent être tirés depuis un lanceur de chapelets ! N'est-il donc pas logique pour vous d'apprendre le secret de fabrication de ces lanceurs de chapelets ? Apportez-moi des pièces des ancêtres et je vous offrirai cette connaissance." WHERE entry = 8882;
UPDATE locales_quest SET OfferRewardText_loc2 = "$N, bienvenue à Havre-de-nuit, hôte de la Fête lunaire ! Malgré que notre village soit d'habitude éloigné et isolé des peuples d'Azeroth, durant ce temps de fête, nous ouvrons nos bras et nos coeurs à tous.$B$BProfitez bien de votre visite, , et parlez à ma soeur ou moi-même à nouveau lorsque vous êtes prêt." WHERE entry = 8883;
