ALTER TABLE creature_text CHANGE COLUMN text text_fr longtext default NULL;
ALTER TABLE creature_text ADD COLUMN text_en longtext default NULL AFTER id;

UPDATE creature_text SET text_en = "And then the rabbit just bit his head off... I swear.", text_fr = "Et alors le lapin l'a mordu et lui a arraché la tête... Je le jure." WHERE entry = 1368 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "They say he can turn into a raven sometimes.", text_fr = "On dit qu'il se métamorphose parfois en corbeau." WHERE entry = 1368 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "And so the knights stood before the charging Horde and held their ground as a thousand berserk orcs came through the valley.", text_fr = "Les chevaliers firent face aux charges de la Horde et résistèrent à un millier d'orcs enragés qui déferlaient à travers la vallée." WHERE entry = 1368 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "You know there are crocolisks in the Canals. They were brought from the swamp as pets, but got thrown in the canals.", text_fr = "Tu sais qu'il y a des crocilisques dans les canaux. Les gens les ont capturés dans les marais pour s'en faire des animaux de compagnie et ont fini par les relâcher dans les canaux." WHERE entry = 1368 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "There is no spoon.", text_fr = "Il n'y a pas de cuillère." WHERE entry = 1368 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "You know why orc eyes glow red? It's because they drink blood!", text_fr = "Tu sais pourquoi les orcs ont des yeux rougeoyants ? Parce qu'ils boivent du sang !" WHERE entry = 1368 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "And that's how Lothar killed thirty six orcs with his bare hands!", text_fr = "Et c'est comme ça que Lothar a tué trente-six orcs à mains nues !" WHERE entry = 1368 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "Can you imagine?" WHERE entry = 1370 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Oh c'mon, that's not true", text_fr = "Allez, ce n'est pas vrai." WHERE entry = 1370 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "Really?", text_fr = "Vraiment ?" WHERE entry = 1370 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Wow." WHERE entry = 1370 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Oh yeah, I heard about that." WHERE entry = 1370 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "That reminds me of stories Billy is telling." WHERE entry = 1370 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "That's great.", text_fr = "C'est super." WHERE entry = 1370 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "Eww... that's not a fish!", text_fr = "Pouah... Ce n'est pas un poisson !" WHERE entry = 1371 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Something smells funny." WHERE entry = 1371 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "I think I see something." WHERE entry = 1371 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "I got worm guts on my shoes." WHERE entry = 1371 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "I hope that was a fish!" WHERE entry = 1371 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "I thought I heard something." WHERE entry = 1371 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "We catch the worm on the hook, the bait is immersed in water. The fish, our fish, is in water." WHERE entry = 1371 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "It's entirely the fault of these idiots soldiers of the Alliance. They had to go build their towers right behind my farm.", text_fr = "C'est entièrement leur faute à ces imbéciles de soldats de l'Alliance. Il fallait qu'ils aillent construire leurs tours juste derrière ma ferme." WHERE entry = 1395 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Could ye spare some coin?", text_fr = "Vous n'auriez pas une ou deux pièces ?" WHERE entry = 1395 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "I will gladly pay on Tuesday for a good steak today.", text_fr = "Je te paierai volontiers mardi pour avoir un bon steak aujourd'hui." WHERE entry = 1395 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "It's entirely the fault of these idiots of orcs. They had to burn my farm to ashes!", text_fr = "C'est entièrement leur faute à ces imbéciles d'orcs. Il fallait qu'ils réduisent ma ferme en cendres !" WHERE entry = 1395 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Alms for the poor?" WHERE entry = 1395 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "Charity?" WHERE entry = 1395 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "Here you are. What are the news from Westfall?" WHERE entry = 1754 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Mmh, that could be Shaw. I'll see what I can find. Go on, I'll be in touch." WHERE entry = 1754 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "VanCleef said that plans are on their way. But there are rumors about a spy." WHERE entry = 1755 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "The Defias will prevail! No one will stop us!" WHERE entry = 1755 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "Freshly baked bread for sale!" WHERE entry = 3518 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Warm, wholesome bread!" WHERE entry = 3518 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "I've heard of mice trapped in ale bottles before, but never in bread. P-p-please take everything and don't speak of this to anyone." WHERE entry = 3518 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Oh my... someone became ill from my bread? How can this be? Please, I hope my meager earnings are enough to help out." WHERE entry = 3518 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Freshly baked bread for sale!" WHERE entry = 3518 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "Fresh bread for sale!" WHERE entry = 3518 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "O'course I'm talkin to myself. Only way to get decent conversation in this city." WHERE entry = 3520 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "As if I don't have better things to do in my old age than carry buckets of water." WHERE entry = 3520 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "Where's the water, Emma? Get the water, Emma? If'n it weren't fer me, that lot wouldn't know what water looks like." WHERE entry = 3520 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Seems like a hundred times a day I walk all the way to the well to get more water. No respect for their elders I tell ya." WHERE entry = 3520 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Deja vu. For a moment, I thought I was back home... before the plague..." WHERE entry = 3520 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "Think I'm starting to wear a rut in the paving stones." WHERE entry = 3520 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "The only place in Stormwind where magic and spirits mix, come to the Blue Recluse!" WHERE entry = 3627 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Magical studies stressing your brain? Relax at the Blue Recluse!" WHERE entry = 3627 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "Free drinks at the Blue Recluse!" WHERE entry = 3627 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Feeling blue? Come on down to the Blue Recluse for a good time!" WHERE entry = 3627 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Lunch has arrived, my beautiful children. Tear them to pieces!" WHERE entry = 8127 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Rise and defend your master!" WHERE entry = 8127 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "The children of Sul will protect their master. Rise once more Sul'lithuz!" WHERE entry = 8127 AND groupid = 2 AND id = 0;
UPDATE creature_text SET text_en = "Follow me!" WHERE entry = 8516 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "Protect me while I'm busy with this idol." WHERE entry = 8516 AND groupid = 2 AND id = 0;
UPDATE creature_text SET text_en = "They're coming!" WHERE entry = 8516 AND groupid = 3 AND id = 0;
UPDATE creature_text SET text_en = "More are coming!" WHERE entry = 8516 AND groupid = 4 AND id = 0;
UPDATE creature_text SET text_en = "Their chief is there!" WHERE entry = 8516 AND groupid = 5 AND id = 0;
UPDATE creature_text SET text_en = "Goodbye." WHERE entry = 8516 AND groupid = 6 AND id = 0;
UPDATE creature_text SET text_en = "Defend the bunkers!" WHERE entry = 9457 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Our foes will fall!" WHERE entry = 9457 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "For the Horde!" WHERE entry = 9457 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Merry Christmas to all players of WoW Mania!" WHERE entry = 13445 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "This world is OURS!" WHERE entry = 14624 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Gakarah ma!" WHERE entry = 14624 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "The blood is our power!" WHERE entry = 14624 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Lok narash!" WHERE entry = 14624 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Lok'tar Illadari!" WHERE entry = 14624 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "We are the true Horde!" WHERE entry = 14624 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "For Kargath! For Victory!" WHERE entry = 14624 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "I am Gunnery Sergeant Hartman, your senior Drill Instructor." WHERE entry = 15199 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "The walls are shaking. Something is happening.." WHERE entry = 15362 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Malfurion Stormrage bows." WHERE entry = 15362 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "Be firm, champion. I know why you're here and what you are looking for. Eranikus will not give up easily its fragment. It was corrupted ... corrupted by the same as you want to destroy." WHERE entry = 15362 AND groupid = 2 AND id = 0;
UPDATE creature_text SET text_en = "Are you really surprised? Is it so hard to believe that the power of an Old God can extend up inside the dream? It's true, Eranikus, Tyrant of the Dream, is leading a battle against us. The Nightmare follows in its wake of destruction." WHERE entry = 15362 AND groupid = 3 AND id = 0;
UPDATE creature_text SET text_en = "Understand this, Eranikus wants nothing more than to be brought to Azeroth from the Dream. Once he is here, it will stop at nothing to destroy my physical manifestation. However, this is the only way to recover the scepter fragment." WHERE entry = 15362 AND groupid = 4 AND id = 0;
UPDATE creature_text SET text_en = "You will bring him back to this world, champion." WHERE entry = 15362 AND groupid = 5 AND id = 0;
UPDATE creature_text SET text_en = "Turn back while you can." WHERE entry = 16544 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "You will succeed only in damning yourselves!" WHERE entry = 16544 AND groupid = 2 AND id = 0;
UPDATE creature_text SET text_en = "This world is OURS!" WHERE entry = 17370 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Gakarah ma!" WHERE entry = 17370 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "The blood is our power!" WHERE entry = 17370 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Lok narash!" WHERE entry = 17370 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Lok'tar Illadari!" WHERE entry = 17370 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "We are the true Horde!" WHERE entry = 17370 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "For Kargath! For Victory!" WHERE entry = 17370 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "This world is OURS!" WHERE entry = 17371 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Gakarah ma!" WHERE entry = 17371 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "The blood is our power!" WHERE entry = 17371 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Lok narash!" WHERE entry = 17371 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Lok'tar Illadari!" WHERE entry = 17371 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "We are the true Horde!" WHERE entry = 17371 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "For Kargath! For Victory!" WHERE entry = 17371 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "This world is OURS!" WHERE entry = 17397 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Gakarah ma!" WHERE entry = 17397 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "The blood is our power!" WHERE entry = 17397 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Lok narash!" WHERE entry = 17397 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Lok'tar Illadari!" WHERE entry = 17397 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "We are the true Horde!" WHERE entry = 17397 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "For Kargath! For Victory!" WHERE entry = 17397 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "This world is OURS!" WHERE entry = 17414 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Gakarah ma!" WHERE entry = 17414 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "The blood is our power!" WHERE entry = 17414 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Lok narash!" WHERE entry = 17414 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Lok'tar Illadari!" WHERE entry = 17414 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "We are the true Horde!" WHERE entry = 17414 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "For Kargath! For Victory!" WHERE entry = 17414 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "Shadowmoon Technician begins to arm the proximity bomb!" WHERE entry = 17414 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "This world is OURS!" WHERE entry = 17491 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Gakarah ma!" WHERE entry = 17491 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "The blood is our power!" WHERE entry = 17491 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Lok narash!" WHERE entry = 17491 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Lok'tar Illadari!" WHERE entry = 17491 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "We are the true Horde!" WHERE entry = 17491 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "For Kargath! For Victory!" WHERE entry = 17491 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "This world is OURS!" WHERE entry = 17626 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Gakarah ma!" WHERE entry = 17626 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "The blood is our power!" WHERE entry = 17626 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Lok narash!" WHERE entry = 17626 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Lok'tar Illadari!" WHERE entry = 17626 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "We are the true Horde!" WHERE entry = 17626 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "For Kargath! For Victory!" WHERE entry = 17626 AND groupid = 0 AND id = 6;
UPDATE creature_text SET text_en = "Laughing Skull Legionaire enters in a crazy rage!", text_fr = "Légionnaire du Crâne ricanant entre dans une rage folle !" WHERE entry = 17626 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "3... 2... 1... BOOM!" WHERE entry = 17982 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "Thanks! How many times have you saved my life now? Three? That makes us blood in my book!" WHERE entry = 18369 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Eat me already! I can't take being locked up in this cage around you stinky, fat slobs." WHERE entry = 18445 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "You'll be in big troubles if I get out from here!" WHERE entry = 18445 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "Hey, what about eating?" WHERE entry = 18445 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "I want my daddy!" WHERE entry = 18445 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Thanks! I'm sure my daddy will give you a beautiful reward. Bye!" WHERE entry = 18445 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "This is the last time I get caught! Promise! Bye!" WHERE entry = 20812 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "Who dares to interrupt my operation?" WHERE entry = 21057 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "My blood will be the end of you!" WHERE entry = 21174 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "How long do you believe your pathetic sorcery can hold me?" WHERE entry = 21174 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "Away, you mindless parasites! My blood is my own!" WHERE entry = 21174 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Illidan is an arrogant fool! I will crush him and reclaim Outland as my own!" WHERE entry = 21174 AND groupid = 0 AND id = 3;
UPDATE creature_text SET text_en = "Vermin! Leeches! Take my blood and choke on it!" WHERE entry = 21174 AND groupid = 0 AND id = 4;
UPDATE creature_text SET text_en = "Wretched, meddling insects! Release me, and perhaps I will grant you a merciful death!" WHERE entry = 21174 AND groupid = 0 AND id = 5;
UPDATE creature_text SET text_en = "Gross!" WHERE entry = 22314 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "I think those weird bird guys were going to eat us. Gross!" WHERE entry = 22314 AND groupid = 0 AND id = 1;
UPDATE creature_text SET text_en = "Yay! We love you! You saved us!" WHERE entry = 22314 AND groupid = 0 AND id = 2;
UPDATE creature_text SET text_en = "Ashtongue Battlelord goes berserk!" WHERE entry = 22844 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "[PH] Totem" WHERE entry = 23093 AND groupid = 0 AND id = 0;
UPDATE creature_text SET text_en = "[PH] Air Acolyte" WHERE entry = 23093 AND groupid = 1 AND id = 0;
UPDATE creature_text SET text_en = "[PH] Water Acolyte" WHERE entry = 23093 AND groupid = 2 AND id = 0;
UPDATE creature_text SET text_en = "[PH] Earth Acolyte" WHERE entry = 23093 AND groupid = 3 AND id = 0;
UPDATE creature_text SET text_en = "[PH] Fire Acolyte" WHERE entry = 23093 AND groupid = 4 AND id = 0;
UPDATE creature_text SET text_en = "[PH] Flawless Arcane Elemental" WHERE entry = 23093 AND groupid = 5 AND id = 0;
