UPDATE script_texts SET content_loc2 = "est pris de frénésie meurtrière !" WHERE entry = -1000001;
UPDATE script_texts SET content_loc2 = "entre dans une folie furieuse !" WHERE entry = -1000004;
UPDATE script_texts SET content_loc2 = "REUTILISEZ-MOI" WHERE entry = -1000005;
UPDATE script_texts SET content_loc2 = "Venez, mes petits. Affrontez-moi !" WHERE entry = -1000100;
UPDATE script_texts SET content_loc2 = "Suivez moi, $N. Je vais vous conduire à la cachette des Défias. Mais vous feriez mieux de me protéger ou je serai bientôt mort." WHERE entry = -1000101;
UPDATE script_texts SET content_loc2 = "L'entrée est cachée ici dans Ruisselune. Gardez vos yeux grands ouverts à cause des voleurs. Ils me veulent mort." WHERE entry = -1000102;
UPDATE script_texts SET content_loc2 = "Vous pouvez aller dire à Roidemantel que c'est ici que le gang Défias se terre, $N." WHERE entry = -1000103;
UPDATE script_texts SET content_loc2 = "%s arrive rapidement ! Préparez vous à combattre !" WHERE entry = -1000104;
UPDATE script_texts SET content_loc2 = "À l'aide !" WHERE entry = -1000105;
UPDATE script_texts SET content_loc2 = "Est ce que tout le monde est prêt ?" WHERE entry = -1000106;
UPDATE script_texts SET content_loc2 = "D'accord, allons-y !" WHERE entry = -1000107;
UPDATE script_texts SET content_loc2 = "Tenez-vous prêt. Aile-Argent est juste à la sortie de ce virage." WHERE entry = -1000108;
UPDATE script_texts SET content_loc2 = "Aile-Argent est à nous !" WHERE entry = -1000109;
UPDATE script_texts SET content_loc2 = "Allez faire votre rapport, et dites que l'avant-poste est à nous. Nous, nous resterons ici." WHERE entry = -1000110;
UPDATE script_texts SET content_loc2 = "Notre maison est par ici, à travers le bosquet." WHERE entry = -1000111;
UPDATE script_texts SET content_loc2 = "Aidez-moi !" WHERE entry = -1000112;
UPDATE script_texts SET content_loc2 = "Ma pauvre famille. Tout a été détruit." WHERE entry = -1000113;
UPDATE script_texts SET content_loc2 = "Père ! Père ! Tu es en vie !" WHERE entry = -1000114;
UPDATE script_texts SET content_loc2 = "Tu peux remercier $N de m'avoir ramené ici sain et sauf, père." WHERE entry = -1000115;
UPDATE script_texts SET content_loc2 = "serre son père dans ses bras." WHERE entry = -1000116;
UPDATE script_texts SET content_loc2 = "Merci d'avoir accepté de nous aider. Maintenant, sortons d'ici $N." WHERE entry = -1000117;
UPDATE script_texts SET content_loc2 = "Par ici ! Ils nous suivent !" WHERE entry = -1000118;
UPDATE script_texts SET content_loc2 = "Accordez-moi un moment de repos. Le voyage a raison du peu de force qui me reste." WHERE entry = -1000119;
UPDATE script_texts SET content_loc2 = "Vous avez entendu quelque chose ?" WHERE entry = -1000120;
UPDATE script_texts SET content_loc2 = "Le Guet de l'Épervier, enfin ! Maintenant, où est mon... Oh non ! Mon paquet a disparu ! Où est..." WHERE entry = -1000121;
UPDATE script_texts SET content_loc2 = "Vous ne m'empêcherez pas d'arriver au Guet de l'Épervier !" WHERE entry = -1000122;
UPDATE script_texts SET content_loc2 = "C'est quand vous voulez, $c." WHERE entry = -1000123;
UPDATE script_texts SET content_loc2 = "La Dispute a commencé. $n, soyez prêt à combattre !" WHERE entry = -1000124;
UPDATE script_texts SET content_loc2 = "Vous ! Entrez dans l'arène !" WHERE entry = -1000125;
UPDATE script_texts SET content_loc2 = "Le challenger est au sol !" WHERE entry = -1000126;
UPDATE script_texts SET content_loc2 = "La Dispute est terminée." WHERE entry = -1000127;
UPDATE script_texts SET content_loc2 = "Nous avons besoin de vous pour envoyer des renforts à la Manaforge Duro, Ardonis. Ce n'est pas une demande, c'est un ordre." WHERE entry = -1000128;
UPDATE script_texts SET content_loc2 = "Vous ne pouvez pas être sérieux ! Nous sommes déjà à court de personnel et nous pouvons à peine garder la Manaforge fonctionnelle !" WHERE entry = -1000129;
UPDATE script_texts SET content_loc2 = "Vous ferez comme on vous l'a demandé. La Manaforge Duro subit déjà une lourde attaque par les créatures de mana et la situation est hors de contrôle. L'échec ne sera pas toléré !" WHERE entry = -1000130;
UPDATE script_texts SET content_loc2 = "En effet, ce n'est pas une demande." WHERE entry = -1000131;
UPDATE script_texts SET content_loc2 = "Mon seigneur !" WHERE entry = -1000132;
UPDATE script_texts SET content_loc2 = "Duro recevra des renforts ! Ultris a été un désastre complet. Je ne veux pas répéter cette erreur !" WHERE entry = -1000133;
UPDATE script_texts SET content_loc2 = "Nous avons eu un trop grand nombre de revers tout au long de notre route : la citadelle des Flammes infernales, la Crête Tombeciel, la Halte Aile-de-Feu... Le Prince Kael'thas ne tolérera pas d'autre retard. Je ne tolèrerai rien  d'autre qu'une réussite totale !" WHERE entry = -1000134;
UPDATE script_texts SET content_loc2 = "Je vais retourner au Donjon de la Tempête. Veillez à ce que je n'aie aucune raison de revenir !" WHERE entry = -1000135;
UPDATE script_texts SET content_loc2 = "Oui, mon seigneur !" WHERE entry = -1000136;
UPDATE script_texts SET content_loc2 = "Nous nous reverrons la-bas, Ardonis !" WHERE entry = -1000137;
UPDATE script_texts SET content_loc2 = "La magie d'Avruu... elle me contrôle toujours. Vous devez me combattre, mortel. C'est la seule façon de briser le charme !" WHERE entry = -1000138;
UPDATE script_texts SET content_loc2 = "La magie d'Avruu est cassée ! Je suis de nouveau libre !" WHERE entry = -1000139;
UPDATE script_texts SET content_loc2 = "Allons-y." WHERE entry = -1000140;
UPDATE script_texts SET content_loc2 = "$N, nous allons utiliser l'antichambre sur la droite." WHERE entry = -1000141;
UPDATE script_texts SET content_loc2 = "Je peux voir la lumière au bout du tunnel !" WHERE entry = -1000142;
UPDATE script_texts SET content_loc2 = "Voici l'Enclave des Péregrins, $C. Plus beaucoup de chemin à parcourir... Regardez ! Une embuscade de Trolls !" WHERE entry = -1000143;
UPDATE script_texts SET content_loc2 = "Merci de m'avoir sauvé la vie et de m'avoir ramené en lieu sur, $N." WHERE entry = -1000144;
UPDATE script_texts SET content_loc2 = "Liatha, que quelqu'un s'occupe de vos blessures. Merci de l'avoir ramenée en sécurité." WHERE entry = -1000146;
UPDATE script_texts SET content_loc2 = "Allons-y, $N. Je suis prêt à aller jusqu'au Poste de Blanc-relais." WHERE entry = -1000147;
UPDATE script_texts SET content_loc2 = "Ça me semble sûr. Si nous allons vers l'est, nous allons sans doute... Aah ! Une attaque de wyvernes !" WHERE entry = -1000148;
UPDATE script_texts SET content_loc2 = "Merci beaucoup... A partir d'ici, je devrais me débrouiller pour rentrer au Poste de Blanc-relais. Parlez à Motega Crin-de-feu, peut-être pourrez-vous le convaincre de me renvoyer chez moi." WHERE entry = -1000149;
UPDATE script_texts SET content_loc2 = "Salutations, $N. Je serai votre guide pour traverse cette caverne. Essayez de bien me suivre." WHERE entry = -1000150;
UPDATE script_texts SET content_loc2 = "Nous ne savons pas si les Grottes du Temps ont toujours été accessibles aux mortels. Honnêtement, il est impossible de le savoir puisque l'Intemporel est en mouvement perpétuel, modifiant nos voies temporelles pour les adapter à sa guise. Ce que vous voyez aujourd'hui peut très bien ne plus exister demain. Il se peut que vous vous réveillez et ne vous souvenez pas de cet endroit." WHERE entry = -1000151;
UPDATE script_texts SET content_loc2 = "C'est étrange, je le sais... La plupart des mortels ne peuvent comprendre ce qu'ils voient ici car, le plus souvent, ce qu'ils voient n'est pas ancré dans leur perception de la réalité." WHERE entry = -1000152;
UPDATE script_texts SET content_loc2 = "Suivez moi s'il vous plait." WHERE entry = -1000153;
UPDATE script_texts SET content_loc2 = "L'univers sera redéfini. Il n'y a ici que 2 vérités à apprendre: Tout d'abord, que le temps est chaotique, toujours en mouvement, en perpétuel changement et ensuite, que notre perception ne définit pas la réalité" WHERE entry = -1000154;
UPDATE script_texts SET content_loc2 = "En tant que gardiens du temps, nous surveillons et nous occupons du royaume de Nozdormu. Le maitre est absent pour le moment, ce qui signifie que quelqu'un tente de gravement influencer le temps. Le maitre n'interfère jamais dans les affaires des mortels, mais corrige plutôt les altérations faites par d'autres dans le flot du temps. A ce niveau, il est intransigeant." WHERE entry = -1000155;
UPDATE script_texts SET content_loc2 = "Pour l'entretien habituel du temps, les Gardiens du Temps sont suffisants. Nous sommes en mesure de faire face à la plupart des troubles. Je parle de petites choses, comme des mages renégats qui veulent changer quelque chose dans le passé et élever leur statut ou richesse dans le présent." WHERE entry = -1000156;
UPDATE script_texts SET content_loc2 = "Ces tunnels que vous voyez sont appelés couloirs du temps. Ils sont en nombre infini. Ceux qui existent actuellement dans la réalité sont ceux que le maître a estimé être des \"points de troubles\". Ces points de troubles peuvent être complètement différents, mais ils servent toujours le même but. Leur existence est le résultat d'une même perturbation du temps. Rappelez-vous en si vous vous aventurez dans l'un d'eux ..." WHERE entry = -1000157;
UPDATE script_texts SET content_loc2 = "Cette route est en grand péril ! Nous avons des agents à l'intérieur qui tentent de rétablir l'ordre en ce moment. D'après mes sources, la liberté de Thrall est en danger. Une organisation maléfique connue sous le nom de Vol Infini tente d'empêcher son évasion. Je crains que sans une aide extérieure, tout sera perdu." WHERE entry = -1000158;
UPDATE script_texts SET content_loc2 = "Nous avons très peu d'informations sur cette voie temporelle. Sa'at a été envoyé et est actuellement à l'intérieur. La seule information que nous avons collecté de ses rapports est que le Vol infini tente une nouvelle fois de modifier le temps. Serait-il possible que l'ouverture de la Porte des Ténèbres soit la cible d'actes de sabotage ? Espérons que non ..." WHERE entry = -1000159;
UPDATE script_texts SET content_loc2 = "Ce passage est effondré pour le moment. Ce qu'il peut conserver de notre passé, présent, et avenir est actuellement inconnu ..." WHERE entry = -1000160;
UPDATE script_texts SET content_loc2 = "Les couloirs du temps sont actuellement rangés par ordre de catastrophes. Notez qu'ils sont tous classés comme catastrophiques, ce qui signifie que si l'un d'eux s'effondrait, le monde prendrait fin. Nous les avons classé de cette manière pour que les héros et les aventuriers qui sont envoyés ici sachent quelle route convient le mieux à leurs capacités." WHERE entry = -1000161;
UPDATE script_texts SET content_loc2 = "Tous ce que nous savons de ce passage est qu'il mène au mont Hyjal. Les dragons du Vol Infini ont fait de grands efforts pour nous empêcher d'y participer. Nous ne savons presque rien, mortel. Soridormi tente actuellement de percer les défenses du passage mais ses tentatives ont été infructueuses jusque là. Vous êtes peut-être notre seul espoir de résoudre le conflit." WHERE entry = -1000162;
UPDATE script_texts SET content_loc2 = "Ah, $GPrêtre:Prêtresse;, vous arrivez juste à temps. J’apprécie cela." WHERE entry = -1000164;
UPDATE script_texts SET content_loc2 = "Merci ! Merci,  $GPrêtre:Prêtresse;. Maintenant, je peux prendre le pas sur ces gnolls avec votre pouvoir pour me soutenir !" WHERE entry = -1000165;
UPDATE script_texts SET content_loc2 = "Adieu, et que l'ombre vous protège à jamais !" WHERE entry = -1000166;
UPDATE script_texts SET content_loc2 = "Merci ! Merci,  $GPrêtre:Prêtresse;. Maintenant je peux prendre le pas sur ces murlocs avec la Lumière de mon coté !" WHERE entry = -1000167;
UPDATE script_texts SET content_loc2 = "Adieu, et que la Lumière soit toujours avec vous." WHERE entry = -1000168;
UPDATE script_texts SET content_loc2 = "Merci ! Merci,  $GPrêtre:Prêtresse;. Maintenant je peux prendre le pas sur ces humains avec votre pouvoir pour me soutenir !" WHERE entry = -1000169;
UPDATE script_texts SET content_loc2 = "Adieu, et que les ancêtres soit toujours à vos cotés !" WHERE entry = -1000170;
UPDATE script_texts SET content_loc2 = "Merci ! Merci, $GPrêtre:Prêtresse;. Maintenant je peux prendre le pas sur ces Wendigo avec la Lumière de mon coté !" WHERE entry = -1000171;
UPDATE script_texts SET content_loc2 = "Adieu, et que la Lumière soit toujours à vos cotés." WHERE entry = -1000172;
UPDATE script_texts SET content_loc2 = "Merci ! Merci, $GPrêtre:Prêtresse;. Maintenant je peux prendre le pas sur ces sylvains corrompus avec le pouvoir d'Elune pour me soutenir !" WHERE entry = -1000173;
UPDATE script_texts SET content_loc2 = "Adieu, et que Elune soit toujours à vos cotés." WHERE entry = -1000174;
UPDATE script_texts SET content_loc2 = "A-Me gentille. Gentille A-me. Suivre... A-ME suivre. Maison. A-ME rentre à la maison." WHERE entry = -1000200;
UPDATE script_texts SET content_loc2 = "Méchant Marteleur d'Un Goro. Marteleur démoniaque." WHERE entry = -1000201;
UPDATE script_texts SET content_loc2 = "Gentille.. gentille, A-ME. Maison. Chercher une route." WHERE entry = -1000202;
UPDATE script_texts SET content_loc2 = "A-ME maison. A-ME va maison ! Seigneur du goudron ne dérange pas A-ME." WHERE entry = -1000203;
UPDATE script_texts SET content_loc2 = "A-ME pas taper Seigneur du goudron. A-ME gentille." WHERE entry = -1000204;
UPDATE script_texts SET content_loc2 = "A-ME maison! Gentille A-ME! Gentille A-ME. à maison. Maison. Maison" WHERE entry = -1000205;
UPDATE script_texts SET content_loc2 = "Venez, $N. Le seigneur Hurlorage ne va pas tarder." WHERE entry = -1000206;
UPDATE script_texts SET content_loc2 = "Le Seigneur Illidan va arriver." WHERE entry = -1000207;
UPDATE script_texts SET content_loc2 = "Seigneur Illidan, voici le Gueule-de-dragon dont moi, et les autres, vous avons parlé. Il va nous mener à la victoire !" WHERE entry = -1000208;
UPDATE script_texts SET content_loc2 = "Mais... Monseigneur, je ne comprends pas. $N... Il est l'orc qui a..." WHERE entry = -1000209;
UPDATE script_texts SET content_loc2 = "Ce sera fait, monseigneur." WHERE entry = -1000210;
UPDATE script_texts SET content_loc2 = "Alors vous croyiez pouvoir vous moquer de Mor'ghor, hein ? Avant que vous soyiez livré au Seigneur Illidan, vous allez ressentir une douleur que vous ne croyiez pas possible. Je vais prendre plaisir à exercer ma propre vengeance." WHERE entry = -1000211;
UPDATE script_texts SET content_loc2 = "Guerriers Gueule-de-dragon, écoutez-moi ! Un de vous a obtenu le rang de Grand Seigneur ! Inclinez vos têtes en signe de révérence ! Montrez votre respect et votre allégeance au Seigneur $N !" WHERE entry = -1000212;
UPDATE script_texts SET content_loc2 = "Tous te saluent, Seigneur Illidan !" WHERE entry = -1000213;
UPDATE script_texts SET content_loc2 = "Que signifie tout ceci, Mor'ghor ?" WHERE entry = -1000214;
UPDATE script_texts SET content_loc2 = "SILENCE !" WHERE entry = -1000215;
UPDATE script_texts SET content_loc2 = "Espèce d'idiot. Tu n'es qu'un bouffon incompétent..." WHERE entry = -1000216;
UPDATE script_texts SET content_loc2 = "CECI est ton héros ?" WHERE entry = -1000217;
UPDATE script_texts SET content_loc2 = "Tu as été trompé, imbécile." WHERE entry = -1000218;
UPDATE script_texts SET content_loc2 = "Cette... opération... toute entière... A ÉTÉ COMPROMISE !" WHERE entry = -1000219;
UPDATE script_texts SET content_loc2 = "Je m'attends à voir la carcasse de cet insecte en morceaux dans mon antre dans l'heure. Echoue et tu vivras un destin bien pire que la mort." WHERE entry = -1000220;
UPDATE script_texts SET content_loc2 = "Vous ne ferez aucun mal au garçon, Mor'ghor. Vite, $N, grimpez sur mon dos !" WHERE entry = -1000221;
UPDATE script_texts SET content_loc2 = "Merci, mortel." WHERE entry = -1000222;
UPDATE script_texts SET content_loc2 = "Je sens les esprits torturés, $N. Ils sont sur la route, et arrivent rapidement !" WHERE entry = -1000223;
UPDATE script_texts SET content_loc2 = "Attention !" WHERE entry = -1000224;
UPDATE script_texts SET content_loc2 = "Des attaquants Naga! Défendez-vous!" WHERE entry = -1000225;
UPDATE script_texts SET content_loc2 = "Tuez-les tous !" WHERE entry = -1000226;
UPDATE script_texts SET content_loc2 = "Accordez-moi votre protection $N, il faut briser leur cuve de magie immonde!" WHERE entry = -1000228;
UPDATE script_texts SET content_loc2 = "Les nagas de Glissentaille font preuve d'une cruauté inouïe à leurs prisonniers. C'est un miracle que j'aie pu survivre dans cette prison aquatique aussi longtemps. Louée soit la déesse de la Terre !" WHERE entry = -1000229;
UPDATE script_texts SET content_loc2 = "Et maintenant, il faut que nous trouvions la sortie." WHERE entry = -1000230;
UPDATE script_texts SET content_loc2 = "Dame Vashj doit répondre des atrocités qu'elle a commises. Elle doit être traduite en justice !" WHERE entry = -1000231;
UPDATE script_texts SET content_loc2 = "La nature tumultueuse des grands cours d'eau d'Azeroth et Draenor sont une conséquence directe des esprits tourmentés de l'eau." WHERE entry = -1000232;
UPDATE script_texts SET content_loc2 = "Merci, $N. S'il vous plaît retournez voir mes frères à l'Autel de damnation, à proximité de la main de Gul'dan, et dites-leur que Wilda est sûr. Que la Terre-mère veille sur vous ..." WHERE entry = -1000234;
UPDATE script_texts SET content_loc2 = "Ok, $N. Suivez-moi jusqu'à la grotte où je vais tenter d'exploiter la puissance de la rune dans ces lunettes." WHERE entry = -1000235;
UPDATE script_texts SET content_loc2 = "J'ai découvert cette grotte dès notre premier jour ici. Je crois que l'énergie de la pierre peut être utilisée à notre avantage." WHERE entry = -1000236;
UPDATE script_texts SET content_loc2 = "Je vais commencer à examiner l'énergie de la pierre. Votre travail, $N, est de me défendre. Cet endroit est maudit ... croyez-moi." WHERE entry = -1000237;
UPDATE script_texts SET content_loc2 = "commence à bricoler avec les lunettes devant la pierre." WHERE entry = -1000238;
UPDATE script_texts SET content_loc2 = "A l'aide ! Enlevez-moi ces choses afin que je puisse faire mon travail!" WHERE entry = -1000239;
UPDATE script_texts SET content_loc2 = "Presque fini! Il me faut encore un peu de temps !" WHERE entry = -1000240;
UPDATE script_texts SET content_loc2 = "Je l'ai fait! J'ai transféré la puissance de la pierre dans les lunettes de protection! Sortons d'ici!" WHERE entry = -1000241;
UPDATE script_texts SET content_loc2 = "Ouf! Heureux de quitter cette grotte effrayante." WHERE entry = -1000242;
UPDATE script_texts SET content_loc2 = "tends une paire de lunettes éclatante au docteur Draunessieu." WHERE entry = -1000243;
UPDATE script_texts SET content_loc2 = "Docteur Draunessieu vous donnera de plus amples instructions, $N. Un grand merci pour votre aide!" WHERE entry = -1000244;
UPDATE script_texts SET content_loc2 = "Vous, là-bas ! Lâchez cette pierre de lune et personne ne sera blessé !" WHERE entry = -1000245;
UPDATE script_texts SET content_loc2 = "Calmez-vous !" WHERE entry = -1000246;
UPDATE script_texts SET content_loc2 = "OK, vous avez gagné ! Je me rends ! Mais ne me faites pas de mal !" WHERE entry = -1000247;
UPDATE script_texts SET content_loc2 = "Je me souviens du vaisseau qui tombait. Nous avons couru jusqu'aux capsules... Je vais voir si je peux aider les autres. Merci !" WHERE entry = -1000248;
UPDATE script_texts SET content_loc2 = "Vous m'avez sauvé, $C ! J'ai une dette envers vous, je ne pourrais jamais vous remercier assez. Je vais aller voir si je peux aider les autres." WHERE entry = -1000250;
UPDATE script_texts SET content_loc2 = "Urgh… quel est cet endroit ? Est-ce l'épave du vaisseau que je vois là-bas ?" WHERE entry = -1000251;
UPDATE script_texts SET content_loc2 = "Oh, j'ai mal…" WHERE entry = -1000252;
UPDATE script_texts SET content_loc2 = "J'ai mal partout. Soulagez-moi, par pitié !" WHERE entry = -1000253;
UPDATE script_texts SET content_loc2 = "Aaaah… J'ai mal. Pouvez-vous m'aider ?" WHERE entry = -1000254;
UPDATE script_texts SET content_loc2 = "Je ne sais pas si je vais m'en sortir. Aidez-moi, je vous en prie…" WHERE entry = -1000255;
UPDATE script_texts SET content_loc2 = "Oui maître, tout se passe comme prévu." WHERE entry = -1000256;
UPDATE script_texts SET content_loc2 = "met le coquillage à son oreille." WHERE entry = -1000257;
UPDATE script_texts SET content_loc2 = "Et maintenant, je vous découpe !" WHERE entry = -1000258;
UPDATE script_texts SET content_loc2 = "Quelle est cette idée géniale ?" WHERE entry = -1000259;
UPDATE script_texts SET content_loc2 = "Quelle est cette grande idée? Vous avez presque fait sauter ma couverture, idiot! Je vous ai dit de mettre la boussole et les cartes de navigation dans un endroit sûr - pas à l'air libre pour que n'importe quel imbécile puisse les découvrir." WHERE entry = -1000260;
UPDATE script_texts SET content_loc2 = "Le Maître a fait de grands efforts pour obtenir des renseignements sur la localisation de l'Exodar. Vous pourriez avoir fait sauté toute l'opération, y compris la couverture de notre espion à l'intérieur." WHERE entry = -1000261;
UPDATE script_texts SET content_loc2 = "Détendez-vous? Savez-vous ce que Kael'thas réserve à ceux qui manquent leur mission, Geezle? Souffrance et douleur éternelle ... Ne faites PAS rater le plan, imbécile." WHERE entry = -1000263;
UPDATE script_texts SET content_loc2 = "Nos éclaireurs de Brume-sang ont situé notre contact. Le fou, Velen, va bientôt être seul et sans défense - assez longtemps pour faire grève! Maintenant, sortez de ma vue avant que je vous atomise ..." WHERE entry = -1000264;
UPDATE script_texts SET content_loc2 = "Oui, monsieur. Ça n'arrivera plus..." WHERE entry = -1000265;
UPDATE script_texts SET content_loc2 = "prend le drapeau des nagas." WHERE entry = -1000266;
UPDATE script_texts SET content_loc2 = "Je serais prêt quand vous le serez, $Gguerrier:guerrière;." WHERE entry = -1000267;
UPDATE script_texts SET content_loc2 = "La bagarre a commencé, préparez-vous à combattre!" WHERE entry = -1000268;
UPDATE script_texts SET content_loc2 = "Vous! Entrez dans la mêlée!" WHERE entry = -1000269;
UPDATE script_texts SET content_loc2 = "L'ennemi est à terre !" WHERE entry = -1000270;
UPDATE script_texts SET content_loc2 = "La bagarre est terminée." WHERE entry = -1000271;
UPDATE script_texts SET content_loc2 = "Bon, d'accord, je pense que je peux comprendre comment faire fonctionner ce truc ..." WHERE entry = -1000272;
UPDATE script_texts SET content_loc2 = "Arrrgh ! Ce n'est pas bon !" WHERE entry = -1000273;
UPDATE script_texts SET content_loc2 = "Bon, je crois que je l'ai, maintenant. Suivez-moi, $N!" WHERE entry = -1000274;
UPDATE script_texts SET content_loc2 = "C'est la déchiqueteuse volée! Arrêtez ça ou Trimballast aura notre peau!" WHERE entry = -1000275;
UPDATE script_texts SET content_loc2 = "On dirait que nous sommes sortis des bois, hein? Je me demande ce que ça fait ..." WHERE entry = -1000276;
UPDATE script_texts SET content_loc2 = "Allons, n'abandonnez pas maintenant!" WHERE entry = -1000277;
UPDATE script_texts SET content_loc2 = "De justesse ! Eh bien, allons-y, il y a encore beaucoup de route jusqu'à Cabestan !" WHERE entry = -1000278;
UPDATE script_texts SET content_loc2 = "Hmm ... Je ne pense pas que ce feu rouge clignotant soit une bonne chose ..." WHERE entry = -1000279;
UPDATE script_texts SET content_loc2 = "Merci cher paladin, vous m'avez sauvé la vie." WHERE entry = -1000280;
UPDATE script_texts SET content_loc2 = "Très bien. Voyons voir ce que vous avez à me montrer, $N." WHERE entry = -1000281;
UPDATE script_texts SET content_loc2 = "Quelle sorte de traquenard est-ce, $R ? Si vous cherchez à me tendre un piège, je vous préviens que je ne vais pas me laisser faire!" WHERE entry = -1000282;
UPDATE script_texts SET content_loc2 = "libère le reste de son énergie dans la pierre runique, et la réactive avec succès." WHERE entry = -1000283;
UPDATE script_texts SET content_loc2 = "Déploiement réussi. Les intrus seront neutralisés." WHERE entry = -1000284;
UPDATE script_texts SET content_loc2 = "Objectif acquis. Initialisation des routines de sécurité." WHERE entry = -1000285;
UPDATE script_texts SET content_loc2 = "Une ombreuse, une sinistre présence a envahi le Rêve d'émeraude. Sa puissance est sur le point de déferler sur notre monde, $N. Nous devons nous y opposer! C'est pourquoi je ne peux pas vous accompagner en personne." WHERE entry = -1000286;
UPDATE script_texts SET content_loc2 = "Le Rêve d’Émeraude ne vous appartiendra jamais !" WHERE entry = -1000287;
UPDATE script_texts SET content_loc2 = "Partez de cet endroit !" WHERE entry = -1000288;
UPDATE script_texts SET content_loc2 = "C'est la première relique, mais il y en a encore deux de plus. Suivez-moi, $N." WHERE entry = -1000289;
UPDATE script_texts SET content_loc2 = "J'ai récupéré la deuxième relique. Prenez un moment pour vous reposer, et puis nous irons chercher la dernière." WHERE entry = -1000290;
UPDATE script_texts SET content_loc2 = "Nous avons les trois reliques, mais mon énergie s'estompe rapidement. Nous devons retourner auprès du Garderêve Lurosa! Il vous dira quoi faire ensuite." WHERE entry = -1000291;
UPDATE script_texts SET content_loc2 = "Lurosa, je confie les reliques d'Aviana à $N, qui les mènera à Morthis Murmedaile. Je dois retourner au Rêve d'émeraude maintenant. Ne laissez pas $N échouer !" WHERE entry = -1000292;
UPDATE script_texts SET content_loc2 = "En Nagrand, bouffe chasser ogre !" WHERE entry = -1000293;
UPDATE script_texts SET content_loc2 = "Avec un peu de sel et de poivre, vous avoir bon goût." WHERE entry = -1000294;
UPDATE script_texts SET content_loc2 = "D'accord, d'accord, Gros-tas laisser tomber." WHERE entry = -1000295;
UPDATE script_texts SET content_loc2 = "Attention! Processus d'arrêt d'urgence lancé par $N. l'arrêt s'achèvera dans deux minutes." WHERE entry = -1000296;
UPDATE script_texts SET content_loc2 = "L'arrêt d'urgence sera complété dans une minute." WHERE entry = -1000297;
UPDATE script_texts SET content_loc2 = "L'arrêt d'urgence sera complété dans trente secondes." WHERE entry = -1000298;
UPDATE script_texts SET content_loc2 = "L'arrêt d'urgence sera complété dans dix secondes." WHERE entry = -1000299;
UPDATE script_texts SET content_loc2 = "L'arrêt d'urgence est terminé." WHERE entry = -1000300;
UPDATE script_texts SET content_loc2 = "L'arrêt d'urgence est abandonné." WHERE entry = -1000301;
UPDATE script_texts SET content_loc2 = "Saeed est actuellement engagé ou en attente d'ordres. Vous devriez vous rendre à l'est d'ici et voir si Saeed vous attend. S'il n'est pas présent, alors il lutte dans une autre bataille. Je vous recommande d'attendre son retour avant d'attaquer Dimensius." WHERE entry = -1000302;
UPDATE script_texts SET content_loc2 = "est très faible." WHERE entry = -1000303;
UPDATE script_texts SET content_loc2 = "Marguerite, est-ce toi ?" WHERE entry = -1000304;
UPDATE script_texts SET content_loc2 = "Merci pour avoir ramené ma Marguerite, $N. Je ne pourrais pas vivre sans elle !" WHERE entry = -1000305;
UPDATE script_texts SET content_loc2 = "Suivez-moi, étranger. Ce ne sera pas long." WHERE entry = -1000306;
UPDATE script_texts SET content_loc2 = "Shattrath fut jadis la capitale draeneï de ce monde. Son nom signifie \"demeure de la lumière.\"" WHERE entry = -1000307;
UPDATE script_texts SET content_loc2 = "Lorsque la Légion ardente tourna les orcs contre les draeneï, la plus féroce bataille a fût menée ici. Les draeneï se sont battus bec et ongles, mais à la fin, la ville tomba." WHERE entry = -1000308;
UPDATE script_texts SET content_loc2 = "La ville fût abandonnée, en ruines et sombrant dans l'obscurité ... jusqu'à ce que le Sha'tar arrive." WHERE entry = -1000309;
UPDATE script_texts SET content_loc2 = "Entrons dans la Basse-Ville. Je vous préviens que comme c'est l'un des seul paradis sûrs dans l'Outreterre, Shattrath a attiré une foule de réfugiés en provenance de toutes les guerres, actuelles et passés." WHERE entry = -1000310;
UPDATE script_texts SET content_loc2 = "Les Sha'tar, ou \"né de la lumière\" sont les naaru venus en Outreterre pour combattre les démons de la Légion ardente." WHERE entry = -1000311;
UPDATE script_texts SET content_loc2 = "Ils ont été attirés par les ruines de Shattrath où un petit groupe de prêtres draeneï menaient ses rites l'intérieur d'un temple en ruines, à cet endroit même." WHERE entry = -1000312;
UPDATE script_texts SET content_loc2 = "Le sacerdoce, connu sous le nom de l'Aldor, reprit rapidement sa force, et la nouvelle se répandit que les naaru étaient de retour et commençaient la reconstruction. Le temple en ruine est maintenant utilisé comme une infirmerie pour les réfugiés blessés." WHERE entry = -1000313;
UPDATE script_texts SET content_loc2 = "Il ne fallu pas attendre longtemps, cependant, avant que la ville soit attaquée une fois de plus. Cette fois, l'attaque venait des armées d'Illidan. Un important régiment d'elfes de sang avait été envoyé par l'allié d'Illidan, Kael'thas Haut-soleil, pour dévaster la ville." WHERE entry = -1000314;
UPDATE script_texts SET content_loc2 = "Comme le régiment d'elfes de sang traversait le pont, les exarques de l'Aldor et les redresseurs de torts étaient alignés pour défendre la Terrasse de la Lumière. Mais alors, l'inattendu se produisit." WHERE entry = -1000315;
UPDATE script_texts SET content_loc2 = "Les elfes de sang déposèrent leurs armes devant les défenseurs de la ville; leur chef, un ancien elfe de sang connu sous le nom Voren'thal, fit irruption dans la Terrasse de la Lumière et demanda à parler à A'dal." WHERE entry = -1000316;
UPDATE script_texts SET content_loc2 = "Comme le naaru s'approchait de lui, Voren'thal s'agenouilla devant lui et prononça les paroles suivantes:. \"Je vous ai vu dans une vision, naaru. Le seul espoir pour la survie de ma race réside en vous. Mes disciples et moi sommes ici pour vous servir.. \"" WHERE entry = -1000317;
UPDATE script_texts SET content_loc2 = "La défection de Voren'thal et de ses disciples était la plus grosse perte jamais subie par les forces de Kael. Et ce n'étaient pas seulement les elfes de sang. Beaucoup des meilleurs et des plus brillants érudits de Kael et des Magistères avaient été influencés par Voren'thal." WHERE entry = -1000318;
UPDATE script_texts SET content_loc2 = "Les naaru acceptèrent les déserteurs, qui seraient connus sous le nom des Clairvoyants; leur logement se trouve dans la plate-forme ci-dessus. Seuls ceux qui ont rejoint les Clairvoyants sont autorisés à aller là-bas." WHERE entry = -1000319;
UPDATE script_texts SET content_loc2 = "Les membres de l'Aldor sont des adeptes de la Lumière, le pardon et la rédemption sont des valeurs qu'ils respectent. Cependant, il leur est difficile d'oublier les actes des elfes de sang sous le commandement de Kael." WHERE entry = -1000320;
UPDATE script_texts SET content_loc2 = "Beaucoup de prêtres ont été tué par les magistères qui sont maintenant voués à servir les naaru. Ils n'aiment guère partager la ville avec leurs anciens ennemis." WHERE entry = -1000321;
UPDATE script_texts SET content_loc2 = "Le temple le plus sacré de l'Aldor, ainsi que ses habitations environnantes, se trouvent sur la terrasse au-dessus. Comme un site sacré, seuls les initiés sont les bienvenus à l'intérieur." WHERE entry = -1000322;
UPDATE script_texts SET content_loc2 = "Les attaques contre Shattrath continuent, mais la ville ne tombe pas, comme vous pouvez le voir. Au contraire, le naaru connu sous le nom Xi'ri a mené une incursion réussie dans la vallée d'Ombrelune, au pied du temple d'Illidan." WHERE entry = -1000323;
UPDATE script_texts SET content_loc2 = "Là-bas, il continue de mener la guerre contre Illidan avec l'aide de l'Aldor et des Clairvoyants. Les deux factions n'ont pas renoncé à leurs vieilles querelles, bien sûr." WHERE entry = -1000324;
UPDATE script_texts SET content_loc2 = "Leur animosité est telle qu'ils se disputent l'honneur d'être envoyés pour aider les naaru là-bas. Chaque jour, cette décision est prise ici par A'dal. Les armées se rassemblent ici pour recevoir la bénédiction de A'dal avant d'aller à Ombrelune." WHERE entry = -1000325;
UPDATE script_texts SET content_loc2 = "Khadgar devrait être prêt à vous revoir. N'oubliez pas que pour servir les Sha'tar, vous aurez très probablement besoin de vous allier avec l'Aldor ou les Clairvoyants. Et la recherche de la faveur d'un groupe entraîne l'aversion des autres." WHERE entry = -1000326;
UPDATE script_texts SET content_loc2 = "Bonne chance étranger, et bienvenue dans la ville de Shattrath." WHERE entry = -1000327;
UPDATE script_texts SET content_loc2 = "Il est temps de vous donner une leçon dans les règles de l'art, $Gpetit:petite; $Ggarçon:fille; !" WHERE entry = -1000328;
UPDATE script_texts SET content_loc2 = "Maintenant je vais vous compter jusqu'à '3 ' pour que vous partiez d'ici, ou je lance mes chiens sur vous." WHERE entry = -1000329;
UPDATE script_texts SET content_loc2 = "1..." WHERE entry = -1000330;
UPDATE script_texts SET content_loc2 = "2..." WHERE entry = -1000331;
UPDATE script_texts SET content_loc2 = "Il est temps de rencontrer votre créateur !" WHERE entry = -1000332;
UPDATE script_texts SET content_loc2 = "Très bien, nous renonçons! Ne nous tapez plus !" WHERE entry = -1000333;
UPDATE script_texts SET content_loc2 = "Merci cher Paladin, vous m'avez sauvé la vie." WHERE entry = -1000334;
UPDATE script_texts SET content_loc2 = "Allons voir les autres, et gardez un oeil sur ces loups ..." WHERE entry = -1000335;
UPDATE script_texts SET content_loc2 = "Soyez prudent, $N. Ces loups aiment se cacher derrière les arbres." WHERE entry = -1000336;
UPDATE script_texts SET content_loc2 = "Une attaque de $C !" WHERE entry = -1000337;
UPDATE script_texts SET content_loc2 = "Attention, je suis attaqué !" WHERE entry = -1000338;
UPDATE script_texts SET content_loc2 = "Nous y sommes presque !" WHERE entry = -1000339;
UPDATE script_texts SET content_loc2 = "Nous l'avons fait ! Merci, $N. Je n'aurais pas pu réussir sans vous." WHERE entry = -1000340;
UPDATE script_texts SET content_loc2 = "C'est bon de vous voir à nouveau Erland. Quel est votre rapport ?" WHERE entry = -1000341;
UPDATE script_texts SET content_loc2 = "Beaucoup de worgens sont à l'est, et quiconque a vécu au verger de Malden, a disparu." WHERE entry = -1000342;
UPDATE script_texts SET content_loc2 = "Si vous voulez bien m'excusez, j'aimerais maintenant me rendre auprès de Quinn..." WHERE entry = -1000343;
UPDATE script_texts SET content_loc2 = "Bonjour, Quinn. Comment vous en sortez-vous ?" WHERE entry = -1000344;
UPDATE script_texts SET content_loc2 = "J'ai été mieux. Ivar l'Infect fait du mieux qu'il peut..." WHERE entry = -1000345;
UPDATE script_texts SET content_loc2 = "Essayez de prendre mieux soin de vous, Quinn. Vous avez eu de la chance cette fois." WHERE entry = -1000346;
UPDATE script_texts SET content_loc2 = "Partons vite avant qu'ils s’aperçoivent que je suis libre !" WHERE entry = -1000347;
UPDATE script_texts SET content_loc2 = "Regardez ! Nous sommes attaqués !" WHERE entry = -1000348;
UPDATE script_texts SET content_loc2 = "Merci de m'avoir aidé. Je connais le chemin à partir d'ici." WHERE entry = -1000349;
UPDATE script_texts SET content_loc2 = "Qui ose réveiller Aquementas?" WHERE entry = -1000350;
UPDATE script_texts SET content_loc2 = "J'abandonne ! S'il vous plait, ne me tuez pas !" WHERE entry = -1000351;
UPDATE script_texts SET content_loc2 = "Je choisis la troisième option: VOUS TUEZ !" WHERE entry = -1000352;
UPDATE script_texts SET content_loc2 = "Ok, nous allons sortir d'ici!" WHERE entry = -1000353;
UPDATE script_texts SET content_loc2 = "Vous êtes sûr que vous êtes prêt ? Prenez un moment." WHERE entry = -1000354;
UPDATE script_texts SET content_loc2 = "Très bien, faisons ça !" WHERE entry = -1000355;
UPDATE script_texts SET content_loc2 = "Ok, je pense que je peux faire le chemin d'ici. Je vous remercie beaucoup de m'avoir sorti de là !" WHERE entry = -1000356;
UPDATE script_texts SET content_loc2 = "Belore..." WHERE entry = -1000357;
UPDATE script_texts SET content_loc2 = "s'agenouille et ramasse l'amulette." WHERE entry = -1000358;
UPDATE script_texts SET content_loc2 = "Vous avez ma bénédiction." WHERE entry = -1000359;
UPDATE script_texts SET content_loc2 = "Est-ce que la voie est libre ? Sortons tant que nous pouvons, $N." WHERE entry = -1000360;
UPDATE script_texts SET content_loc2 = "On dirait qu'on ne s'en tirera pas si facilement. Préparez-vous!" WHERE entry = -1000361;
UPDATE script_texts SET content_loc2 = "Continuons notre route. Nous ne sommes pas en sécurité ici!" WHERE entry = -1000362;
UPDATE script_texts SET content_loc2 = "Regardez, $N ! Des ennemis devant !" WHERE entry = -1000363;
UPDATE script_texts SET content_loc2 = "Nous sommes presque au refuge! Allons-y." WHERE entry = -1000364;
UPDATE script_texts SET content_loc2 = "Je peux voir mes camarades druides à partir d'ici. Merci, $N. Je suis sûr que Ysiel vous récompensera pour vos actions!" WHERE entry = -1000365;
UPDATE script_texts SET content_loc2 = "Donc, vous avez vaincu le Cachet cramoisi. Vous cherchez maintenant à contester mes règles ? Pas même Arthas pourrait me vaincre, mais vous osez quand même avoir de telles pensées? Alors je vous le dis, venez ! Venez $N ! Le Temple noir attend ..." WHERE entry = -1000366;
UPDATE script_texts SET content_loc2 = "A vos ordres, mon seigneur ..." WHERE entry = -1000367;
UPDATE script_texts SET content_loc2 = "Détruisez-les, Torloth. Laissez-les perdre leur sang comme un fleuve sur cette terre sacrée." WHERE entry = -1000368;
UPDATE script_texts SET content_loc2 = "Vos désirs sont des ordres, seigneur Illidan." WHERE entry = -1000369;
UPDATE script_texts SET content_loc2 = "Oui, seigneur Illidan, Je sacrifierais pour vous ce physique magnifique. En ce jour vous tomberez - une autre victime de Torloth ..." WHERE entry = -1000370;
UPDATE script_texts SET content_loc2 = "Quelle sorte d'imbécile ose se tenir devant Illidan Hurlorage? Soldats, détruisez ces insectes!" WHERE entry = -1000371;
UPDATE script_texts SET content_loc2 = "Vous n'êtes pas un défi pour le cachet cramoisi. Briseurs d'esprits, mettez fin à cette absurdité." WHERE entry = -1000372;
UPDATE script_texts SET content_loc2 = "Fuyez tant que vous le pouvez encore. Les généralissimes vont bientôt arriver ..." WHERE entry = -1000373;
UPDATE script_texts SET content_loc2 = "Torloth, ton maître t'appelle !" WHERE entry = -1000374;
UPDATE script_texts SET content_loc2 = "Je me souviens bien de l'aiguillon de la défaite à l'issue de la Troisième guerre. J'ai attendu trop longtemps pour ma vengeance. Maintenant l'ombre de la Légion tombe sur ce monde. Ce n'est qu'une question de temps jusqu'à ce que votre création ratée... soit supprimée." WHERE entry = -1000375;
UPDATE script_texts SET content_loc2 = "La Légion va tout conquérir !" WHERE entry = -1000376;
UPDATE script_texts SET content_loc2 = "Tous les mortels périront !" WHERE entry = -1000377;
UPDATE script_texts SET content_loc2 = "Toute vie doit être éradiquée !" WHERE entry = -1000378;
UPDATE script_texts SET content_loc2 = "Je vais arracher la chair de vos os!" WHERE entry = -1000379;
UPDATE script_texts SET content_loc2 = "Kirel Narak !" WHERE entry = -1000380;
UPDATE script_texts SET content_loc2 = "Scélérat méprisable!" WHERE entry = -1000381;
UPDATE script_texts SET content_loc2 = "L'univers sera refait." WHERE entry = -1000382;
UPDATE script_texts SET content_loc2 = "La Légion... ne tombera... jamais." WHERE entry = -1000383;
UPDATE script_texts SET content_loc2 = "entre en frénésie !" WHERE entry = -1000384;
UPDATE script_texts SET content_loc2 = "Envahisseurs, vous aller tomber dans le précipice de l'oubli! La Légion ardente vient et amène avec elle votre fin." WHERE entry = -1000385;
UPDATE script_texts SET content_loc2 = "Petits chiens imprudents, vous ne faites que retarder l'inévitable. Si un de nous tombe, dix se lèveront. Telle est la volonté de Kazzak ..." WHERE entry = -1000386;
UPDATE script_texts SET content_loc2 = "Ne pas procéder. Vous serez éliminé!" WHERE entry = -1000387;
UPDATE script_texts SET content_loc2 = "Magnitude réglée. Relâchez." WHERE entry = -1000389;
UPDATE script_texts SET content_loc2 = "Trajectoire verrouillée." WHERE entry = -1000390;
UPDATE script_texts SET content_loc2 = "Vitesse maximum engagée." WHERE entry = -1000391;
UPDATE script_texts SET content_loc2 = "Niveau de menace zéro." WHERE entry = -1000392;
UPDATE script_texts SET content_loc2 = "Directive accomplie." WHERE entry = -1000393;
UPDATE script_texts SET content_loc2 = "Cible exterminée." WHERE entry = -1000394;
UPDATE script_texts SET content_loc2 = "Défaillance du système dans cinq, q-u-a-t-r-e..." WHERE entry = -1000395;
UPDATE script_texts SET content_loc2 = "Muahahahaha! Vous êtes fou! Vous m'avez libéré de mon exil dans les interstices entre espace et le temps!" WHERE entry = -1000396;
UPDATE script_texts SET content_loc2 = "Draenor tombera rapidement sous mes pieds! Je détruirai ce monde et le remodèlerait à mon image!" WHERE entry = -1000397;
UPDATE script_texts SET content_loc2 = "Où devrais-je commencer? Je ne peux pas me tracasser avec un ver tel que vous. Il y a un monde à conquérir!" WHERE entry = -1000398;
UPDATE script_texts SET content_loc2 = "NOOOOooooooon!" WHERE entry = -1000400;
UPDATE script_texts SET content_loc2 = "Bien, $N, vous êtes sous l'influence de mon pouvoir. Je vais analyser ça rapidement, et après nous pourrons parler." WHERE entry = -1000401;
UPDATE script_texts SET content_loc2 = "Dans la maison! Restez près de moi, peu importe ce qu'il se passe ! J'ai mon fusil et des munitions là-bas!" WHERE entry = -1000402;
UPDATE script_texts SET content_loc2 = "Nous avons montré celui-ci!" WHERE entry = -1000403;
UPDATE script_texts SET content_loc2 = "Un de plus à terre !" WHERE entry = -1000404;
UPDATE script_texts SET content_loc2 = "Nous l'avons fait ! Nous avons réussi !" WHERE entry = -1000405;
UPDATE script_texts SET content_loc2 = "Retrouvez-moi au verger - J'ai juste besoin de prendre mon fusil." WHERE entry = -1000406;
UPDATE script_texts SET content_loc2 = "%s crie de joie à la vue de son déjeuner!" WHERE entry = -1000407;
UPDATE script_texts SET content_loc2 = "%s mange son déjeuner." WHERE entry = -1000408;
UPDATE script_texts SET content_loc2 = "%s vous remercie avec une danse spéciale." WHERE entry = -1000409;
UPDATE script_texts SET content_loc2 = "Mince ! Je craignais de ne jamais vous revoir! Oui, je vais bien, ne vous inquiétez pas pour moi. Il faut vous reposer et récupérer votre santé." WHERE entry = -1000411;
UPDATE script_texts SET content_loc2 = "gronde en reconnaissance avant de s'effacer et de faire son chemin dans la forêt." WHERE entry = -1000412;
UPDATE script_texts SET content_loc2 = "Le premier officier Destructomembreur est prêt à vous suivre." WHERE entry = -1000413;
UPDATE script_texts SET content_loc2 = "Yarrr! Idiot, qu'avez-vous fait?! Il est devenu fou! Abaissez les écoutilles ! Hissez le mât ! ARRRR! Chaque homme pour sa vie !" WHERE entry = -1000414;
UPDATE script_texts SET content_loc2 = "Ok, $N, allons chercher où j'ai laissé ce mystérieux fossile. Suivez-moi !" WHERE entry = -1000415;
UPDATE script_texts SET content_loc2 = "Maintenant, où ai-je pu mettre ce mystérieux fossile ? Ah peut-être ici..." WHERE entry = -1000416;
UPDATE script_texts SET content_loc2 = "Mmmh, rien ici." WHERE entry = -1000417;
UPDATE script_texts SET content_loc2 = "Pas de mystérieux fossile ici... Ah mais il y a ma copie des Vertes Collines de Strangleronce. C'est un très bon livre !" WHERE entry = -1000418;
UPDATE script_texts SET content_loc2 = "Je vous parie que je l'ai laissé dans la tente!" WHERE entry = -1000419;
UPDATE script_texts SET content_loc2 = "Oh attendez, c'est la tente d'Hollee... Et elle est vide." WHERE entry = -1000420;
UPDATE script_texts SET content_loc2 = "Intéressant... Je n'avais pas remarqué ça avant..." WHERE entry = -1000421;
UPDATE script_texts SET content_loc2 = "%s inspecte l'ancienne pierre couverte de mousse." WHERE entry = -1000422;
UPDATE script_texts SET content_loc2 = "Oh attendez ! Je suis supposé chercher le mystérieux fossile !" WHERE entry = -1000423;
UPDATE script_texts SET content_loc2 = "Non. Je n'ai pas laissé le fossile ici !" WHERE entry = -1000424;
UPDATE script_texts SET content_loc2 = "Ah. Je me souviens maintenant ! J'ai donné le mystérieux fossile à Hollee ! Vérifiez avec elle." WHERE entry = -1000425;
UPDATE script_texts SET content_loc2 = "%s retourne travailler, sans ce soucier de ce qui l'entoure." WHERE entry = -1000426;
UPDATE script_texts SET content_loc2 = "Quelque chose me dit que ce $R veut aussi le mystérieux fossile. A l'aide !" WHERE entry = -1000427;
UPDATE script_texts SET content_loc2 = "Ah ... Le son merveilleux des kodos. J'aime la façon dont ils font trembler le sol  ... Inspectez la bête pour moi." WHERE entry = -1000428;
UPDATE script_texts SET content_loc2 = "Hé, faite attention avec ce kodo! Vous feriez mieux de contrôler la bête avant que je ne vous fasse des crédits!" WHERE entry = -1000429;
UPDATE script_texts SET content_loc2 = "Ce kodo à l'air très beau. Attendez une minute, où sont mes lunettes à double foyer? Peut-être vous devriez contrôler la bête pour moi." WHERE entry = -1000430;
UPDATE script_texts SET content_loc2 = "Regardez !" WHERE entry = -1000482;
UPDATE script_texts SET content_loc2 = "Ne les laissez pas s'échapper ! Tuez le plus fort en premier !" WHERE entry = -1000483;
UPDATE script_texts SET content_loc2 = "D'autres arrivent ! Regardez !" WHERE entry = -1000484;
UPDATE script_texts SET content_loc2 = "Où pensez-vous aller ? Tuez-les tous !" WHERE entry = -1000485;
UPDATE script_texts SET content_loc2 = "Allez aussi vite que la lumière !" WHERE entry = -1000486;
UPDATE script_texts SET content_loc2 = "HORION DE GIVRE !" WHERE entry = -1000487;
UPDATE script_texts SET content_loc2 = "C'est mieux si nous nous séparons maintenant, au cas où ils en enverraient d'autres après nous. Espérons qu'un de nous parvienne à retourner auprès de Garrosh. Bonne chance, étranger." WHERE entry = -1000488;
UPDATE script_texts SET content_loc2 = "%s tend la tête vers le haut, comme s'il écoutait quelque chose." WHERE entry = -1000496;
UPDATE script_texts SET content_loc2 = "%s pousse un hurlement qui résonne vers les montagnes du nord et vous invite à le suivre." WHERE entry = -1000497;
UPDATE script_texts SET content_loc2 = "Bienvenue, esprit bienveillant. Que nous avez-vous apporté?" WHERE entry = -1000498;
UPDATE script_texts SET content_loc2 = "Ok, c'est parti." WHERE entry = -1000507;
UPDATE script_texts SET content_loc2 = "Maintenant, trouvons cette herbe." WHERE entry = -1000508;
UPDATE script_texts SET content_loc2 = "Non, pas ici..." WHERE entry = -1000509;
UPDATE script_texts SET content_loc2 = "Il doit y en avoir une quelque part par ici..." WHERE entry = -1000510;
UPDATE script_texts SET content_loc2 = "Ah, en voilà une !" WHERE entry = -1000511;
UPDATE script_texts SET content_loc2 = "Venez, $N ! Allons là-bas en cueillir !" WHERE entry = -1000512;
UPDATE script_texts SET content_loc2 = "Ok, maintenant allons-nous en d'ici" WHERE entry = -1000513;
UPDATE script_texts SET content_loc2 = "Je peux me débrouiller à partir d'ici. Merci, $N ! Et parlez à mon employeur pour votre récompense !" WHERE entry = -1000514;
UPDATE script_texts SET content_loc2 = "A l'aide ! La bête est sur moi !" WHERE entry = -1000515;
UPDATE script_texts SET content_loc2 = "Ignatz « Puant » disparaît dans le marécage." WHERE entry = -1000516;
UPDATE script_texts SET content_loc2 = "Attention ! Nous sommes attaqués !" WHERE entry = -1000709;
UPDATE script_texts SET content_loc2 = "Ce doit être la pureté de la Marque du la Lumière qui incite les Mort-Vivants à  nous attaquer. Nous devons être prudents, sinon nous allons être submergés !" WHERE entry = -1000710;
UPDATE script_texts SET content_loc2 = "Ce pays a vraiment besoin d'être purifié par la Lumière. Continuons vers la tombe, ce n'est plus très loin..." WHERE entry = -1000711;
UPDATE script_texts SET content_loc2 = "Soyez les bienvenus, frères !" WHERE entry = -1000712;
UPDATE script_texts SET content_loc2 = "Merci d'être venus ici en souvenir de moi. Vos efforts pour retrouver ce symbole, bien que non nécessaires, touchent beaucoup un vieil homme." WHERE entry = -1000713;
UPDATE script_texts SET content_loc2 = "Levez-vous, mes frères. Gardez la Bénédiction comme symbole de la force de la Lumière, et comme même des héros depuis longtemps disparus peuvent revenir briller en chacun de nous." WHERE entry = -1000714;
UPDATE script_texts SET content_loc2 = "Merci mon ami d'avoir rendu cela possible. C'est un jour que je n'oublierai jamais ! Je pense que je vais rester ici un moment. Retournez voir la Grande Prêtresse MacDonnell au camp. Je sais qu'elle sera très intéressée par savoir ce qu'il s'est passé ici." WHERE entry = -1000715;
UPDATE script_texts SET content_loc2 = "Enfants de la Nuit, entendez l'appel de votre Reine !" WHERE entry = -1000716;
UPDATE script_texts SET content_loc2 = "Je vous rejoins dans la célébration de cette nuit fêtée - la nuit où les Réprouvés ont brisé l'oppression des Mort-vivants !" WHERE entry = -1000717;
UPDATE script_texts SET content_loc2 = "C'est cette nuit que nos ennemis craignent le plus. C'est CETTE NUIT que nous montrons à nos ennemis ce qu'implique d'être opposé aux Réprouvés !" WHERE entry = -1000718;
UPDATE script_texts SET content_loc2 = "Nous brûlons cette effigie de l'Homme d'osier comme symbole de notre lutte contre ceux qui se mettent en travers de notre chemin. Nous portons les cendres de l'Homme d'osier brûlé comme symbole de notre lutte sans fin contre ceux qui nous voudraient nous enchaîner." WHERE entry = -1000719;
UPDATE script_texts SET content_loc2 = "Il est maintenant temps de faire trembler le monde sur ses bases ! MAINTENANT, il est temps de rappeler à ceux qui voudraient nous enchaîner que jamais nous ne cèderons !" WHERE entry = -1000720;
UPDATE script_texts SET content_loc2 = "MAINTENANT est venu le temps des Réprouvés ! Pouvoir aux Réprouvés - MAINTENANT ET POUR TOUJOURS !!!" WHERE entry = -1000721;
UPDATE script_texts SET content_loc2 = "Ne soyez pas surpris, le toccin a sonné ! Mettez bien à l'abri infirmes, vieillards, enfants. Chacun aura le prix en entier à payer. Implorez ma merci, à l'heure du jugement !" WHERE entry = -1000722;
UPDATE script_texts SET content_loc2 = "Le ciel est sombre. Le feu brûle. Vous combattez en vain alors que la roue du Destin tourne." WHERE entry = -1000723;
UPDATE script_texts SET content_loc2 = "La ville brûle toujours. Un feu purificateur ! Le temps est compté, je vais bientôt me retirer." WHERE entry = -1000724;
UPDATE script_texts SET content_loc2 = "Mes flammes ont décliné, plus un reflet n'y court. Je vais vous dérober votre vie, votre jour !" WHERE entry = -1000725;
UPDATE script_texts SET content_loc2 = "Le festin du brasier scelle votre débâcle. Justice a triomphé en un ardent spectacle !" WHERE entry = -1000726;
UPDATE script_texts SET content_loc2 = "Pour que coule mon sang, vous luttez sans faillir. C'est ma tête pourtant, qu'il vous faudra occire !" WHERE entry = -1000727;
UPDATE script_texts SET content_loc2 = "Ecoutez-moi ! Je vous repousse ! Maintenant, ressentez... La brûlure !" WHERE entry = -1000728;
UPDATE script_texts SET content_loc2 = "Akama... Vous êtes au courant ? J'ai été démasqué par les serviteurs de Vashj. Notre secret est en péril !" WHERE entry = -1000729;
UPDATE script_texts SET content_loc2 = "Olum, mon vieil ami. Je suis heureux de vous voir sain et sauf." WHERE entry = -1000730;
UPDATE script_texts SET content_loc2 = "Illidan me recherche. Je ne suis pas en sureté ici... Et vous non plus." WHERE entry = -1000731;
UPDATE script_texts SET content_loc2 = "Illidan va se douter de quelque chose, c'est une certitude. Nous nous en chargerons, comme d'habitude." WHERE entry = -1000732;
UPDATE script_texts SET content_loc2 = "Illidan me retrouvera. Et alors... Il m'arrachera le secret des Cendrelangues. Tel est le pouvoir du Traître ! Non... Il ne reste qu'une issue. J'ai cessé d'être utile à la cause. Je dois partir pour le monde des esprits." WHERE entry = -1000733;
UPDATE script_texts SET content_loc2 = "Vous n'êtes pas... sérieux, Olum. Vous avez déjà  fait un bien trop grand sacrifice." WHERE entry = -1000734;
UPDATE script_texts SET content_loc2 = "Ma décision est irrévocable. Je n'en démordrai pas. J'ai voué ma vie à notre plan. Le mettre en péril aujourd'hui reviendrait à trahir tous ceux qui sont morts pour la cause bien avant moi." WHERE entry = -1000735;
UPDATE script_texts SET content_loc2 = "Vous semblez avoir pris votre décision. Nous vous guiderons vers le monde des esprits avec tous les égards possibles." WHERE entry = -1000736;
UPDATE script_texts SET content_loc2 = "Je vous remercie, Akama. Vous me faites honneur en m'offrant ce moment, entouré par mes frères. Adieu, mon ami. Et guidez bien notre peuple." WHERE entry = -1000737;
UPDATE script_texts SET content_loc2 = "Adieu, mon cher ami. Nous vous retrouverons dans un autre monde quand nos devoirs envers celui-ci seront remplis." WHERE entry = -1000738;
UPDATE script_texts SET content_loc2 = "Maître ! Nous avons trouvé le traitre qui a échappé à Vashj. Son corps est étendu devant moi, sans vie !" WHERE entry = -1000739;
UPDATE script_texts SET content_loc2 = "Tu me déçois, Akama. Je voulais interroger moi-même cette vermine de traître. Je commence à avoir des doutes sur ton allégeance, Roué." WHERE entry = -1000740;
UPDATE script_texts SET content_loc2 = "Mais Sire ! Vous vous méprenez sur mes actes... J'ai appris que l'un de vos proches projette de vous trahir. C'est ce chien de Kael'thas ! Il s'est allié avec Kil'jaeden et cherche à devenir seigneur de l'Outreterre à votre place !" WHERE entry = -1000741;
UPDATE script_texts SET content_loc2 = "Je ne perçois aucun mensonge dans ta voix, Akama. Que Kael'thas cherche à me trahir n'est pas une grand surprise - je ne suis pas aussi inconscient que certains aimeraient le penser. Mais que l'un des tiens se soit associé à lui remet ta loyauté en question." WHERE entry = -1000742;
UPDATE script_texts SET content_loc2 = "Envoie ton Cendrelangue au Donjon de la Tempête et tue son bien le plus cher, le phénix appelé A'lar. Je dois m'assurer que tu n'es pas dans son camp. Ne songe pas à me trahir, Roué. Nous savons tous deux qui possède ton âme !" WHERE entry = -1000743;
UPDATE script_texts SET content_loc2 = "Ce sera fait, seigneur !" WHERE entry = -1000744;
UPDATE script_texts SET content_loc2 = "Défenseurs, montrez à ces bâtards la furie d'un Clairvoyant !" WHERE entry = -1000745;
UPDATE script_texts SET content_loc2 = "Tenez bon, soldats. Ne faites pas de quartier !" WHERE entry = -1000746;
UPDATE script_texts SET content_loc2 = "BRÛLEZ TOUT !" WHERE entry = -1000747;
UPDATE script_texts SET content_loc2 = "TUEZ LES TOUS !" WHERE entry = -1000748;
UPDATE script_texts SET content_loc2 = "Pour les Gueule-de-dragon !" WHERE entry = -1000749;
UPDATE script_texts SET content_loc2 = "Tes os vont casser sous mes bottes, draenei !" WHERE entry = -1000750;
UPDATE script_texts SET content_loc2 = "Longue vie aux Gueule-de-dragon ! Meurs, draenei inutile !" WHERE entry = -1000751;
UPDATE script_texts SET content_loc2 = "Tes os vont casser sous mes bottes, elfe de sang !" WHERE entry = -1000752;
UPDATE script_texts SET content_loc2 = "Longue vie aux Gueule-de-dragon ! Meurs, elfe de sang inutile !" WHERE entry = -1000753;
UPDATE script_texts SET content_loc2 = "Défenseurs, montrez à ces bâtards la furie d'un membre de l'Aldor !" WHERE entry = -1000754;
UPDATE script_texts SET content_loc2 = "Tenez bon, soldats. Ne faites pas de quartier !" WHERE entry = -1000755;
UPDATE script_texts SET content_loc2 = "Victoire aux Clairvoyants ! Les Gueule-de-dragon ont été défaits !" WHERE entry = -1000756;
UPDATE script_texts SET content_loc2 = "Victoire à l'Aldor ! Les Gueule-de-dragon ont été défaits !" WHERE entry = -1000757;
UPDATE script_texts SET content_loc2 = "Nous sommes encerclés !" WHERE entry = -1000758;
UPDATE script_texts SET content_loc2 = "Ne les laissez pas s'échapper ! Tuez le plus fort d'abord !" WHERE entry = -1000759;
UPDATE script_texts SET content_loc2 = "Il en arrive d'autres ! Attention !" WHERE entry = -1000760;
UPDATE script_texts SET content_loc2 = "Où pensez-vous aller ? Tuez-les tous !" WHERE entry = -1000761;
UPDATE script_texts SET content_loc2 = "Allez aussi vite que la lumière !" WHERE entry = -1000762;
UPDATE script_texts SET content_loc2 = "HORION DE GIVRE !" WHERE entry = -1000763;
UPDATE script_texts SET content_loc2 = "Devant nous se trouve la route de Telaar. Nous nous séparerons à l'embranchement, car ils enverront sûrement d'autres Bourbesang à nos trousses. Espérons que l'un d'entre nous arrivera à Telaar vivant." WHERE entry = -1000764;
UPDATE script_texts SET content_loc2 = "Dans la boîte mes jolis ! C'est ça. Un par un." WHERE entry = -1000765;
UPDATE script_texts SET content_loc2 = "Très bien, allons-y." WHERE entry = -1000766;
UPDATE script_texts SET content_loc2 = "On dirait que nous avons des problèmes. Soyez attentifs, ils arrivent !" WHERE entry = -1000767;
UPDATE script_texts SET content_loc2 = "Vous avez trouvé des assassins de ce culte... Partons avant que quelqu'un d'autre nous trouve ici." WHERE entry = -1000768;
UPDATE script_texts SET content_loc2 = "Attendez ! Je sens une présence diabolique ici... Mort-vivant !" WHERE entry = -1000769;
UPDATE script_texts SET content_loc2 = "Un paladin ! Le maître serait ravi par sa mort. A l'attaque !" WHERE entry = -1000770;
UPDATE script_texts SET content_loc2 = "Il en arrive énormément aujourd'hui. Continuons notre route ou nous pourrions rencontrer d'autres choses encore qui voudraient me voir mort." WHERE entry = -1000771;
UPDATE script_texts SET content_loc2 = "Encore ces trois là ?" WHERE entry = -1000772;
UPDATE script_texts SET content_loc2 = "Pas aussi sûr de toi sans le Purificateur, hein ?" WHERE entry = -1000773;
UPDATE script_texts SET content_loc2 = "Je vais en finir avec toi une bonne fois pour toutes !" WHERE entry = -1000774;
UPDATE script_texts SET content_loc2 = "Bien joué ! Je devrais être en sécurité à partir d'ici. Rappelez-vous de parler à Delgren quand vous retournerez au Poste de Maestra à Orneval." WHERE entry = -1000775;
UPDATE script_texts SET content_loc2 = "Allons-y. Mon équipement devrait se trouver dans l'entrepôt là-bas..." WHERE entry = -1000776;
UPDATE script_texts SET content_loc2 = "Vérifiez cette cellule, $N. Si quelqu'un est en vie là-dedans, nous devons l'en sortir." WHERE entry = -1000777;
UPDATE script_texts SET content_loc2 = "Merci, $N ! Je suis libre !!!" WHERE entry = -1000778;
UPDATE script_texts SET content_loc2 = "Sortez-le de là !" WHERE entry = -1000779;
UPDATE script_texts SET content_loc2 = "Bon travail ! Nous y sommes presque, $N. Par ici." WHERE entry = -1000780;
UPDATE script_texts SET content_loc2 = "C'est ici, $N. Mes affaires doivent être dans cette pièce. Couvrez-moi, j'entre !" WHERE entry = -1000781;
UPDATE script_texts SET content_loc2 = "Pouvez-vous sentir la puissance, $N ??? Ca va faire mal !" WHERE entry = -1000782;
UPDATE script_texts SET content_loc2 = "Maintenant, il ne nous reste plus qu'à trouver Tobias et nous pouvons sortir d'ici. Par là !" WHERE entry = -1000783;
UPDATE script_texts SET content_loc2 = "Ouvrez-la." WHERE entry = -1000784;
UPDATE script_texts SET content_loc2 = "Ca va laisser des marques !" WHERE entry = -1000785;
UPDATE script_texts SET content_loc2 = "Je n'ai jamais aimé ces deux-là. Continuons." WHERE entry = -1000786;
UPDATE script_texts SET content_loc2 = "Ouvrez-la, et soyez prudent cette fois !" WHERE entry = -1000787;
UPDATE script_texts SET content_loc2 = "Peut-être qu'Ograbisi utilisera votre tête comme un petit chapeau quand j'en aurai terminé avec vous." WHERE entry = -1000788;
UPDATE script_texts SET content_loc2 = "Ressens les gifles de la fureur, Shill Dinger !" WHERE entry = -1000789;
UPDATE script_texts SET content_loc2 = "Cet individu aura finalement obtenu ce qui l'attendait. Bon débarras !" WHERE entry = -1000790;
UPDATE script_texts SET content_loc2 = "Ouvrez-la. Nous devons nous dépêcher. Je peux sentir ces Sombrefers arriver à un kilomètre et je peux vous dire une chose, ILS ARRIVENT !" WHERE entry = -1000791;
UPDATE script_texts SET content_loc2 = "Dans le pays d'où je viens, vous vous faites tuer pour avoir ouvert la porte d'un compagnon de cellule !" WHERE entry = -1000792;
UPDATE script_texts SET content_loc2 = "Ressens les gifles de la fureur, Tueur des sommets !" WHERE entry = -1000793;
UPDATE script_texts SET content_loc2 = "Il doit être dans la dernière cellule. A moins... qu'ils l'aient tué." WHERE entry = -1000794;
UPDATE script_texts SET content_loc2 = "Sortez-le de là !" WHERE entry = -1000795;
UPDATE script_texts SET content_loc2 = "Enfin !! Je peux quitter ce dépotoir !" WHERE entry = -1000796;
UPDATE script_texts SET content_loc2 = "Excellent travail, $N. Essayons de trouver une sortie. Je pense que je connais le chemin. Suivez-moi !" WHERE entry = -1000797;
UPDATE script_texts SET content_loc2 = "Nous avons réussi !" WHERE entry = -1000798;
UPDATE script_texts SET content_loc2 = "Retrouvez-moi au camp de Maxwell. Nous discuterons des prochaines étapes de notre plan et réfléchirons à un moyen de décoder mes tablettes sans l'anneau de décryptage." WHERE entry = -1000799;
UPDATE script_texts SET content_loc2 = "La moitié est morte..." WHERE entry = -1000800;
UPDATE script_texts SET content_loc2 = "Un défenseur est tombé !" WHERE entry = -1000801;
UPDATE script_texts SET content_loc2 = "Faites attention, $N. Regardez à l'ouest !" WHERE entry = -1000802;
UPDATE script_texts SET content_loc2 = "Les Kolkars sont les plus forts !" WHERE entry = -1000803;
UPDATE script_texts SET content_loc2 = "Parfait, écoutez-moi ! Formez un cercle autour de moi et allons-y !" WHERE entry = -1000804;
UPDATE script_texts SET content_loc2 = "$R, votre travail est de veiller à notre sécurité pendant nos fouilles. Nous vous paierons en retour." WHERE entry = -1000805;
UPDATE script_texts SET content_loc2 = "Le site de fouille est juste au nord d'ici." WHERE entry = -1000806;
UPDATE script_texts SET content_loc2 = "Nous y sommes ! Commencez à fouiller !" WHERE entry = -1000807;
UPDATE script_texts SET content_loc2 = "Je crois qu'il y a quelque chose enterré ici, sous le sable !" WHERE entry = -1000808;
UPDATE script_texts SET content_loc2 = "J'y suis presque !" WHERE entry = -1000809;
UPDATE script_texts SET content_loc2 = "Par la barbe de Brann ! Qu'est-ce que c'est que ça ?! On dirait... un tambour." WHERE entry = -1000810;
UPDATE script_texts SET content_loc2 = "Wow... Un tambour." WHERE entry = -1000811;
UPDATE script_texts SET content_loc2 = "Cette découverte va sûrement faire trembler l'archéologie moderne sur ses bases." WHERE entry = -1000812;
UPDATE script_texts SET content_loc2 = "Ouais, super. On peut partir maintenant ? Ce désert me donne la chair de poule." WHERE entry = -1000813;
UPDATE script_texts SET content_loc2 = "Vous êtes devenus fous ? Vous espérez que je vais laisser derrière moi un tambour sans avoir d'abord frappé dessus ?  Pas un fils de Forgefer ! Non messieurs !" WHERE entry = -1000814;
UPDATE script_texts SET content_loc2 = "Ça me rappelle la fois où il nous a fait chercher dans Silithus après des preuves de l'existence des gnomes des sables." WHERE entry = -1000815;
UPDATE script_texts SET content_loc2 = "Ou la fois où vous nous avez raconté que vous alliez découvrir un remède à la peste du 20e siècle. Déjà, qu'est-ce que c'est, le 20e siècle ?" WHERE entry = -1000816;
UPDATE script_texts SET content_loc2 = "Je pense que ça ne vaut pas la fois où il nous a raconté qu'il avait entendu dire que le squelette du \"cousin\" d'Arthas était gelé sous un glacier au Berceau-de-l'Hiver. Je n'oublierai jamais celle là, Letoll. Sérieusement... Le cousin d'Arthas ?" WHERE entry = -1000817;
UPDATE script_texts SET content_loc2 = "Je ne sais pas. Ça ne peut pas battre la fois où il a tenté de nous convaincre que nous n'étions en fait qu'un produit de l'imagination de quelque être et qu'il nous utilisait pour son amusement personnel. Ça l'a vraiment fait pendant le souper de famille." WHERE entry = -1000818;
UPDATE script_texts SET content_loc2 = "Taisez-vous ! Je vais frapper ce tambour et c'est tout !" WHERE entry = -1000819;
UPDATE script_texts SET content_loc2 = "frappe sur le tambour." WHERE entry = -1000820;
UPDATE script_texts SET content_loc2 = "PRENDS ÇA ! Je t'avais dit qu'il y avait quelque chose ici !" WHERE entry = -1000821;
UPDATE script_texts SET content_loc2 = "Ne restez pas là à rien faire, aidez-le !" WHERE entry = -1000822;
UPDATE script_texts SET content_loc2 = "ramasse le tambour." WHERE entry = -1000823;
UPDATE script_texts SET content_loc2 = "Vous avez été d'une aide précieuse, $R. Allons-nous en d'ici avant que d'autres de ces choses se montrent. Je ferai savoir à Nanowitz que vous avez fait votre travail de façon admirable." WHERE entry = -1000824;
UPDATE script_texts SET content_loc2 = "Merci de votre aide. Barrons-nous d'ici !" WHERE entry = -1000825;
UPDATE script_texts SET content_loc2 = "Continuons à avancer. Je n'aime pas cet endroit." WHERE entry = -1000826;
UPDATE script_texts SET content_loc2 = "Encore merci. Le sergent Doryn sera heureux de savoir qu'il a un éclaireur de moins à remplacer cette semaine." WHERE entry = -1000827;
UPDATE script_texts SET content_loc2 = "Merci de m'avoir libéré. Je vais ouvrir cette porte pour vous, ensuite je sortirai d'ici." WHERE entry = -1033000;
UPDATE script_texts SET content_loc2 = "Je possède uniquement le sort pour ouvrir cette porte. Malheureusement les portes des cellules ne sont pas fermées par hasard." WHERE entry = -1033001;
UPDATE script_texts SET content_loc2 = "Ça y est ! Grande ouverte. Bonne chance pour vaincre ce qui réside derrière. Je dois d'abord faire mon rapport au Kirin Tor !" WHERE entry = -1033002;
UPDATE script_texts SET content_loc2 = "Vous êtes bien courageux de vouloir braver les horreurs qui se trouvent derrière cette porte." WHERE entry = -1033004;
UPDATE script_texts SET content_loc2 = "Nous y voilà !" WHERE entry = -1033005;
UPDATE script_texts SET content_loc2 = "Bonne chance avec Arugal. Je dois maintenant retrouver Hadrec rapidement." WHERE entry = -1033006;
UPDATE script_texts SET content_loc2 = "Il était temps que quelqu'un tue le décharné." WHERE entry = -1033007;
UPDATE script_texts SET content_loc2 = "Pour une, fois je suis d'accord avec vous... raclure." WHERE entry = -1033008;
UPDATE script_texts SET content_loc2 = "Vous là ! Occupez-vous de ce bruit bizarre." WHERE entry = -1036000;
UPDATE script_texts SET content_loc2 = "Nous sommes attaqués ! Repoussez les envahisseurs !" WHERE entry = -1036001;
UPDATE script_texts SET content_loc2 = "Enfin ! Vous pouvez réveiller Naralex ! Venez m'aider, braves aventuriers !" WHERE entry = -1043000;
UPDATE script_texts SET content_loc2 = "Je dois faire les préparatifs nécessaires avant de pouvoir commencer le rituel de réveil. Vous devez me protéger !" WHERE entry = -1043001;
UPDATE script_texts SET content_loc2 = "Ces cavernes furent jadis un temple de résurrection dans les Tarides. Aujourd’hui, elles sont les salles des cauchemars." WHERE entry = -1043002;
UPDATE script_texts SET content_loc2 = "Venez. Nous devons continuer ! Il y a encore beaucoup à faire avant de pouvoir tirer Naralex de son cauchemar." WHERE entry = -1043003;
UPDATE script_texts SET content_loc2 = "Au sein de ce cercle de feu, je dois lancer le sort qui bannira les esprits des seigneurs-Croc tombés au champ d’honneur." WHERE entry = -1043004;
UPDATE script_texts SET content_loc2 = "Les cavernes ont été purifiées. Allons dans les appartements de Naralex !" WHERE entry = -1043005;
UPDATE script_texts SET content_loc2 = "Au-delà de ce couloir, Naralex dort d'un sommeil agité. Allons le réveiller avant qu’il ne soit trop tard." WHERE entry = -1043006;
UPDATE script_texts SET content_loc2 = "Accordez-moi votre protection, âmes courageuses, pendant que je fouille dans les profondeurs du Rêve d'émeraude pour secourir Naralex et mettre un terme à cette corruption !" WHERE entry = -1043007;
UPDATE script_texts SET content_loc2 = "commence à effectuer le rituel de réveil sur Naralex." WHERE entry = -1043008;
UPDATE script_texts SET content_loc2 = "se retourne par à-coups dans un sommeil troublé." WHERE entry = -1043009;
UPDATE script_texts SET content_loc2 = "se tord, à l'agonie. Le Disciple semble progresser." WHERE entry = -1043010;
UPDATE script_texts SET content_loc2 = "semble rêver d'une chose horrible. Quelque chose remue à la surface de l'eau trouble." WHERE entry = -1043011;
UPDATE script_texts SET content_loc2 = "Mutanus le Dévoreur est sûrement au service du cauchemar de Naralex !" WHERE entry = -1043012;
UPDATE script_texts SET content_loc2 = "ENFIN JE SUIS ÉVEILLÉ !" WHERE entry = -1043013;
UPDATE script_texts SET content_loc2 = "Enfin ! Naralex émerge de son cauchemar." WHERE entry = -1043014;
UPDATE script_texts SET content_loc2 = "Ah, être enfin arraché aux griffes du redoutable cauchemar ! Je vous remercie, mon fidèle Disciple, ainsi que vos braves compagnons." WHERE entry = -1043015;
UPDATE script_texts SET content_loc2 = "Nous devons aller rejoindre les autres Disciples. Il y a beaucoup de travail à faire avant que je ne puisse à nouveau tenter de rétablir les Tarides. Adieu, braves âmes !" WHERE entry = -1043016;
UPDATE script_texts SET content_loc2 = "On m'attaque ! Aidez-moi à me débarrasser de ce maudit $N !" WHERE entry = -1043017;
UPDATE script_texts SET content_loc2 = "Du hast!" WHERE entry = -1043900;
UPDATE script_texts SET content_loc2 = "Fiouu! Enfin dehors. Par contre, les choses ne vont pas devenir plus simple. Retenez votre contrariété." WHERE entry = -1047000;
