UPDATE trinity_string SET content_default = "You never had credits." WHERE entry = 11503;
UPDATE shop_orders  SET name = "rename" WHERE id = 19;
UPDATE shop_orders  SET name = "gold" WHERE id = 29;
UPDATE shop_orders  SET name = "mount 1" WHERE id = 48;
UPDATE shop_orders  SET name = "mount 2" WHERE id = 49;
UPDATE shop_orders  SET name = "mount 3" WHERE id = 50;
UPDATE shop_orders  SET name = "mount 4" WHERE id = 51;
UPDATE shop_orders  SET name = "mount 5" WHERE id = 52;
UPDATE shop_orders  SET name = "mount 6" WHERE id = 53;
UPDATE shop_orders  SET name = "mount 7" WHERE id = 54;
UPDATE shop_orders  SET name = "bag 1" WHERE id = 55;
UPDATE shop_orders  SET name = "bag 2" WHERE id = 56;
UPDATE shop_orders  SET name = "weapon 1" WHERE id = 57;
UPDATE shop_orders  SET name = "weapon 2" WHERE id = 58;
UPDATE shop_orders  SET name = "weapon 3" WHERE id = 59;
UPDATE shop_orders  SET name = "weapon 4" WHERE id = 60;
UPDATE shop_orders  SET name = "weapon 5" WHERE id = 61;
UPDATE shop_orders  SET name = "weapon 6" WHERE id = 62;
UPDATE shop_orders  SET name = "weapon 7" WHERE id = 63;
UPDATE shop_orders  SET name = "weapon 8" WHERE id = 64;
UPDATE shop_orders  SET name = "weapon 9" WHERE id = 65;
UPDATE shop_orders  SET name = "character" WHERE (id BETWEEN 395 AND 403) OR (id BETWEEN 413 AND 416) OR (id BETWEEN 425 AND 446) OR (id BETWEEN 454 AND 457) OR (id BETWEEN 462 AND 474);
UPDATE shop_orders  SET name = "bear mount" WHERE id = 487;
#... not all done
